# -*- coding: utf-8 -*-
# Gera data/books/gn/37-50.json — Gênesis, capítulos 37 a 50
# Adaptação em português moderno, fiel aos escritos originais,
# elaborada a partir de traduções de domínio público (Almeida 1911 / Tradução Brasileira 1917).
import json, os

def V(v, text):
    return {"v": v, "text": text}

CH = {}

CH["37"] = {
  "verses": 36,
  "summary": "José, o filho preferido de Jacó, tem sonhos de grandeza que despertam a inveja dos irmãos. Eles o jogam num poço e o vendem como escravo a mercadores que vão para o Egito.",
  "sections": [
    {"title": "Os sonhos de José", "start": 1},
    {"title": "José é vendido pelos irmãos", "start": 12},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Jacó passou a morar na terra de Canaã, onde o seu pai tinha vivido como estrangeiro."),
      V(2, "Esta é a história de Jacó. José tinha dezessete anos e pastoreava os rebanhos com os irmãos, os filhos de Bila e de Zilpa, mulheres do seu pai. E José trazia ao pai más notícias sobre eles."),
      V(3, "Israel amava José mais do que a todos os outros filhos, porque tinha nascido na sua velhice; e mandou fazer para ele uma túnica longa e colorida."),
      V(4, "Os irmãos viram que o pai o amava mais do que a todos eles, e passaram a odiá-lo; já não conseguiam falar com ele em paz."),
      V(5, "José teve um sonho e o contou aos irmãos; por isso o odiaram ainda mais."),
      V(6, "Ele disse: “Ouçam o sonho que tive:"),
      V(7, "estávamos amarrando feixes no campo, e o meu feixe se levantou e ficou em pé; os feixes de vocês se juntaram ao redor e se curvaram diante do meu.”"),
      V(8, "Os irmãos disseram: “Então você vai reinar sobre nós? Vai governar sobre nós?” E o odiaram ainda mais, por causa dos sonhos e das palavras dele."),
      V(9, "José teve outro sonho e contou aos irmãos: “Tive outro sonho: o sol, a lua e onze estrelas se curvavam diante de mim.”"),
      V(10, "Quando contou ao pai e aos irmãos, o pai o repreendeu: “Que sonho é esse? Será que eu, a sua mãe e os seus irmãos viremos a nos curvar até o chão diante de você?”"),
      V(11, "Os irmãos ficaram com ciúmes dele, mas o pai guardou aquilo no coração."),
    ]},
    {"verses": [
      V(12, "Os irmãos de José foram pastorear os rebanhos do pai, perto de Siquém."),
      V(13, "Israel disse a José: “Os seus irmãos estão pastoreando perto de Siquém. Venha, vou enviá-lo até eles.” José respondeu: “Aqui estou.”"),
      V(14, "O pai disse: “Vá ver se os seus irmãos vão bem e se os rebanhos estão bem, e traga-me notícias.” Ele o enviou do vale de Hebrom, e José chegou a Siquém."),
      V(15, "Um homem o encontrou vagando pelo campo e perguntou: “O que você está procurando?”"),
      V(16, "Ele respondeu: “Procuro os meus irmãos. Pode me dizer onde eles estão pastoreando?”"),
      V(17, "O homem disse: “Eles partiram daqui, e eu os ouvi dizer: ‘Vamos para Dotã.’” José foi atrás dos irmãos e os encontrou em Dotã."),
      V(18, "Eles o viram de longe e, antes que chegasse perto, planejaram matá-lo."),
      V(19, "Disseram uns aos outros: “Lá vem o sonhador!"),
      V(20, "Vamos matá-lo e jogá-lo num destes poços, e diremos que um animal feroz o devorou. Veremos então o que vai acontecer com os sonhos dele.”"),
      V(21, "Rúben ouviu e quis livrá-lo das mãos deles: “Não vamos tirar a vida dele.”"),
      V(22, "E acrescentou: “Não derramem sangue. Joguem-no neste poço do deserto, mas não levantem as mãos contra ele.” Ele disse isso para livrar José e devolvê-lo ao pai."),
      V(23, "Quando José chegou aos irmãos, eles arrancaram dele a túnica longa e colorida que vestia,"),
      V(24, "agarraram-no e o jogaram no poço, que estava vazio e sem água."),
      V(25, "Depois se sentaram para comer. Levantaram os olhos e viram uma caravana de ismaelitas vindo de Gileade, com camelos carregados de especiarias, bálsamo e mirra, a caminho do Egito."),
      V(26, "Judá disse aos irmãos: “O que ganhamos matando o nosso irmão e escondendo o sangue dele?"),
      V(27, "Vamos vendê-lo aos ismaelitas. Não levantemos as mãos contra ele, afinal é nosso irmão, da nossa própria carne.” Os irmãos concordaram."),
      V(28, "Quando os mercadores midianitas passaram, os irmãos tiraram José do poço e o venderam aos ismaelitas por vinte moedas de prata. E José foi levado ao Egito."),
      V(29, "Rúben voltou ao poço e viu que José não estava mais lá. Então rasgou as suas roupas,"),
      V(30, "voltou aos irmãos e disse: “O menino não está lá! Para onde eu vou agora?”"),
      V(31, "Eles pegaram a túnica de José, mataram um cabrito e mergulharam a túnica no sangue."),
      V(32, "Enviaram a túnica colorida ao pai, com esta mensagem: “Achamos isto. Veja se é a túnica do seu filho ou não.”"),
      V(33, "Ele a reconheceu e disse: “É a túnica do meu filho! Um animal feroz o devorou! José foi despedaçado!”"),
      V(34, "Jacó rasgou as próprias roupas, vestiu-se de pano de saco e chorou pelo filho durante muitos dias."),
      V(35, "Todos os seus filhos e filhas vieram consolá-lo, mas ele não aceitou consolo e disse: “Descerei chorando ao túmulo, para junto do meu filho.” Assim o pai chorou por ele."),
      V(36, "Enquanto isso, no Egito, os midianitas venderam José a Potifar, oficial do faraó e capitão da guarda."),
    ]},
  ],
}

CH["38"] = {
  "verses": 30,
  "summary": "A história de Judá e Tamar: depois de perder dois maridos, Tamar age de forma ousada para garantir a sua descendência. Judá reconhece a justiça dela, e nascem gêmeos — entre eles Perez, ancestral do rei Davi.",
  "sections": [
    {"title": "Judá e Tamar", "start": 1},
    {"title": "O nascimento de Perez e Zerá", "start": 27},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Nessa época, Judá se separou dos irmãos e foi morar na casa de um homem de Adulão, chamado Hira."),
      V(2, "Ali Judá viu a filha de um cananeu chamado Suá, casou-se com ela e se deitou com ela."),
      V(3, "Ela engravidou e deu à luz um filho, a quem ele chamou Er."),
      V(4, "Engravidou de novo e deu à luz um filho, a quem chamou Onã."),
      V(5, "Engravidou ainda outra vez e deu à luz um filho, a quem chamou Selá. Judá estava em Quezibe quando ela deu à luz."),
      V(6, "Judá arranjou para Er, o seu primogênito, uma mulher chamada Tamar."),
      V(7, "Mas Er, o primogênito de Judá, era mau aos olhos do Senhor, e o Senhor o matou."),
      V(8, "Então Judá disse a Onã: “Deite-se com a mulher do seu irmão, cumpra o dever de cunhado e dê descendência ao seu irmão.”"),
      V(9, "Onã, porém, sabia que a descendência não seria dele. Por isso, sempre que se deitava com a mulher do irmão, deixava o sêmen cair no chão, para não dar descendência ao irmão."),
      V(10, "Aquilo que ele fazia desagradou ao Senhor, que também o matou."),
      V(11, "Judá disse a Tamar, sua nora: “Fique viúva na casa do seu pai, até que Selá, meu filho, cresça.” Pois pensava: “É melhor que ele não morra como os irmãos.” Tamar foi morar na casa do pai."),
      V(12, "Muito tempo depois, a filha de Suá, mulher de Judá, morreu. Terminado o luto, Judá subiu a Timna, onde tosquiavam as suas ovelhas, com Hira, o adulamita, seu amigo."),
      V(13, "Contaram a Tamar: “O seu sogro está subindo a Timna para tosquiar as ovelhas.”"),
      V(14, "Ela trocou as roupas de viúva, cobriu-se com um véu e se sentou à entrada de Enaim, no caminho de Timna, porque viu que Selá já tinha crescido, e ela não tinha sido dada a ele como mulher."),
      V(15, "Judá a viu e pensou que era uma prostituta, porque ela tinha coberto o rosto."),
      V(16, "Ele se aproximou dela à beira do caminho e disse: “Venha, deixe-me deitar com você” — sem saber que era a sua nora. Ela perguntou: “O que você me dará para se deitar comigo?”"),
      V(17, "Ele respondeu: “Mandarei um cabrito do rebanho.” Ela perguntou: “Você me dá um penhor até mandá-lo?”"),
      V(18, "Ele perguntou: “Que penhor devo dar?” Ela respondeu: “O seu selo com o cordão e o cajado que você tem na mão.” Ele os entregou, deitou-se com ela, e ela engravidou dele."),
      V(19, "Ela se levantou, foi embora, tirou o véu e voltou a vestir as roupas de viúva."),
      V(20, "Judá enviou o cabrito por meio do seu amigo adulamita, para receber de volta o penhor das mãos da mulher, mas ele não a encontrou."),
      V(21, "Perguntou aos homens do lugar: “Onde está a prostituta sagrada que se sentava à beira do caminho, em Enaim?” Eles responderam: “Não houve nenhuma prostituta sagrada aqui.”"),
      V(22, "Ele voltou a Judá e disse: “Não a encontrei. E os homens do lugar disseram que não houve prostituta ali.”"),
      V(23, "Judá disse: “Que fique com o penhor, para não passarmos vergonha. Eu mandei o cabrito, mas você não a encontrou.”"),
      V(24, "Cerca de três meses depois, contaram a Judá: “Tamar, a sua nora, se prostituiu e ficou grávida.” Judá disse: “Tragam-na para fora e queimem-na!”"),
      V(25, "Enquanto a levavam, ela mandou dizer ao sogro: “Estou grávida do homem a quem pertencem estas coisas.” E acrescentou: “Reconheça, por favor, de quem são este selo, este cordão e este cajado.”"),
      V(26, "Judá os reconheceu e disse: “Ela é mais justa do que eu, porque não a dei a Selá, meu filho.” E nunca mais se deitou com ela."),
    ]},
    {"verses": [
      V(27, "Quando chegou o tempo do parto, havia gêmeos no ventre dela."),
      V(28, "Durante o parto, um deles pôs a mão para fora, e a parteira amarrou um fio vermelho na mão dele, dizendo: “Este saiu primeiro.”"),
      V(29, "Mas ele recolheu a mão, e saiu o irmão. A parteira disse: “Que brecha você abriu!” Por isso o chamaram Perez — “brecha”."),
      V(30, "Depois saiu o irmão, que tinha o fio vermelho na mão, e o chamaram Zerá — “vermelho”."),
    ]},
  ],
}

CH["39"] = {
  "verses": 23,
  "summary": "José prospera na casa de Potifar, mas a mulher do oficial tenta seduzi-lo. Ele foge do pecado e, acusado injustamente, vai para a prisão — onde o Senhor continua com ele.",
  "sections": [
    {"title": "José na casa de Potifar", "start": 1},
    {"title": "A falsa acusação", "start": 6},
    {"title": "José na prisão", "start": 19},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "José foi levado ao Egito, e Potifar, oficial do faraó e capitão da guarda, um egípcio, comprou-o dos ismaelitas que o tinham levado para lá."),
      V(2, "O Senhor estava com José, que prosperou em tudo. Ele morava na casa do seu senhor egípcio."),
      V(3, "O senhor viu que o Senhor estava com José e fazia prosperar tudo o que ele tocava."),
      V(4, "José conquistou a confiança de Potifar e passou a servi-lo pessoalmente. Potifar o pôs como administrador da sua casa e entregou nas mãos dele tudo o que possuía."),
      V(5, "Desde que o pôs como administrador da casa e de todos os bens, o Senhor abençoou a casa do egípcio por causa de José. A bênção do Senhor estava sobre tudo o que ele tinha, na casa e no campo."),
      V(6, "Potifar deixou tudo o que tinha aos cuidados de José e, com ele ali, não se preocupava com nada, a não ser com a própria comida. José era bonito de corpo e de rosto."),
    ]},
    {"verses": [
      V(7, "Depois de algum tempo, a mulher do seu senhor pôs os olhos em José e disse: “Deite-se comigo.”"),
      V(8, "Ele recusou e disse à mulher do senhor: “O meu senhor confiou em mim e não se preocupa com nada da casa; entregou nas minhas mãos tudo o que tem."),
      V(9, "Nesta casa, ninguém é maior do que eu. Nada ele me negou, a não ser você, porque é a mulher dele. Como eu poderia cometer tamanha maldade e pecar contra Deus?”"),
      V(10, "Ela insistia com José dia após dia, mas ele não aceitava deitar-se com ela nem ficar perto dela."),
      V(11, "Certo dia, José entrou na casa para fazer o seu trabalho, e nenhum dos servos estava lá."),
      V(12, "Ela o agarrou pela roupa e disse: “Deite-se comigo!” Mas José deixou a roupa nas mãos dela e fugiu para fora."),
      V(13, "Quando ela viu que ele tinha fugido, deixando a roupa nas mãos dela,"),
      V(14, "chamou os servos da casa e disse: “Vejam! Trouxeram-nos este hebreu para zombar de nós! Ele veio até mim para se deitar comigo, mas eu gritei."),
      V(15, "Quando me ouviu gritar, deixou a roupa ao meu lado e fugiu.”"),
      V(16, "Ela guardou a roupa de José ao seu lado, até o senhor dele voltar para casa."),
      V(17, "Então repetiu a história: “Aquele servo hebreu que você trouxe veio até mim para zombar de mim."),
      V(18, "Mas, quando gritei, ele deixou a roupa ao meu lado e fugiu.”"),
    ]},
    {"verses": [
      V(19, "Quando o senhor de José ouviu as palavras da mulher — “foi isso que o seu servo fez comigo” —, ficou furioso."),
      V(20, "Mandou prender José na prisão onde ficavam os presos do rei. E José ficou ali, na prisão."),
      V(21, "Mas o Senhor estava com José, mostrou-lhe bondade e fez com que conquistasse a confiança do carcereiro."),
      V(22, "O carcereiro entregou nas mãos de José todos os presos que estavam na prisão, e José administrava tudo o que se fazia ali."),
      V(23, "O carcereiro não se preocupava com nada do que estava sob os cuidados de José, porque o Senhor estava com ele e fazia prosperar tudo o que ele fazia."),
    ]},
  ],
}

CH["40"] = {
  "verses": 23,
  "summary": "Na prisão, José interpreta os sonhos do copeiro e do padeiro do faraó. As interpretações se cumprem, mas o copeiro esquece de falar de José.",
  "sections": [
    {"title": "Os sonhos do copeiro e do padeiro", "start": 1},
    {"title": "As interpretações se cumprem", "start": 20},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Algum tempo depois, o copeiro e o padeiro do rei do Egito ofenderam o seu senhor, o rei do Egito."),
      V(2, "O faraó ficou indignado com os dois oficiais, o chefe dos copeiros e o chefe dos padeiros,"),
      V(3, "e mandou prendê-los na casa do capitão da guarda, na prisão onde José estava."),
      V(4, "O capitão da guarda encarregou José de servi-los. E eles ficaram presos por algum tempo."),
      V(5, "Numa mesma noite, o copeiro e o padeiro do rei do Egito, que estavam na prisão, tiveram cada um o seu sonho, e cada sonho tinha a sua interpretação."),
      V(6, "De manhã, José foi até eles e viu que estavam abatidos."),
      V(7, "Perguntou aos oficiais do faraó, que estavam presos com ele na casa do seu senhor: “Por que hoje os seus rostos estão tão tristes?”"),
      V(8, "Eles responderam: “Tivemos um sonho, e não há quem o interprete.” José disse: “As interpretações pertencem a Deus. Contem-me, por favor.”"),
      V(9, "O chefe dos copeiros contou o seu sonho a José: “No meu sonho, havia uma videira diante de mim,"),
      V(10, "e nela, três ramos. Ela brotou, floresceu e os seus cachos amadureceram."),
      V(11, "Eu tinha na mão a taça do faraó. Peguei as uvas, espremi-as na taça do faraó e entreguei a taça na mão dele.”"),
      V(12, "José disse: “A interpretação é esta: os três ramos são três dias."),
      V(13, "Dentro de três dias, o faraó vai exaltar você e restituí-lo ao seu cargo. Você voltará a entregar a taça na mão do faraó, como antes, quando era o copeiro dele."),
      V(14, "Mas lembre-se de mim quando tudo estiver bem com você: tenha a bondade de falar de mim ao faraó e tire-me desta prisão."),
      V(15, "Pois fui sequestrado da terra dos hebreus e, também aqui, não fiz nada para merecer a prisão.”"),
      V(16, "Quando o chefe dos padeiros viu que a interpretação era boa, disse a José: “Eu também sonhei: havia três cestos de pão branco sobre a minha cabeça."),
      V(17, "No cesto de cima havia todo tipo de pães e doces para o faraó, mas as aves comiam do cesto que estava sobre a minha cabeça.”"),
      V(18, "José respondeu: “A interpretação é esta: os três cestos são três dias."),
      V(19, "Dentro de três dias, o faraó vai levantar a sua cabeça — mas para enforcá-lo —, e as aves comerão a sua carne.”"),
    ]},
    {"verses": [
      V(20, "No terceiro dia, que era aniversário do faraó, ele deu um banquete a todos os seus servos e, diante deles, levantou a cabeça do chefe dos copeiros e a do chefe dos padeiros."),
      V(21, "Restituiu o cargo ao chefe dos copeiros, que voltou a entregar a taça na mão do faraó."),
      V(22, "Mas enforcou o chefe dos padeiros, como José tinha interpretado."),
      V(23, "O chefe dos copeiros, porém, não se lembrou de José; esqueceu-se dele."),
    ]},
  ],
}

CH["41"] = {
  "verses": 57,
  "summary": "O faraó tem dois sonhos que ninguém interpreta. O copeiro se lembra de José, que interpreta os sonhos e propõe um plano contra a fome. O faraó o torna governador do Egito, e José se casa e tem dois filhos.",
  "sections": [
    {"title": "Os sonhos do faraó", "start": 1},
    {"title": "José interpreta os sonhos", "start": 14},
    {"title": "José se torna governador", "start": 37},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Dois anos depois, o faraó teve um sonho: estava em pé junto ao rio Nilo,"),
      V(2, "quando subiram do rio sete vacas bonitas e gordas, que pastavam entre os juncos."),
      V(3, "Depois delas, subiram do rio outras sete vacas feias e magras, que ficaram ao lado das primeiras, na margem do rio."),
      V(4, "As vacas feias e magras devoraram as sete vacas bonitas e gordas. Então o faraó acordou."),
      V(5, "Adormeceu de novo e teve outro sonho: sete espigas cheias e boas cresciam num mesmo talo."),
      V(6, "Depois delas, brotaram sete espigas mirradas e queimadas pelo vento leste."),
      V(7, "As espigas mirradas engoliram as sete espigas cheias e boas. O faraó acordou — era um sonho."),
      V(8, "De manhã, o espírito dele estava perturbado. Mandou chamar todos os magos e sábios do Egito e contou-lhes os sonhos, mas ninguém conseguiu interpretá-los."),
      V(9, "Então o chefe dos copeiros disse ao faraó: “Hoje me lembro do meu erro."),
      V(10, "Certa vez, o faraó ficou indignado com os seus servos e mandou prender-me na casa do capitão da guarda, junto com o chefe dos padeiros."),
      V(11, "Numa mesma noite, nós dois tivemos um sonho, cada um com a sua interpretação."),
      V(12, "Havia lá conosco um jovem hebreu, servo do capitão da guarda. Contamos os sonhos a ele, e ele interpretou cada sonho."),
      V(13, "E aconteceu exatamente como ele interpretou: eu fui restituído ao meu cargo, e o outro foi enforcado.”"),
    ]},
    {"verses": [
      V(14, "O faraó mandou chamar José, que o tiraram depressa da prisão. Ele se barbeou, trocou de roupa e se apresentou ao faraó."),
      V(15, "O faraó disse a José: “Tive um sonho, e não há quem o interprete. Ouvi dizer que, quando você ouve um sonho, consegue interpretá-lo.”"),
      V(16, "José respondeu: “Não sou eu. Deus é quem dará uma resposta favorável ao faraó.”"),
      V(17, "O faraó contou a José: “No meu sonho, eu estava em pé na margem do rio Nilo."),
      V(18, "Subiram do rio sete vacas gordas e bonitas, que pastavam entre os juncos."),
      V(19, "Depois delas, subiram outras sete vacas fracas, muito feias e magras; nunca vi vacas tão feias em toda a terra do Egito."),
      V(20, "As vacas magras e feias devoraram as sete primeiras, as gordas."),
      V(21, "Mas, mesmo depois de devorá-las, ninguém diria que tinham comido, pois continuavam tão feias como antes. Então acordei."),
      V(22, "Depois sonhei que sete espigas cheias e boas cresciam num mesmo talo."),
      V(23, "Depois delas, brotaram sete espigas secas, mirradas e queimadas pelo vento leste."),
      V(24, "As espigas mirradas engoliram as sete espigas boas. Contei isso aos magos, mas ninguém me explicou nada.”"),
      V(25, "José disse ao faraó: “Os dois sonhos do faraó têm o mesmo significado: Deus está mostrando ao faraó o que ele vai fazer."),
      V(26, "As sete vacas boas são sete anos, e as sete espigas boas também são sete anos: é um só sonho."),
      V(27, "As sete vacas magras e feias que subiram depois são sete anos, e as sete espigas vazias e queimadas pelo vento leste serão sete anos de fome."),
      V(28, "É como eu disse ao faraó: Deus mostrou ao faraó o que está para fazer."),
      V(29, "Vêm aí sete anos de grande fartura em toda a terra do Egito."),
      V(30, "Depois virão sete anos de fome, tão terríveis que ninguém se lembrará da fartura no Egito, porque a fome arrasará a terra."),
      V(31, "A fartura será esquecida por causa da fome que virá depois, pois ela será duríssima."),
      V(32, "O sonho foi repetido ao faraó duas vezes porque a coisa já está decidida por Deus, e Deus se apressa em realizá-la."),
      V(33, "Agora, que o faraó escolha um homem sábio e prudente e o coloque sobre a terra do Egito."),
      V(34, "Que o faraó nomeie administradores sobre a terra, para recolher a quinta parte da colheita do Egito durante os sete anos de fartura."),
      V(35, "Que juntem todo o alimento desses anos bons que virão, armazenem o trigo sob a autoridade do faraó e guardem o alimento nas cidades."),
      V(36, "Assim haverá mantimento reservado para a terra, para os sete anos de fome que virão sobre o Egito, e a terra não será arrasada pela fome.”"),
    ]},
    {"verses": [
      V(37, "A proposta agradou ao faraó e a todos os seus servos."),
      V(38, "O faraó disse aos servos: “Encontraremos alguém como este, em quem está o Espírito de Deus?”"),
      V(39, "E disse a José: “Já que Deus lhe mostrou tudo isso, não há ninguém tão sábio e prudente como você."),
      V(40, "Você administrará a minha casa, e todo o meu povo obedecerá às suas ordens. Somente no trono eu serei maior do que você.”"),
      V(41, "O faraó continuou: “Eu o coloco agora sobre toda a terra do Egito.”"),
      V(42, "O faraó tirou o anel de selar da própria mão e o colocou na mão de José, vestiu-o com roupas de linho fino e pôs uma corrente de ouro no pescoço dele."),
      V(43, "Fez José subir na sua segunda carruagem, e gritavam diante dele: “Ajoelhem-se!” Assim o faraó o pôs sobre toda a terra do Egito."),
      V(44, "E o faraó disse a José: “Eu sou o faraó, mas sem a sua ordem ninguém levantará a mão ou o pé em toda a terra do Egito.”"),
      V(45, "O faraó deu a José o nome de Zafenate-Paneia e lhe deu como mulher Azenate, filha de Potífera, sacerdote de Om. José saiu para percorrer a terra do Egito."),
      V(46, "José tinha trinta anos quando se apresentou ao faraó, rei do Egito. Ele saiu da presença do faraó e percorreu todo o Egito."),
      V(47, "Durante os sete anos de fartura, a terra produziu em abundância."),
      V(48, "José juntou todo o alimento dos sete anos de fartura que houve no Egito e armazenou-o nas cidades: em cada cidade guardou o alimento dos campos ao redor."),
      V(49, "José estocou trigo em quantidade imensa, como a areia do mar, até desistir de contar, porque já não se podia contar."),
      V(50, "Antes dos anos de fome, Azenate, filha de Potífera, sacerdote de Om, deu a José dois filhos."),
      V(51, "José chamou o primogênito de Manassés — “fazer esquecer” —, dizendo: “Deus me fez esquecer todo o meu sofrimento e toda a casa do meu pai.”"),
      V(52, "Ao segundo chamou Efraim — “frutificar” —, dizendo: “Deus me fez frutificar na terra da minha aflição.”"),
      V(53, "Os sete anos de fartura que houve no Egito chegaram ao fim,"),
      V(54, "e começaram os sete anos de fome, como José tinha dito. Houve fome em todas as terras, mas em todo o Egito havia pão."),
      V(55, "Quando todo o Egito começou a passar fome, o povo clamou ao faraó por pão. O faraó disse a todos os egípcios: “Vão a José e façam o que ele disser.”"),
      V(56, "A fome se espalhou por toda a terra. José abriu os armazéns e vendeu trigo aos egípcios, porque a fome era severa no Egito."),
      V(57, "E de todas as terras vinham ao Egito comprar trigo de José, porque a fome era severa em todo o mundo."),
    ]},
  ],
}

CH["42"] = {
  "verses": 38,
  "summary": "Os irmãos de José descem ao Egito para comprar trigo e se curvam diante dele sem reconhecê-lo. José os põe à prova, e eles reconhecem a culpa pelo que fizeram ao irmão.",
  "sections": [
    {"title": "A primeira viagem ao Egito", "start": 1},
    {"title": "A culpa vem à tona", "start": 18},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Jacó soube que havia trigo no Egito e disse aos filhos: “Por que vocês estão aí se olhando?"),
      V(2, "Ouvi dizer que há trigo no Egito. Desçam até lá e comprem para nós, para que vivamos e não morramos.”"),
      V(3, "Dez irmãos de José desceram ao Egito para comprar trigo."),
      V(4, "Mas Jacó não deixou Benjamim, irmão de José, ir com eles, pensando: “Não quero que lhe aconteça alguma desgraça.”"),
      V(5, "Os filhos de Israel foram com outros que também iam, porque a fome era severa na terra de Canaã."),
      V(6, "José era o governador da terra e vendia trigo a todo o povo. Os irmãos de José chegaram e se prostraram diante dele, com o rosto em terra."),
      V(7, "José viu os irmãos e os reconheceu, mas agiu como se não os conhecesse. Falou duramente com eles: “De onde vocês vêm?” Eles responderam: “Da terra de Canaã, para comprar mantimento.”"),
      V(8, "José reconheceu os irmãos, mas eles não o reconheceram."),
      V(9, "Então José se lembrou dos sonhos que tinha tido a respeito deles e disse: “Vocês são espiões! Vieram ver os pontos fracos da terra.”"),
      V(10, "Eles responderam: “Não, meu senhor! Os seus servos vieram comprar mantimento."),
      V(11, "Somos todos filhos de um mesmo homem. Somos homens honestos; os seus servos não são espiões.”"),
      V(12, "José insistiu: “Não! Vocês vieram ver os pontos fracos da terra.”"),
      V(13, "Eles disseram: “Nós, os seus servos, éramos doze irmãos, filhos de um mesmo homem, na terra de Canaã. O mais novo está com o nosso pai, e o outro já não existe.”"),
      V(14, "José respondeu: “É como eu disse: vocês são espiões!"),
      V(15, "Vou pô-los à prova: juro pela vida do faraó que vocês não sairão daqui enquanto o seu irmão mais novo não vier."),
      V(16, "Mandem um de vocês buscar o seu irmão; os outros ficarão presos. Assim provarei se vocês falam a verdade. Se não, pela vida do faraó, vocês são espiões.”"),
      V(17, "E os manteve presos durante três dias."),
    ]},
    {"verses": [
      V(18, "No terceiro dia, José disse a eles: “Façam o que eu digo e viverão, pois eu temo a Deus."),
      V(19, "Se vocês são honestos, fique um dos irmãos preso na casa onde vocês estão detidos; os outros voltem levando trigo para matar a fome das suas famílias."),
      V(20, "Depois tragam-me o irmão mais novo, para que as suas palavras se confirmem e vocês não morram.” E eles concordaram."),
      V(21, "Disseram uns aos outros: “É verdade, somos culpados pelo que fizemos ao nosso irmão. Vimos a angústia dele quando nos implorava por misericórdia, e não o ouvimos. Por isso esta angústia veio sobre nós.”"),
      V(22, "Rúben respondeu: “Eu não avisei vocês? Disse: ‘Não pequem contra o menino!’ Mas vocês não ouviram. Agora estamos prestando contas pelo sangue dele.”"),
      V(23, "Eles não sabiam que José entendia, porque havia um intérprete entre eles."),
      V(24, "José se afastou deles e chorou. Depois voltou, falou com eles e, entre eles, mandou prender Simeão diante dos seus olhos."),
      V(25, "José ordenou que enchessem de trigo os sacos deles, que devolvessem a prata de cada um no seu saco e que lhes dessem provisão para o caminho. E assim foi feito."),
      V(26, "Eles carregaram o trigo nos jumentos e partiram."),
      V(27, "Quando um deles abriu o saco para dar forragem ao jumento, no lugar de pouso, viu a prata na boca do saco."),
      V(28, "E disse aos irmãos: “Devolveram a minha prata! Está aqui, no meu saco!” O coração deles desfaleceu, e disseram, tremendo: “O que é isso que Deus fez conosco?”"),
      V(29, "Quando chegaram à casa de Jacó, seu pai, na terra de Canaã, contaram-lhe tudo o que tinha acontecido:"),
      V(30, "“O homem que governa aquela terra falou duramente conosco e nos tratou como espiões da terra."),
      V(31, "Nós respondemos: ‘Somos homens honestos; não somos espiões."),
      V(32, "Éramos doze irmãos, filhos do mesmo pai. Um já não existe, e o mais novo está com o nosso pai, na terra de Canaã.’"),
      V(33, "Então o homem que governa a terra nos disse: ‘Assim saberei que vocês são honestos: deixem comigo um dos irmãos, levem o mantimento para matar a fome das suas famílias e vão embora."),
      V(34, "Tragam-me o seu irmão mais novo. Então saberei que vocês não são espiões, mas homens honestos. Devolverei o irmão de vocês, e vocês poderão negociar na terra.’”"),
      V(35, "Ao esvaziarem os sacos, cada um achou o seu pacote de prata dentro do saco. Quando eles e o pai viram os pacotes de prata, ficaram com medo."),
      V(36, "Jacó, o pai, disse: “Vocês estão me tirando os filhos! José já não existe, Simeão já não existe, e agora querem levar Benjamim! Tudo isso cai sobre mim!”"),
      V(37, "Rúben respondeu ao pai: “Pode matar os meus dois filhos, se eu não trouxer Benjamim de volta. Entregue-o aos meus cuidados, e eu o trarei.”"),
      V(38, "Mas Jacó disse: “O meu filho não irá com vocês. O irmão dele já morreu, e só ele restou. Se lhe acontecer alguma desgraça no caminho, vocês farão os meus cabelos brancos descerem à sepultura em tristeza.”"),
    ]},
  ],
}

CH["43"] = {
  "verses": 34,
  "summary": "Forçados pela fome, os irmãos voltam ao Egito com Benjamim. José os recebe, chora ao ver o irmão e os honra num banquete.",
  "sections": [
    {"title": "A segunda viagem ao Egito", "start": 1},
    {"title": "O banquete na casa de José", "start": 15},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "A fome era severa na terra."),
      V(2, "Quando acabou o trigo que tinham trazido do Egito, o pai disse aos filhos: “Voltem e comprem um pouco de mantimento para nós.”"),
      V(3, "Judá respondeu: “O homem nos avisou com firmeza: ‘Não voltem à minha presença sem o irmão de vocês.’"),
      V(4, "Se o senhor deixar o nosso irmão ir conosco, desceremos e compraremos mantimento para o senhor."),
      V(5, "Mas, se não deixar, não iremos, porque o homem nos disse: ‘Não voltem à minha presença sem o irmão de vocês.’”"),
      V(6, "Israel perguntou: “Por que vocês me fizeram esse mal, contando ao homem que tinham outro irmão?”"),
      V(7, "Eles responderam: “O homem fez perguntas detalhadas sobre nós e a nossa família: ‘O pai de vocês ainda vive? Vocês têm outro irmão?’ Nós apenas respondemos às perguntas dele. Como poderíamos saber que ele diria: ‘Tragam o seu irmão’?”"),
      V(8, "Judá disse a Israel, seu pai: “Deixe o menino ir comigo. Vamos partir para que vivamos — nós, o senhor e as nossas crianças — e não morramos."),
      V(9, "Eu me responsabilizo por ele; o senhor pode me cobrar. Se eu não o trouxer de volta e não o colocar diante do senhor, serei culpado diante do senhor para sempre."),
      V(10, "Se não tivéssemos demorado tanto, já teríamos ido e voltado duas vezes.”"),
      V(11, "Então Israel, o pai deles, disse: “Se tem que ser assim, façam o seguinte: levem nos sacos os melhores produtos desta terra como presente para o homem — um pouco de bálsamo, um pouco de mel, especiarias, mirra, nozes e amêndoas."),
      V(12, "Levem o dobro da prata, pois precisam devolver a prata que foi achada na boca dos sacos; talvez tenha sido um engano."),
      V(13, "Levem o irmão de vocês e voltem àquele homem."),
      V(14, "Que o Deus Todo-Poderoso faça com que o homem tenha compaixão de vocês e deixe voltar o outro irmão e Benjamim. Quanto a mim, se tenho que perder os filhos, que eu os perca.”"),
    ]},
    {"verses": [
      V(15, "Os homens levaram o presente, o dobro da prata e Benjamim, desceram ao Egito e se apresentaram a José."),
      V(16, "Quando José viu Benjamim com eles, disse ao administrador da sua casa: “Leve estes homens para casa, mate um animal e prepare-o, porque eles almoçarão comigo ao meio-dia.”"),
      V(17, "O homem fez como José ordenou e os levou para a casa de José."),
      V(18, "Os irmãos ficaram com medo ao serem levados à casa de José, e pensaram: “É por causa da prata que voltou nos nossos sacos que estamos sendo trazidos aqui: para ele nos atacar, nos dominar e nos escravizar, levando os nossos jumentos.”"),
      V(19, "Por isso, ao chegarem à porta da casa, falaram com o administrador:"),
      V(20, "“Meu senhor, nós realmente descemos antes para comprar mantimento."),
      V(21, "Mas, quando chegamos ao lugar de pouso e abrimos os sacos, cada um achou a sua prata na boca do saco, o valor exato. Por isso a trouxemos de volta."),
      V(22, "Trouxemos também mais prata para comprar mantimento. Não sabemos quem pôs a prata nos nossos sacos.”"),
      V(23, "Ele respondeu: “Fiquem em paz, não tenham medo. O seu Deus, o Deus do seu pai, colocou um tesouro nos sacos de vocês. A prata de vocês chegou até mim.” E trouxe Simeão para junto deles."),
      V(24, "O administrador os levou para dentro da casa de José, deu-lhes água para lavar os pés e forragem para os jumentos."),
      V(25, "Eles prepararam o presente, esperando José chegar ao meio-dia, porque souberam que ali almoçariam."),
      V(26, "Quando José chegou em casa, eles lhe entregaram o presente e se prostraram até o chão diante dele."),
      V(27, "Ele perguntou como estavam e disse: “O pai de vocês, o idoso de quem me falaram, vai bem? Ainda vive?”"),
      V(28, "Eles responderam: “O seu servo, nosso pai, vai bem; ainda vive.” E se prostraram e se curvaram."),
      V(29, "José levantou os olhos e viu Benjamim, seu irmão, filho da sua mãe, e perguntou: “É este o irmão mais novo de quem me falaram?” E disse: “Deus tenha bondade de você, meu filho.”"),
      V(30, "José saiu depressa, porque a emoção ao ver o irmão era grande, e procurou um lugar para chorar. Entrou no seu quarto e chorou ali."),
      V(31, "Depois lavou o rosto e saiu. Contendo-se, disse: “Sirvam a comida.”"),
      V(32, "Serviram a José à parte, e aos irmãos à parte; e à parte também os egípcios que comiam com ele, porque os egípcios não podiam comer com os hebreus: isso era repugnante para eles."),
      V(33, "Os irmãos foram sentados à mesa diante de José, por ordem de idade, do mais velho ao mais novo, e se olhavam espantados."),
      V(34, "As porções eram servidas da mesa de José, e a porção de Benjamim era cinco vezes maior que a dos outros. Eles beberam e se alegraram com ele."),
    ]},
  ],
}

CH["44"] = {
  "verses": 34,
  "summary": "José arma a última prova: manda esconder a sua taça no saco de Benjamim. Judá, em um dos discursos mais bonitos da Bíblia, se oferece como escravo no lugar do irmão.",
  "sections": [
    {"title": "A taça de José", "start": 1},
    {"title": "O apelo de Judá", "start": 14},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "José ordenou ao administrador da sua casa: “Encha os sacos destes homens com todo o mantimento que puderem carregar e ponha a prata de cada um na boca do seu saco."),
      V(2, "E ponha a minha taça, a taça de prata, na boca do saco do mais novo, junto com a prata do trigo dele.” Ele fez como José tinha ordenado."),
      V(3, "Ao amanhecer, os homens partiram com os seus jumentos."),
      V(4, "Mal tinham saído da cidade, e ainda não estavam longe, quando José disse ao administrador: “Vá atrás daqueles homens e, quando os alcançar, diga: ‘Por que retribuíram o bem com o mal?"),
      V(5, "Não é esta a taça em que o meu senhor bebe e com a qual faz adivinhações? Vocês fizeram algo muito errado!’”"),
      V(6, "Ele os alcançou e repetiu essas palavras."),
      V(7, "Eles responderam: “Por que o meu senhor fala assim? Longe dos seus servos fazer tal coisa!"),
      V(8, "A prata que achamos na boca dos sacos trouxemos de volta da terra de Canaã! Como roubaríamos prata ou ouro da casa do seu senhor?"),
      V(9, "Aquele dos seus servos com quem a taça for achada, morra — e nós também seremos escravos do meu senhor.”"),
      V(10, "Ele disse: “Que seja como vocês dizem: aquele com quem a taça for achada será o meu escravo; os outros ficarão livres.”"),
      V(11, "Cada um se apressou em baixar o saco ao chão e abri-lo."),
      V(12, "O administrador os revistou, do mais velho ao mais novo, e a taça foi achada no saco de Benjamim."),
      V(13, "Então rasgaram as roupas, carregaram os jumentos de novo e voltaram à cidade."),
    ]},
    {"verses": [
      V(14, "Judá e os irmãos chegaram à casa de José, que ainda estava lá, e se prostraram até o chão diante dele."),
      V(15, "José perguntou: “O que foi que vocês fizeram? Não sabiam que um homem como eu é capaz de adivinhar?”"),
      V(16, "Judá respondeu: “O que diremos ao meu senhor? O que falaremos? Como nos justificaremos? Deus descobriu a culpa dos seus servos. Aqui estamos: somos escravos do meu senhor, nós e aquele com quem a taça foi achada.”"),
      V(17, "Mas José disse: “Longe de mim fazer isso! Aquele com quem a taça foi achada será o meu escravo. Os outros voltem em paz para o pai de vocês.”"),
      V(18, "Então Judá se aproximou de José e disse: “Por favor, meu senhor, deixe o seu servo dizer uma palavra aos ouvidos do meu senhor, sem que a sua ira se acenda contra mim, pois o senhor é como o próprio faraó."),
      V(19, "O meu senhor perguntou aos seus servos: ‘Vocês têm pai ou irmão?’"),
      V(20, "E respondemos ao meu senhor: ‘Temos um pai idoso, e um filho que nasceu na velhice dele, ainda menino. O irmão dele morreu; ele é o único filho da sua mãe que restou, e o pai o ama muito.’"),
      V(21, "O senhor disse aos seus servos: ‘Tragam-no a mim, para que eu o veja com os meus próprios olhos.’"),
      V(22, "Respondemos ao meu senhor: ‘O menino não pode deixar o pai; se o deixar, o pai morrerá.’"),
      V(23, "Mas o senhor insistiu: ‘Se o irmão mais novo de vocês não descer com vocês, nunca mais verão o meu rosto.’"),
      V(24, "Quando voltamos ao seu servo, meu pai, contamos a ele as palavras do meu senhor."),
      V(25, "O nosso pai disse: ‘Voltem e comprem um pouco de mantimento para nós.’"),
      V(26, "Nós respondemos: ‘Não podemos descer. Só desceremos se o nosso irmão mais novo for conosco, porque não podemos ver o rosto daquele homem sem o nosso irmão mais novo.’"),
      V(27, "O seu servo, meu pai, nos disse: ‘Vocês sabem que a minha mulher me deu dois filhos."),
      V(28, "Um saiu de casa, e eu disse: com certeza foi despedaçado! E nunca mais o vi."),
      V(29, "Se vocês levarem também este e lhe acontecer alguma desgraça, farão os meus cabelos brancos descerem à sepultura em tristeza.’"),
      V(30, "Agora, se eu voltar ao seu servo, meu pai, sem o menino — a vida dele está ligada à vida do menino —,"),
      V(31, "quando ele vir que o menino não está conosco, morrerá. E os seus servos farão os cabelos brancos do seu servo, nosso pai, descerem à sepultura em tristeza."),
      V(32, "O seu servo se responsabilizou pelo menino diante do meu pai, dizendo: ‘Se eu não o trouxer de volta, serei culpado diante do meu pai para sempre.’"),
      V(33, "Por isso, deixe o seu servo ficar como escravo do meu senhor no lugar do menino, e que o menino volte com os seus irmãos."),
      V(34, "Como poderei voltar ao meu pai sem o menino? Não suportaria ver a desgraça que cairia sobre o meu pai!”"),
    ]},
  ],
}

CH["45"] = {
  "verses": 28,
  "summary": "José não consegue mais se conter e se revela aos irmãos: “Fui eu que vocês venderam — mas Deus me enviou adiante para salvar vidas”. O faraó manda buscar Jacó, e os irmãos partem carregados de presentes.",
  "sections": [
    {"title": "José se revela", "start": 1},
    {"title": "O convite do faraó", "start": 16},
    {"title": "A volta dos irmãos", "start": 21},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "José não conseguiu mais se conter diante de todos os que o serviam e gritou: “Saiam todos daqui!” Assim, ninguém estava com ele quando se deu a conhecer aos irmãos."),
      V(2, "E chorou tão alto, que os egípcios ouviram, e a notícia chegou à casa do faraó."),
      V(3, "José disse aos irmãos: “Eu sou José! O meu pai ainda vive?” Os irmãos ficaram tão atônitos diante dele, que não conseguiam responder."),
      V(4, "José disse: “Cheguem mais perto de mim.” Eles se aproximaram, e ele continuou: “Eu sou José, o irmão de vocês, a quem vocês venderam ao Egito."),
      V(5, "Agora, não fiquem aflitos, nem se culpem por terem me vendido para cá, porque foi para salvar vidas que Deus me enviou adiante de vocês."),
      V(6, "A fome já dura dois anos na terra, e ainda haverá cinco anos em que não se poderá arar nem colher."),
      V(7, "Deus me enviou adiante de vocês para preservar a vida de vocês na terra e para salvá-los com um grande livramento."),
      V(8, "Assim, não foram vocês que me mandaram para cá, e sim Deus. Ele me tornou conselheiro do faraó, senhor de toda a sua casa e governador de toda a terra do Egito."),
      V(9, "Voltem depressa ao meu pai e digam: ‘Assim diz o seu filho José: Deus me tornou senhor de todo o Egito. Desça até mim, não demore."),
      V(10, "O senhor morará na terra de Gósen, perto de mim — o senhor, os seus filhos e netos, os seus rebanhos, o seu gado e tudo o que é seu."),
      V(11, "Ali eu sustentarei o senhor — porque ainda haverá cinco anos de fome —, para que o senhor, a sua casa e tudo o que é seu não caiam na miséria.’"),
      V(12, "Vocês estão vendo com os próprios olhos — e o meu irmão Benjamim também — que sou eu mesmo que falo com vocês."),
      V(13, "Contem ao meu pai toda a honra que tenho no Egito e tudo o que viram. E tragam o meu pai para cá depressa.”"),
      V(14, "Então José abraçou Benjamim, seu irmão, e chorou; e Benjamim chorou abraçado a ele."),
      V(15, "José beijou todos os irmãos e chorou sobre eles. Depois disso, os irmãos conversaram com ele."),
    ]},
    {"verses": [
      V(16, "A notícia chegou à casa do faraó: “Os irmãos de José chegaram!” O faraó e os seus servos ficaram contentes."),
      V(17, "O faraó disse a José: “Diga aos seus irmãos: ‘Façam o seguinte: carreguem os animais e voltem para a terra de Canaã."),
      V(18, "Tragam o pai de vocês e as suas famílias e venham para mim. Eu darei a vocês o melhor da terra do Egito, e vocês comerão da fartura da terra.’"),
      V(19, "E dê esta ordem: ‘Façam o seguinte: levem do Egito carroças para as crianças e as mulheres, tragam o pai de vocês e venham."),
      V(20, "Não se preocupem com os seus bens, porque o melhor de toda a terra do Egito será de vocês.’”"),
    ]},
    {"verses": [
      V(21, "Os filhos de Israel fizeram como foi ordenado. José deu a eles carroças, conforme a ordem do faraó, e provisões para o caminho."),
      V(22, "A cada um deu roupas novas; a Benjamim, porém, deu trezentas moedas de prata e cinco mudas de roupa."),
      V(23, "Ao pai enviou dez jumentos carregados com o melhor do Egito e dez jumentas carregadas de trigo, pão e provisões para a viagem."),
      V(24, "Assim despediu os irmãos e, quando partiam, recomendou: “Não briguem pelo caminho.”"),
      V(25, "Eles subiram do Egito e chegaram à terra de Canaã, à casa de Jacó, seu pai."),
      V(26, "E lhe anunciaram: “José ainda está vivo! E é ele o governador de toda a terra do Egito!” Jacó quase desmaiou, porque não acreditava."),
      V(27, "Mas, quando contaram tudo o que José tinha dito, e viu as carroças que José tinha enviado para levá-lo, o espírito de Jacó reviveu."),
      V(28, "Israel disse: “Basta! O meu filho José ainda está vivo! Quero vê-lo antes de morrer.”"),
    ]},
  ],
}

CH["46"] = {
  "verses": 34,
  "summary": "Jacó desce ao Egito com toda a família, e Deus renova a promessa no caminho. José e Jacó se reencontram em Gósen, num abraço cheio de lágrimas.",
  "sections": [
    {"title": "A descida ao Egito", "start": 1},
    {"title": "Os nomes da família de Jacó", "start": 8},
    {"title": "O reencontro de Jacó e José", "start": 28},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Israel partiu com tudo o que tinha. Ao chegar a Berseba, ofereceu sacrifícios ao Deus de Isaque, seu pai."),
      V(2, "De noite, Deus falou a Israel numa visão: “Jacó! Jacó!” Ele respondeu: “Aqui estou.”"),
      V(3, "Deus disse: “Eu sou Deus, o Deus do seu pai. Não tenha medo de descer ao Egito, porque lá farei de você uma grande nação."),
      V(4, "Eu mesmo descerei com você ao Egito e certamente o trarei de volta. E a mão de José fechará os seus olhos.”"),
      V(5, "Jacó saiu de Berseba. Os filhos de Israel levaram o pai, as crianças e as mulheres nas carroças que o faraó tinha enviado."),
      V(6, "Levaram também os rebanhos e os bens que tinham acumulado na terra de Canaã. E Jacó foi ao Egito com toda a sua descendência:"),
      V(7, "filhos e netos, filhas e netas — toda a sua descendência ele levou consigo ao Egito."),
    ]},
    {"verses": [
      V(8, "Estes são os nomes dos israelitas, filhos de Jacó, que foram ao Egito: Rúben, o primogênito de Jacó."),
      V(9, "Os filhos de Rúben: Enoque, Palu, Hezrom e Carmi."),
      V(10, "Os filhos de Simeão: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma cananeia."),
      V(11, "Os filhos de Levi: Gérson, Coate e Merari."),
      V(12, "Os filhos de Judá: Er, Onã, Selá, Perez e Zerá — Er e Onã morreram na terra de Canaã. Os filhos de Perez: Hezrom e Hamul."),
      V(13, "Os filhos de Issacar: Tola, Puva, Jó e Sinrom."),
      V(14, "Os filhos de Zebulom: Serede, Elom e Jaleel."),
      V(15, "Esses foram os filhos que Lia deu a Jacó em Padã-Arã, além de Diná, a filha dele. Ao todo, filhos e filhas eram trinta e três pessoas."),
      V(16, "Os filhos de Gade: Zifiom, Hagi, Suni, Esbom, Eri, Arodi e Areli."),
      V(17, "Os filhos de Aser: Imna, Isvá, Isvi, Berias e Sera, irmã deles. Os filhos de Berias: Héber e Malquiel."),
      V(18, "Esses foram os filhos que Zilpa, a serva que Labão deu a Lia, sua filha, deu a Jacó: dezesseis pessoas."),
      V(19, "Os filhos de Raquel, mulher de Jacó: José e Benjamim."),
      V(20, "No Egito, Azenate, filha de Potífera, sacerdote de Om, deu a José Manassés e Efraim."),
      V(21, "Os filhos de Benjamim: Belá, Béquer, Asbel, Gera, Naamã, Eí, Rôs, Mupim, Hupim e Arde."),
      V(22, "Esses foram os filhos que Raquel deu a Jacó: catorze pessoas."),
      V(23, "O filho de Dã: Husim."),
      V(24, "Os filhos de Naftali: Jazeel, Guni, Jezer e Silém."),
      V(25, "Esses foram os filhos que Bila, a serva que Labão deu a Raquel, sua filha, deu a Jacó: sete pessoas."),
      V(26, "Todos os que foram ao Egito com Jacó, descendentes diretos dele, sem contar as mulheres dos seus filhos, eram sessenta e seis pessoas."),
      V(27, "Com os dois filhos que nasceram a José no Egito, a família de Jacó que foi ao Egito somava setenta pessoas."),
    ]},
    {"verses": [
      V(28, "Jacó enviou Judá na frente, a José, para preparar o caminho até Gósen. E chegaram à terra de Gósen."),
      V(29, "José mandou aprontar a sua carruagem e subiu a Gósen ao encontro de Israel, seu pai. Quando o viu, abraçou-o e chorou longamente sobre o seu ombro."),
      V(30, "Israel disse a José: “Agora posso morrer, pois já vi o seu rosto e sei que você ainda está vivo.”"),
      V(31, "José disse aos irmãos e à família do pai: “Vou subir e anunciar ao faraó: ‘Os meus irmãos e a família do meu pai, que estavam na terra de Canaã, vieram para mim."),
      V(32, "Eles são pastores e cuidam de rebanhos; trouxeram as ovelhas, o gado e tudo o que têm.’"),
      V(33, "Quando o faraó chamar vocês e perguntar: ‘Qual é a ocupação de vocês?’,"),
      V(34, "respondam: ‘Os seus servos cuidam de rebanhos desde a juventude, como os nossos antepassados.’ Assim vocês poderão morar na terra de Gósen, porque os egípcios detestam pastores de ovelhas.”"),
    ]},
  ],
}

CH["47"] = {
  "verses": 31,
  "summary": "Jacó abençoa o faraó e a família se estabelece em Gósen. Durante a fome, José administra o Egito com sabedoria, e o povo sobrevive. Jacó faz José jurar que o sepultará em Canaã.",
  "sections": [
    {"title": "Jacó diante do faraó", "start": 1},
    {"title": "A administração da fome", "start": 13},
    {"title": "O juramento de José", "start": 27},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "José foi anunciar ao faraó: “O meu pai e os meus irmãos chegaram da terra de Canaã com as ovelhas, o gado e tudo o que possuem. Estão na terra de Gósen.”"),
      V(2, "E levou consigo cinco dos seus irmãos e os apresentou ao faraó."),
      V(3, "O faraó perguntou aos irmãos: “Qual é a ocupação de vocês?” Eles responderam: “Os seus servos são pastores de rebanhos, como os nossos antepassados.”"),
      V(4, "Disseram ainda ao faraó: “Viemos morar nesta terra porque não há pasto para os rebanhos dos seus servos, pois a fome é severa na terra de Canaã. Permita que os seus servos morem na terra de Gósen.”"),
      V(5, "O faraó disse a José: “O seu pai e os seus irmãos vieram para você."),
      V(6, "A terra do Egito está diante de você: faça o seu pai e os seus irmãos morarem no melhor da terra. Que morem na terra de Gósen. E, se você conhece entre eles homens capazes, coloque-os como responsáveis pelos meus rebanhos.”"),
      V(7, "José trouxe Jacó, seu pai, e o apresentou ao faraó, e Jacó abençoou o faraó."),
      V(8, "O faraó perguntou a Jacó: “Quantos anos o senhor tem?”"),
      V(9, "Jacó respondeu: “Os anos da minha peregrinação são cento e trinta. Poucos e difíceis foram os anos da minha vida, e não chegam aos anos que os meus antepassados viveram nas suas peregrinações.”"),
      V(10, "Jacó abençoou o faraó e saiu da presença dele."),
      V(11, "José estabeleceu o pai e os irmãos e deu a eles propriedades na melhor parte da terra do Egito, na região de Ramessés, como o faraó tinha ordenado."),
      V(12, "E sustentou o pai, os irmãos e toda a família do pai, conforme o número de crianças."),
    ]},
    {"verses": [
      V(13, "Não havia pão em nenhuma terra, porque a fome era severa demais. A terra do Egito e a terra de Canaã desfaleciam por causa da fome."),
      V(14, "José recolheu toda a prata que havia na terra do Egito e em Canaã, em troca do trigo que compravam, e levou a prata para a casa do faraó."),
      V(15, "Quando acabou a prata no Egito e em Canaã, todos os egípcios foram a José e disseram: “Dê-nos pão! Por que morreríamos diante dos seus olhos? A prata acabou.”"),
      V(16, "José respondeu: “Tragam os seus rebanhos, e eu darei pão a vocês em troca deles, já que a prata acabou.”"),
      V(17, "Eles trouxeram os rebanhos a José, que deu pão a eles em troca dos cavalos, das ovelhas, do gado e dos jumentos. Naquele ano, ele os sustentou com pão em troca de todos os rebanhos."),
      V(18, "No ano seguinte, voltaram e disseram: “Não podemos esconder do meu senhor que a prata acabou e os rebanhos são do meu senhor. Nada mais nos resta para dar ao meu senhor, a não ser os nossos corpos e as nossas terras."),
      V(19, "Por que morreríamos diante dos seus olhos, nós e as nossas terras? Compre-nos, com as nossas terras, em troca de pão, e seremos escravos do faraó, nós e as nossas terras. Dê-nos semente, para que vivamos e não morramos, e a terra não fique deserta.”"),
      V(20, "Assim José comprou toda a terra do Egito para o faraó, porque todos os egípcios venderam os seus campos, tamanha era a fome. A terra passou a ser do faraó."),
      V(21, "E quanto ao povo, José o reduziu à servidão, de uma ponta a outra do Egito."),
      V(22, "Somente as terras dos sacerdotes ele não comprou, porque os sacerdotes recebiam uma provisão do faraó e viviam dela; por isso não precisaram vender as suas terras."),
      V(23, "José disse ao povo: “Hoje comprei vocês e as suas terras para o faraó. Aqui está a semente: semeiem a terra."),
      V(24, "Na colheita, darão a quinta parte ao faraó; as outras quatro partes serão de vocês, para semear o campo, para o sustento de vocês, das suas casas e das suas crianças.”"),
      V(25, "Eles responderam: “O senhor salvou a nossa vida! Que encontremos favor aos olhos do meu senhor, e seremos escravos do faraó.”"),
      V(26, "José fez disso uma lei, que vale até hoje sobre a terra do Egito: a quinta parte pertence ao faraó. Somente as terras dos sacerdotes não ficaram com o faraó."),
    ]},
    {"verses": [
      V(27, "Israel morou na terra do Egito, na região de Gósen. Ali adquiriram propriedades, foram férteis e se multiplicaram muito."),
      V(28, "Jacó viveu dezessete anos no Egito, e os anos da sua vida chegaram a cento e quarenta e sete."),
      V(29, "Quando se aproximou o dia da morte de Israel, ele chamou José, seu filho, e disse: “Se encontrei favor aos seus olhos, ponha a mão debaixo da minha coxa e jure que me tratará com bondade e fidelidade: não me sepulte no Egito."),
      V(30, "Quando eu descansar com os meus antepassados, leve-me do Egito e sepulte-me na sepultura deles.” José respondeu: “Farei como o senhor diz.”"),
      V(31, "Jacó insistiu: “Jure.” José jurou. E Israel se curvou sobre a cabeceira da cama."),
    ]},
  ],
}

CH["48"] = {
  "verses": 22,
  "summary": "Jacó adota Efraim e Manassés como filhos e, cruzando os braços, abençoa o mais novo acima do mais velho — mostrando que Deus escreve histórias do seu jeito.",
  "sections": [
    {"title": "A bênção de Efraim e Manassés", "start": 1},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Algum tempo depois, disseram a José: “O seu pai está doente.” Ele levou consigo os dois filhos, Manassés e Efraim."),
      V(2, "Avisaram a Jacó: “O seu filho José veio vê-lo.” Israel fez um esforço e se sentou na cama."),
      V(3, "Jacó disse a José: “O Deus Todo-Poderoso apareceu a mim em Luz, na terra de Canaã, e me abençoou,"),
      V(4, "dizendo: ‘Eu o tornarei fértil, multiplicarei a sua descendência e farei de você uma comunidade de povos; e darei esta terra à sua descendência, como propriedade eterna.’"),
      V(5, "Agora, os dois filhos que nasceram a você no Egito, antes de eu vir para cá, são meus: Efraim e Manassés serão meus, como Rúben e Simeão."),
      V(6, "Os filhos que você tiver depois deles serão seus; serão chamados pelo nome dos irmãos na herança deles."),
      V(7, "Quando eu voltava de Padã-Arã, Raquel morreu no meu colo, na terra de Canaã, no caminho, a pouca distância de Efrata. Eu a sepultei ali, no caminho de Efrata, que é Belém.”"),
      V(8, "Israel viu os filhos de José e perguntou: “Quem são estes?”"),
      V(9, "José respondeu: “São os filhos que Deus me deu aqui.” Israel disse: “Traga-os perto de mim, para que eu os abençoe.”"),
      V(10, "Os olhos de Israel já estavam fracos por causa da idade, e ele mal enxergava. José aproximou os filhos, e o pai os beijou e abraçou."),
      V(11, "Israel disse a José: “Eu não esperava mais ver o seu rosto — e agora Deus me deixou ver até os seus filhos!”"),
      V(12, "José os tirou dos joelhos do pai e se prostrou com o rosto em terra."),
      V(13, "Depois pegou os dois: Efraim com a mão direita, à esquerda de Israel, e Manassés com a mão esquerda, à direita de Israel, e os aproximou dele."),
      V(14, "Mas Israel estendeu a mão direita e a pôs sobre a cabeça de Efraim, que era o mais novo, e a mão esquerda sobre a cabeça de Manassés, cruzando os braços — mesmo sendo Manassés o primogênito."),
      V(15, "E abençoou José, dizendo: “O Deus diante de quem andaram os meus pais Abraão e Isaque, o Deus que tem sido o meu pastor desde que nasci até hoje,"),
      V(16, "o Anjo que me livrou de todo mal, abençoe estes meninos. Que por meio deles o meu nome e os nomes dos meus pais Abraão e Isaque sejam lembrados, e que se multipliquem abundantemente sobre a terra.”"),
      V(17, "José viu que o pai tinha posto a mão direita sobre a cabeça de Efraim e não gostou. Segurou a mão do pai para tirá-la da cabeça de Efraim e passá-la para a cabeça de Manassés,"),
      V(18, "dizendo: “Assim não, meu pai: o primogênito é este. Ponha a mão direita sobre a cabeça dele.”"),
      V(19, "Mas o pai recusou: “Eu sei, meu filho, eu sei. Ele também se tornará um povo e também será grande. Mas o irmão mais novo será maior que ele, e a sua descendência se tornará uma multidão de nações.”"),
      V(20, "Assim os abençoou naquele dia, dizendo: “Por vocês, Israel abençoará, dizendo: ‘Que Deus faça de você como Efraim e Manassés.’” E colocou Efraim antes de Manassés."),
      V(21, "Depois Israel disse a José: “Eu vou morrer, mas Deus estará com vocês e os fará voltar à terra dos seus pais."),
      V(22, "E a você, acima dos seus irmãos, dou a encosta de Siquém, que conquistei dos amorreus com a minha espada e o meu arco.”"),
    ]},
  ],
}

CH["49"] = {
  "verses": 33,
  "summary": "Jacó abençoa cada um dos doze filhos com palavras proféticas. Depois ordena que o sepultem em Macpela e morre, reunindo-se ao seu povo.",
  "sections": [
    {"title": "As bênçãos de Jacó", "start": 1},
    {"title": "A morte de Jacó", "start": 28},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Jacó chamou os filhos e disse: “Reúnam-se, e eu anunciarei o que vai acontecer com vocês nos dias que virão."),
      V(2, "Juntem-se e ouçam, filhos de Jacó; ouçam Israel, o pai de vocês."),
    ]},
    {"verses": [
      V(3, "Rúben, você é o meu primogênito, a minha força e o primeiro fruto do meu vigor, o mais destacado em dignidade e em poder."),
      V(4, "Mas é instável como a água, e não terá mais a primazia, porque subiu à cama do seu pai e a desonrou."),
    ]},
    {"verses": [
      V(5, "Simeão e Levi são irmãos; as suas espadas são instrumentos de violência."),
      V(6, "Que eu não participe dos planos deles, que a minha honra não se junte à assembleia deles! No seu furor mataram homens e, por capricho, aleijaram bois."),
      V(7, "Maldito seja o seu furor, pois foi violento; e a sua ira, pois foi cruel. Eu os dividirei em Jacó e os espalharei em Israel."),
    ]},
    {"verses": [
      V(8, "Judá, os seus irmãos o louvarão; a sua mão estará sobre o pescoço dos seus inimigos; os filhos do seu pai se curvarão diante de você."),
      V(9, "Judá é um leão novo. Você subiu da caça, meu filho. Ele se agacha e se deita como um leão, como uma leoa — quem se atreverá a acordá-lo?"),
      V(10, "O cetro não se afastará de Judá, nem o bastão de comando dos seus pés, até que venha aquele a quem pertence, e a ele os povos obedecerão."),
      V(11, "Ele amarrará o seu jumentinho à videira e o filho da sua jumenta à videira escolhida; lavará as suas roupas no vinho e a sua capa no sangue das uvas."),
      V(12, "Os seus olhos serão mais escuros que o vinho, e os seus dentes mais brancos que o leite."),
    ]},
    {"verses": [
      V(13, "Zebulom morará à beira-mar, junto ao porto dos navios; a sua fronteira se estenderá até Sidom."),
      V(14, "Issacar é um jumento forte, deitado entre duas cargas."),
      V(15, "Viu que o descanso era bom e que a terra era agradável; inclinou os ombros para a carga e se tornou escravo do trabalho forçado."),
      V(16, "Dã julgará o seu povo, como uma das tribos de Israel."),
      V(17, "Dã será como serpente no caminho, como víbora na trilha, que morde o calcanhar do cavalo e derruba o cavaleiro."),
      V(18, "A tua salvação eu espero, Senhor!"),
      V(19, "Gade será atacado por bandos, mas ele os atacará pelos calcanhares."),
      V(20, "A mesa de Aser será farta; ele produzirá manjares dignos de reis."),
      V(21, "Naftali é uma gazela solta, que dá palavras bonitas."),
    ]},
    {"verses": [
      V(22, "José é um ramo frutífero, um ramo frutífero junto à fonte, cujos galhos passam por cima do muro."),
      V(23, "Os flecheiros o atacaram com violência, atiraram contra ele e o perseguiram,"),
      V(24, "mas o seu arco permaneceu firme, e os seus braços se mantiveram ágeis, pelas mãos do Poderoso de Jacó, pelo nome do Pastor, a Rocha de Israel,"),
      V(25, "pelo Deus do seu pai, que o ajudará, pelo Todo-Poderoso, que o abençoará com bênçãos do céu lá em cima, bênçãos do abismo que está lá embaixo, bênçãos dos seios e do ventre."),
      V(26, "As bênçãos do seu pai são maiores que as bênçãos dos montes antigos, que as riquezas das colinas eternas. Que elas venham sobre a cabeça de José, sobre a fronte do príncipe entre os seus irmãos."),
    ]},
    {"verses": [
      V(27, "Benjamim é um lobo que despedaça: de manhã devora a presa e à tarde reparte o despojo."),
    ]},
    {"verses": [
      V(28, "Essas são as doze tribos de Israel, e foi isso que o pai lhes disse ao abençoá-las, dando a cada uma a sua bênção."),
      V(29, "Depois ordenou a eles: “Eu vou me reunir ao meu povo. Sepultem-me com os meus pais, na caverna que fica no campo de Efrom, o heteu,"),
      V(30, "na caverna do campo de Macpela, a leste de Manre, na terra de Canaã, o campo que Abraão comprou de Efrom, o heteu, como propriedade para sepultura."),
      V(31, "Ali sepultaram Abraão e Sara, sua mulher; ali sepultaram Isaque e Rebeca, sua mulher; e ali sepultei Lia."),
      V(32, "O campo e a caverna que nele está foram comprados dos heteus.”"),
      V(33, "Quando Jacó terminou de dar essas ordens aos filhos, recolheu os pés na cama, expirou e foi reunido ao seu povo."),
    ]},
  ],
}

CH["50"] = {
  "verses": 26,
  "summary": "Jacó é sepultado em Canaã, com grande honra. José tranquiliza os irmãos, perdoando-os de todo o coração: “Vocês planejaram o mal, mas Deus o transformou em bem”. Antes de morrer, José pede que levem os seus ossos para a terra prometida.",
  "sections": [
    {"title": "O sepultamento de Jacó", "start": 1},
    {"title": "O perdão de José", "start": 15},
    {"title": "A morte de José", "start": 22},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "José se lançou sobre o rosto do pai, chorou sobre ele e o beijou."),
      V(2, "Depois ordenou aos médicos que estavam ao seu serviço que embalsamassem Israel, seu pai. E os médicos o embalsamaram."),
      V(3, "Levaram quarenta dias, pois esse é o tempo do embalsamamento. E os egípcios choraram por ele durante setenta dias."),
      V(4, "Passados os dias de luto, José falou à casa do faraó: “Se encontrei favor aos olhos de vocês, digam ao faraó:"),
      V(5, "‘O meu pai me fez jurar: “Estou morrendo. Sepulte-me na sepultura que preparei para mim na terra de Canaã.” Deixe-me subir e sepultar o meu pai; depois voltarei.’”"),
      V(6, "O faraó respondeu: “Suba e sepulte o seu pai, como ele fez você jurar.”"),
      V(7, "José subiu para sepultar o pai. Com ele subiram todos os servos do faraó, as autoridades da sua casa e todas as autoridades do Egito,"),
      V(8, "além de toda a família de José, dos seus irmãos e da família do pai. Somente as crianças, as ovelhas e o gado ficaram na terra de Gósen."),
      V(9, "Subiram com ele carruagens e cavaleiros: uma comitiva muito grande."),
      V(10, "Chegaram à eira de Atade, do outro lado do Jordão, e ali fizeram um luto muito grande e solene. José fez um luto de sete dias pelo pai."),
      V(11, "Os cananeus que moravam naquela terra viram o luto na eira de Atade e disseram: “É um luto muito solene dos egípcios.” Por isso o lugar, que fica do outro lado do Jordão, foi chamado de Abel-Mizraim — “luto dos egípcios”."),
      V(12, "Os filhos de Jacó fizeram com ele exatamente o que ele tinha ordenado:"),
      V(13, "levaram-no à terra de Canaã e o sepultaram na caverna do campo de Macpela, perto de Manre, o campo que Abraão tinha comprado de Efrom, o heteu, como propriedade para sepultura."),
      V(14, "Depois do sepultamento do pai, José voltou ao Egito com os irmãos e todos os que tinham subido com ele."),
    ]},
    {"verses": [
      V(15, "Vendo que o pai tinha morrido, os irmãos de José disseram: “Talvez José nos odeie e queira retribuir todo o mal que fizemos a ele.”"),
      V(16, "Então mandaram dizer a José: “O seu pai, antes de morrer, deixou esta ordem:"),
      V(17, "‘Digam a José: perdoe, por favor, a transgressão dos seus irmãos e o pecado deles, pois eles fizeram mal a você.’ Agora, perdoe a transgressão dos servos do Deus do seu pai.” José chorou ao ouvir essas palavras."),
      V(18, "Os irmãos vieram, prostraram-se diante dele e disseram: “Aqui estamos: somos seus servos.”"),
      V(19, "José respondeu: “Não tenham medo. Por acaso eu estou no lugar de Deus?"),
      V(20, "Vocês planejaram o mal contra mim, mas Deus transformou aquilo em bem, para realizar o que hoje vemos: salvar a vida de muita gente."),
      V(21, "Portanto, não tenham medo. Eu sustentarei vocês e as crianças de vocês.” Assim ele os consolou e falou com carinho ao coração deles."),
    ]},
    {"verses": [
      V(22, "José e a família do pai ficaram morando no Egito. José viveu cento e dez anos."),
      V(23, "Viu os filhos de Efraim até a terceira geração; e também os filhos de Maquir, filho de Manassés, nasceram e foram colocados sobre os joelhos de José."),
      V(24, "José disse aos irmãos: “Eu vou morrer. Mas Deus certamente visitará vocês e os fará subir desta terra para a terra que jurou dar a Abraão, Isaque e Jacó.”"),
      V(25, "E José fez os filhos de Israel jurar: “Quando Deus visitar vocês, levem os meus ossos daqui.”"),
      V(26, "José morreu aos cento e dez anos. Foi embalsamado e colocado num sarcófago, no Egito."),
    ]},
  ],
}

out = os.path.join(os.path.dirname(__file__), "..", "data", "books", "gn", "37-50.json")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    json.dump({"book": "gn", "chapters": CH}, f, ensure_ascii=False, indent=2)

total = sum(ch["verses"] for ch in CH.values())
print(f"Parte 3 OK: capítulos 37-50, {total} versículos -> {out}")
