# -*- coding: utf-8 -*-
# Gera data/books/gn/18-36.json — Gênesis, capítulos 18 a 36
# Adaptação em português moderno, fiel aos escritos originais,
# elaborada a partir de traduções de domínio público (Almeida 1911 / Tradução Brasileira 1917).
import json, os

def V(v, text):
    return {"v": v, "text": text}

CH = {}

CH["18"] = {
  "verses": 33,
  "summary": "Três visitantes anunciam que Sara terá um filho. Depois, Deus revela a Abraão o juízo sobre Sodoma e Gomorra — e Abraão intercede, negociando pela cidade com ousadia e humildade.",
  "sections": [
    {"title": "Os três visitantes", "start": 1},
    {"title": "A promessa de um filho", "start": 9},
    {"title": "Abraão intercede por Sodoma", "start": 16},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "O Senhor apareceu a Abraão junto aos carvalhos de Manre, enquanto ele estava sentado à entrada da tenda, no calor do dia."),
      V(2, "Abraão levantou os olhos e viu três homens em pé, perto dele. Quando os viu, saiu correndo da entrada da tenda ao encontro deles, prostrou-se até o chão"),
      V(3, "e disse: “Senhor, se encontrei favor aos teus olhos, não passes sem parar com o teu servo."),
      V(4, "Deixa trazer um pouco de água para lavar os pés de vocês e descansar debaixo desta árvore."),
      V(5, "Vou buscar um pedaço de pão, para refazerem as forças; depois poderão seguir o caminho, pois foi para isso que passaram perto do seu servo.” Eles responderam: “Faça como você disse.”"),
      V(6, "Abraão foi depressa à tenda de Sara e disse: “Depressa! Pegue três medidas da melhor farinha, amasse e faça pães.”"),
      V(7, "Depois correu ao rebanho, escolheu um bezerro bom e macio e o entregou ao servo, que se apressou em prepará-lo."),
      V(8, "Então trouxe coalhada, leite e o bezerro que tinha preparado e os serviu. Enquanto comiam, Abraão ficou em pé, junto deles, debaixo da árvore."),
    ]},
    {"verses": [
      V(9, "Eles perguntaram a Abraão: “Onde está Sara, a sua mulher?” Ele respondeu: “Está na tenda.”"),
      V(10, "Então o Senhor disse: “Voltarei a você no ano que vem, neste mesmo tempo, e Sara, a sua mulher, terá um filho.” Sara estava ouvindo, na entrada da tenda, atrás dele."),
      V(11, "Abraão e Sara já eram velhos, de idade avançada, e Sara já tinha passado da idade de ter filhos."),
      V(12, "Por isso Sara riu por dentro e pensou: “Depois de envelhecida, terei esse prazer? E o meu senhor também já está velho.”"),
      V(13, "O Senhor perguntou a Abraão: “Por que Sara riu e disse: ‘Será que vou mesmo dar à luz, agora que estou velha?’"),
      V(14, "Existe algo impossível demais para o Senhor? No tempo marcado, no ano que vem, voltarei a você — e Sara terá um filho.”"),
      V(15, "Sara, com medo, negou: “Eu não ri.” Mas ele disse: “Não foi isso; você riu.”"),
    ]},
    {"verses": [
      V(16, "Os homens se levantaram dali e olharam na direção de Sodoma. Abraão foi com eles, para se despedir."),
      V(17, "O Senhor disse: “Esconderei de Abraão o que estou para fazer?"),
      V(18, "Abraão certamente se tornará uma nação grande e poderosa, e por meio dele todas as nações da terra serão abençoadas."),
      V(19, "Pois eu o escolhi para que ordene aos seus filhos e à sua casa depois dele que guardem o caminho do Senhor, praticando o que é justo e direito, para que o Senhor cumpra em Abraão tudo o que prometeu.”"),
      V(20, "Então o Senhor disse: “O clamor contra Sodoma e Gomorra é grande, e o pecado deles é muito grave."),
      V(21, "Descerei para ver se o que têm feito corresponde ao clamor que chegou até mim; e, se não, eu saberei.”"),
    ]},
    {"verses": [
      V(22, "Os homens partiram dali e foram para Sodoma, mas Abraão permaneceu diante do Senhor."),
      V(23, "Abraão se aproximou e perguntou: “Destruirás o justo junto com o ímpio?"),
      V(24, "E se houver cinquenta justos na cidade? Destruirás o lugar e não o pouparás por causa dos cinquenta justos que nele vivem?"),
      V(25, "Longe de ti fazer tal coisa: matar o justo junto com o ímpio, tratando os dois da mesma forma! Longe de ti! Não fará justiça o Juiz de toda a terra?”"),
      V(26, "O Senhor respondeu: “Se eu encontrar cinquenta justos em Sodoma, pouparei a cidade inteira por causa deles.”"),
      V(27, "Abraão insistiu: “Agora que me atrevi a falar com o Senhor, eu que sou pó e cinza,"),
      V(28, "e se faltarem cinco para cinquenta justos? Destruirás a cidade por causa de cinco?” Ele respondeu: “Não a destruirei se encontrar ali quarenta e cinco.”"),
      V(29, "Abraão falou de novo: “E se houver apenas quarenta?” Ele respondeu: “Por causa dos quarenta, não o farei.”"),
      V(30, "Abraão continuou: “Não fique irado, Senhor, se eu falar mais uma vez: e se houver trinta?” Ele respondeu: “Não o farei se encontrar trinta.”"),
      V(31, "Abraão disse ainda: “Atrevi-me a falar com o Senhor: e se houver vinte?” Ele respondeu: “Por causa dos vinte, não a destruirei.”"),
      V(32, "Abraão disse: “Não fique irado, Senhor, e deixe-me falar só mais esta vez: e se houver dez?” Ele respondeu: “Por causa dos dez, não a destruirei.”"),
      V(33, "Quando o Senhor terminou de falar com Abraão, partiu. E Abraão voltou para casa."),
    ]},
  ],
}

CH["19"] = {
  "verses": 38,
  "summary": "Os anjos resgatam Ló de Sodoma, que é destruída com fogo e enxofre. A mulher de Ló olha para trás e vira estátua de sal. Ló se refugia numa caverna com as filhas.",
  "sections": [
    {"title": "Ló recebe os anjos em Sodoma", "start": 1},
    {"title": "A fuga e a destruição", "start": 12},
    {"title": "Ló e as filhas", "start": 30},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Os dois anjos chegaram a Sodoma ao entardecer, e Ló estava sentado à porta da cidade. Quando os viu, levantou-se para recebê-los, prostrou-se com o rosto em terra"),
      V(2, "e disse: “Meus senhores, por favor, venham à casa do seu servo: passem a noite, lavem os pés e, de manhã cedo, sigam o caminho.” Eles responderam: “Não; passaremos a noite na praça.”"),
      V(3, "Mas Ló insistiu tanto que eles foram com ele e entraram em sua casa. Ló preparou um banquete, assou pães sem fermento, e eles comeram."),
      V(4, "Antes de se deitarem, os homens da cidade, de todos os cantos de Sodoma, desde os jovens até os velhos, cercaram a casa."),
      V(5, "Chamaram Ló e perguntaram: “Onde estão os homens que entraram na sua casa esta noite? Traga-os aqui, pois queremos ter relações com eles.”"),
      V(6, "Ló saiu para a porta, fechou-a atrás de si"),
      V(7, "e disse: “Meus irmãos, por favor, não façam essa maldade!"),
      V(8, "Ouçam: tenho duas filhas que ainda são virgens. Vou trazê-las para vocês, e façam com elas o que quiserem. Mas não façam nada a estes homens, pois estão debaixo da proteção do meu teto.”"),
      V(9, "Eles, porém, gritaram: “Saia da frente! Esse aí veio morar entre nós como estrangeiro e ainda quer ser juiz? Agora faremos pior com você do que com eles!” Empurraram Ló com violência e tentaram arrombar a porta."),
      V(10, "Mas os homens estenderam as mãos, puxaram Ló para dentro de casa e fecharam a porta."),
      V(11, "E feriram de cegueira os que estavam do lado de fora, desde o menor até o maior, de modo que desistiram de achar a porta."),
    ]},
    {"verses": [
      V(12, "Então os homens perguntaram a Ló: “Quem mais você tem aqui? Genros, filhos, filhas — tire todos desta cidade,"),
      V(13, "porque vamos destruí-la. O clamor contra este povo se tornou tão grande diante do Senhor, que ele nos enviou para destruí-la.”"),
      V(14, "Ló saiu e falou com os genros, os noivos de suas filhas: “Levantem-se! Saiam deste lugar, porque o Senhor vai destruir a cidade!” Mas os genros acharam que ele estava brincando."),
      V(15, "Ao amanhecer, os anjos apressaram Ló: “Levante-se! Tome a sua mulher e as suas duas filhas, para que vocês não sejam destruídos no castigo da cidade.”"),
      V(16, "Como Ló demorava, os homens o pegaram pela mão — a ele, à mulher e às duas filhas —, porque o Senhor teve misericórdia dele, e os tiraram da cidade."),
      V(17, "Assim que os levaram para fora, um deles disse: “Fujam para salvar a vida! Não olhem para trás e não parem em nenhum lugar da campina. Fujam para os montes, para não serem destruídos!”"),
      V(18, "Ló respondeu: “Não, Senhor!"),
      V(19, "O teu servo encontrou favor aos teus olhos, e a tua bondade foi grande comigo, salvando a minha vida. Mas eu não consigo fugir para os montes; essa desgraça me alcançaria, e eu morreria."),
      V(20, "Olha, aquela cidade está perto o bastante para eu fugir, e é pequena. Deixa-me ir para lá — não é pequena? — e a minha vida será poupada.”"),
      V(21, "Ele respondeu: “Está bem. Também nisso vou atender você: não destruirei a cidade de que você fala."),
      V(22, "Depressa, fuja para lá, porque não posso fazer nada enquanto você não chegar lá.” Por isso a cidade foi chamada de Zoar — “pequena”."),
      V(23, "O sol já tinha nascido quando Ló entrou em Zoar."),
      V(24, "Então o Senhor fez chover sobre Sodoma e Gomorra enxofre e fogo, vindos do céu, da parte do Senhor."),
      V(25, "Ele destruiu aquelas cidades e toda a campina, todos os moradores das cidades e toda a vegetação da terra."),
      V(26, "Mas a mulher de Ló olhou para trás e se transformou numa estátua de sal."),
      V(27, "Abraão se levantou de manhã cedo e foi ao lugar onde tinha estado diante do Senhor."),
      V(28, "Olhou na direção de Sodoma e Gomorra, para toda a região da campina, e viu a fumaça subindo da terra, como a fumaça de uma fornalha."),
      V(29, "Quando Deus destruiu as cidades da campina, lembrou-se de Abraão e tirou Ló do meio da destruição, derrubando as cidades onde Ló morava."),
    ]},
    {"verses": [
      V(30, "Ló subiu de Zoar e passou a morar nos montes, com as duas filhas, porque teve medo de ficar em Zoar. Morou numa caverna, ele e as duas filhas."),
      V(31, "A filha mais velha disse à mais nova: “Nosso pai está velho, e não há homem na terra para se deitar conosco, como se faz em todo o mundo."),
      V(32, "Vamos dar vinho ao nosso pai, deitar-nos com ele e preservar a descendência do nosso pai.”"),
      V(33, "Naquela noite, deram vinho ao pai. A mais velha entrou e se deitou com o pai, sem que ele percebesse quando ela se deitou nem quando se levantou."),
      V(34, "No dia seguinte, a mais velha disse à mais nova: “Ontem à noite eu me deitei com o meu pai. Vamos dar-lhe vinho também esta noite; então você entra e se deita com ele, e preservaremos a descendência do nosso pai.”"),
      V(35, "Naquela noite também deram vinho ao pai, e a mais nova entrou e se deitou com ele, sem que ele percebesse quando ela se deitou nem quando se levantou."),
      V(36, "Assim as duas filhas de Ló engravidaram do próprio pai."),
      V(37, "A mais velha deu à luz um filho e o chamou de Moabe; ele é o pai dos moabitas de hoje."),
      V(38, "A mais nova também deu à luz um filho e o chamou de Ben-Ami; ele é o pai dos amonitas de hoje."),
    ]},
  ],
}

CH["20"] = {
  "verses": 18,
  "summary": "Em Gerar, Abraão repete o erro de apresentar Sara como irmã. Deus intervém em favor de Abimeleque, que devolve Sara, e Abraão ora — e Deus cura a casa do rei.",
  "sections": [
    {"title": "Abraão e Abimeleque", "start": 1},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Abraão partiu dali para a região do Neguebe e morou entre Cades e Sur. Depois, morou por um tempo em Gerar."),
      V(2, "Abraão dizia de Sara, sua mulher: “Ela é minha irmã.” Então Abimeleque, rei de Gerar, mandou buscar Sara."),
      V(3, "Mas, numa noite, Deus veio a Abimeleque em sonho e lhe disse: “Você vai morrer por causa da mulher que tomou, pois ela é casada.”"),
      V(4, "Abimeleque ainda não tinha tocado nela. Por isso perguntou: “Senhor, matarás um povo inocente?"),
      V(5, "Não foi ele que me disse: ‘Ela é minha irmã’? E ela mesma disse: ‘Ele é meu irmão.’ Fiz isso de coração puro e com as mãos limpas.”"),
      V(6, "Deus respondeu no sonho: “Sei que você fez isso de coração puro, e fui eu que o impedi de pecar contra mim. Por isso não deixei que você a tocasse."),
      V(7, "Agora devolva a mulher ao marido dela, pois ele é profeta e orará por você, para que você viva. Mas, se não a devolver, saiba que você e todos os seus certamente morrerão.”"),
      V(8, "De manhã cedo, Abimeleque convocou todos os seus servos e contou-lhes tudo. Os homens ficaram apavorados."),
      V(9, "Então Abimeleque chamou Abraão e perguntou: “O que foi que você fez conosco? Que pecado cometi contra você, para trazer sobre mim e sobre o meu reino essa culpa tão grande? Você fez comigo coisas que não se fazem.”"),
      V(10, "E perguntou ainda: “O que você tinha em mente quando fez isso?”"),
      V(11, "Abraão respondeu: “Pensei: certamente não há temor de Deus neste lugar, e vão me matar por causa da minha mulher."),
      V(12, "Além disso, ela é de fato minha irmã, filha do meu pai, embora não seja filha da minha mãe; e se tornou minha mulher."),
      V(13, "Quando Deus me fez sair da casa do meu pai, eu disse a ela: ‘Faça-me este favor: em todo lugar aonde formos, diga que eu sou seu irmão.’”"),
      V(14, "Então Abimeleque tomou ovelhas, bois, servos e servas e os deu a Abraão, e lhe devolveu Sara, sua mulher."),
      V(15, "E disse: “A minha terra está diante de você; more onde quiser.”"),
      V(16, "A Sara ele disse: “Dou ao seu irmão mil peças de prata. Isso será para você uma reparação diante de todos os que estão com você; assim você fica completamente inocentada.”"),
      V(17, "Abraão orou a Deus, e Deus curou Abimeleque, a mulher dele e as suas servas, para que pudessem ter filhos de novo —"),
      V(18, "porque o Senhor tinha tornado estéreis todas as mulheres da casa de Abimeleque, por causa de Sara, mulher de Abraão."),
    ]},
  ],
}

CH["21"] = {
  "verses": 34,
  "summary": "Nasce Isaque, o filho da promessa. Agar e Ismael são despedidos, mas Deus cuida deles no deserto. Abraão faz aliança com Abimeleque junto ao poço de Berseba.",
  "sections": [
    {"title": "O nascimento de Isaque", "start": 1},
    {"title": "Agar e Ismael no deserto", "start": 8},
    {"title": "A aliança em Berseba", "start": 22},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "O Senhor visitou Sara, como tinha dito, e cumpriu o que lhe prometera."),
      V(2, "Sara engravidou e deu um filho a Abraão na velhice dele, no tempo exato que Deus tinha marcado."),
      V(3, "Abraão chamou de Isaque o filho que Sara lhe deu."),
      V(4, "Quando Isaque tinha oito dias, Abraão o circuncidou, como Deus lhe tinha ordenado."),
      V(5, "Abraão tinha cem anos quando Isaque, seu filho, nasceu."),
      V(6, "Sara disse: “Deus me fez rir — e todos os que ouvirem vão rir comigo.”"),
      V(7, "E acrescentou: “Quem diria a Abraão que Sara amamentaria filhos? Pois eu dei um filho a ele na sua velhice!”"),
    ]},
    {"verses": [
      V(8, "O menino cresceu e foi desmamado. No dia em que Isaque foi desmamado, Abraão deu uma grande festa."),
      V(9, "Sara viu que o filho de Agar, a egípcia, que ela tinha dado a Abraão, estava zombando."),
      V(10, "Então disse a Abraão: “Mande embora essa serva e o filho dela, porque o filho dessa serva não será herdeiro com Isaque, o meu filho.”"),
      V(11, "Isso desagradou muito a Abraão, por causa do seu filho Ismael."),
      V(12, "Mas Deus disse a Abraão: “Não fique triste por causa do menino e da sua serva. Atenda a tudo o que Sara disser, porque é por meio de Isaque que a sua descendência será chamada."),
      V(13, "Mas também do filho da serva eu farei uma nação, porque ele é seu descendente.”"),
      V(14, "De manhã cedo, Abraão pegou pão e um odre de água, pôs tudo nos ombros de Agar, entregou-lhe o menino e a despediu. Ela partiu e ficou vagando pelo deserto de Berseba."),
      V(15, "Quando a água do odre acabou, Agar deixou o menino debaixo de um arbusto"),
      V(16, "e foi sentar-se sozinha à distância de um tiro de flecha, porque pensou: “Não suporto ver o menino morrer.” Sentada ali, ela começou a chorar em alta voz."),
      V(17, "Deus ouviu a voz do menino. O Anjo de Deus chamou Agar do céu e perguntou: “O que há, Agar? Não tenha medo, porque Deus ouviu a voz do menino, no lugar onde ele está."),
      V(18, "Levante-se, pegue o menino pela mão, porque eu farei dele uma grande nação.”"),
      V(19, "Então Deus abriu os olhos de Agar, e ela viu um poço de água. Ela foi, encheu o odre e deu de beber ao menino."),
      V(20, "Deus estava com o menino. Ele cresceu, morou no deserto e se tornou um atirador de flechas."),
      V(21, "Morou no deserto de Parã, e a mãe dele conseguiu para ele uma mulher da terra do Egito."),
    ]},
    {"verses": [
      V(22, "Naquele tempo, Abimeleque veio de Gerar com Ficol, comandante do seu exército, e disse a Abraão: “Deus está com você em tudo o que você faz."),
      V(23, "Agora jure aqui, por Deus, que você não enganará a mim, nem aos meus filhos, nem aos meus descendentes. Assim como eu fui leal com você, seja leal comigo e com esta terra onde você mora como estrangeiro.”"),
      V(24, "Abraão respondeu: “Eu juro.”"),
      V(25, "Mas Abraão reclamou com Abimeleque a respeito de um poço de água que os servos de Abimeleque tinham tomado à força."),
      V(26, "Abimeleque respondeu: “Não sei quem fez isso. Você nunca me falou, e só fiquei sabendo hoje.”"),
      V(27, "Então Abraão deu ovelhas e bois a Abimeleque, e os dois fizeram uma aliança."),
      V(28, "Abraão separou sete cordeiras do rebanho,"),
      V(29, "e Abimeleque perguntou: “O que significam essas sete cordeiras que você separou?”"),
      V(30, "Abraão respondeu: “Receba estas sete cordeiras como prova de que fui eu que cavei este poço.”"),
      V(31, "Por isso aquele lugar foi chamado de Berseba — “poço do juramento” —, porque ali os dois fizeram um juramento."),
      V(32, "Depois de fazerem a aliança em Berseba, Abimeleque e Ficol, comandante do seu exército, voltaram para a terra dos filisteus."),
      V(33, "Abraão plantou uma tamargueira em Berseba e ali invocou o nome do Senhor, o Deus eterno."),
      V(34, "E Abraão morou muito tempo na terra dos filisteus."),
    ]},
  ],
}

CH["22"] = {
  "verses": 24,
  "summary": "Deus prova Abraão pedindo Isaque em sacrifício. Abraão obedece até o último instante, e Deus provê um carneiro no lugar do menino, renovando a promessa.",
  "sections": [
    {"title": "A prova de Abraão", "start": 1},
    {"title": "O Senhor provê", "start": 9},
    {"title": "A promessa renovada", "start": 15},
    {"title": "A família de Naor", "start": 20},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Depois desses acontecimentos, Deus pôs Abraão à prova e lhe disse: “Abraão!” Ele respondeu: “Aqui estou.”"),
      V(2, "Deus disse: “Tome Isaque, o seu único filho, a quem você ama, vá à terra de Moriá e ofereça-o ali como holocausto, sobre um dos montes que eu vou indicar.”"),
      V(3, "Abraão se levantou de madrugada, preparou o jumento, levou consigo dois servos e Isaque, seu filho, cortou lenha para o holocausto e partiu para o lugar que Deus tinha indicado."),
      V(4, "No terceiro dia, Abraão levantou os olhos e viu o lugar de longe."),
      V(5, "Então disse aos servos: “Fiquem aqui com o jumento. Eu e o menino vamos até lá, adoraremos e voltaremos.”"),
      V(6, "Abraão pegou a lenha do holocausto e a colocou nos ombros de Isaque, seu filho; levou o fogo e a faca, e os dois seguiram juntos."),
      V(7, "Isaque disse a Abraão, seu pai: “Meu pai!” Ele respondeu: “Aqui estou, meu filho.” Isaque perguntou: “Temos o fogo e a lenha, mas onde está o cordeiro para o holocausto?”"),
      V(8, "Abraão respondeu: “Deus proverá para si o cordeiro para o holocausto, meu filho.” E os dois continuaram juntos."),
    ]},
    {"verses": [
      V(9, "Quando chegaram ao lugar que Deus tinha indicado, Abraão construiu o altar, arrumou a lenha, amarrou Isaque, seu filho, e o deitou sobre o altar, em cima da lenha."),
      V(10, "Estendeu a mão e pegou a faca para sacrificar o filho."),
      V(11, "Mas o Anjo do Senhor gritou do céu: “Abraão! Abraão!” Ele respondeu: “Aqui estou.”"),
      V(12, "O anjo disse: “Não estenda a mão contra o menino! Não faça nada a ele! Agora sei que você teme a Deus, porque não me negou o seu filho, o seu único filho.”"),
      V(13, "Abraão levantou os olhos e viu um carneiro preso pelos chifres num arbusto. Foi, pegou o carneiro e o ofereceu em holocausto no lugar do seu filho."),
      V(14, "E Abraão chamou aquele lugar de “O Senhor proverá”. Por isso até hoje se diz: “No monte do Senhor, ele proverá.”"),
    ]},
    {"verses": [
      V(15, "O Anjo do Senhor chamou Abraão do céu pela segunda vez"),
      V(16, "e disse: “Juro por mim mesmo, diz o Senhor: porque você fez isso e não me negou o seu filho, o seu único filho,"),
      V(17, "eu certamente o abençoarei e multiplicarei a sua descendência como as estrelas do céu e como a areia da praia do mar. A sua descendência possuirá as portas das suas cidades inimigas,"),
      V(18, "e por meio dela todas as nações da terra serão abençoadas, porque você obedeceu à minha voz.”"),
      V(19, "Abraão voltou para junto dos seus servos, e juntos partiram para Berseba. E Abraão ficou morando em Berseba."),
    ]},
    {"verses": [
      V(20, "Depois desses acontecimentos, contaram a Abraão: “Milca também deu filhos ao seu irmão Naor:"),
      V(21, "Uz, o mais velho, Buz, o irmão dele, Quemuel, pai de Arã,"),
      V(22, "Quésede, Hazo, Pildas, Jidlafe e Betuel.”"),
      V(23, "Betuel foi o pai de Rebeca. Esses foram os oito filhos que Milca deu a Naor, irmão de Abraão."),
      V(24, "A concubina de Naor, chamada Reumá, também teve filhos: Tebá, Gaã, Taás e Maacá."),
    ]},
  ],
}

CH["23"] = {
  "verses": 20,
  "summary": "Sara morre aos cento e vinte e sete anos. Abraão compra a caverna de Macpela, junto a Hebrom, como sepultura — sua primeira propriedade na terra prometida.",
  "sections": [
    {"title": "A morte de Sara", "start": 1},
    {"title": "A compra da caverna de Macpela", "start": 3},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Sara viveu cento e vinte e sete anos."),
      V(2, "Ela morreu em Quiriate-Arba, que é Hebrom, na terra de Canaã. Abraão foi lamentar por Sara e chorar por ela."),
    ]},
    {"verses": [
      V(3, "Depois Abraão se levantou de junto da sua falecida mulher e foi falar com os heteus:"),
      V(4, "“Sou estrangeiro e moro entre vocês. Cedam-me um lugar de sepultura, para que eu enterre a minha falecida mulher.”"),
      V(5, "Os heteus responderam a Abraão:"),
      V(6, "“Ouça-nos, senhor: você é um príncipe de Deus entre nós. Enterre a sua falecida na melhor das nossas sepulturas; nenhum de nós lhe negará a sua sepultura.”"),
      V(7, "Abraão se levantou, curvou-se diante do povo da terra, os heteus,"),
      V(8, "e disse: “Se vocês concordam que eu enterre aqui a minha falecida, ouçam-me e intercedam por mim junto a Efrom, filho de Zoar,"),
      V(9, "para que ele me ceda a caverna de Macpela, que fica no fim do campo dele, e que me pertence de direito. Que ele a ceda por um preço justo, para que eu tenha uma sepultura entre vocês.”"),
      V(10, "Efrom, o heteu, estava sentado entre os heteus. Ele respondeu a Abraão, ouvindo todos os que passavam pela porta da cidade:"),
      V(11, "“Não, meu senhor, ouça-me: eu lhe dou o campo e também a caverna que nele está. Na presença dos meus compatriotas, eu lhe dou tudo. Enterre a sua falecida.”"),
      V(12, "Abraão se curvou diante do povo da terra"),
      V(13, "e disse a Efrom, diante de todos: “Se você está disposto, ouça-me: pagarei o preço do campo. Aceite de mim, e enterrarei ali a minha falecida.”"),
      V(14, "Efrom respondeu:"),
      V(15, "“Meu senhor, ouça-me: um terreno de quatrocentas moedas de prata — o que é isso entre mim e você? Enterre a sua falecida.”"),
      V(16, "Abraão concordou com Efrom e pesou a ele a prata que ele tinha mencionado na presença dos heteus: quatrocentas moedas de prata, no padrão corrente dos comerciantes."),
      V(17, "Assim o campo de Efrom, que fica em Macpela, a leste de Manre — o campo com a caverna que nele está e todas as árvores dentro dos seus limites —"),
      V(18, "passou a ser propriedade de Abraão, diante dos heteus e de todos os que passavam pela porta da cidade."),
      V(19, "Depois disso, Abraão enterrou Sara, sua mulher, na caverna do campo de Macpela, a leste de Manre, que é Hebrom, na terra de Canaã."),
      V(20, "Assim o campo e a caverna que nele está passaram dos heteus para Abraão, como lugar de sepultura."),
    ]},
  ],
}

CH["24"] = {
  "verses": 67,
  "summary": "Abraão envia seu servo mais antigo a Harã para buscar uma esposa para Isaque. Guiado por Deus, o servo encontra Rebeca junto ao poço. Ela aceita partir, e Isaque a recebe com amor.",
  "sections": [
    {"title": "A missão do servo", "start": 1},
    {"title": "O encontro com Rebeca", "start": 10},
    {"title": "A família de Rebeca consente", "start": 29},
    {"title": "Isaque e Rebeca", "start": 61},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Abraão já estava velho, de idade avançada, e o Senhor o tinha abençoado em tudo."),
      V(2, "Ele disse ao servo mais antigo da sua casa, o administrador de todos os seus bens: “Coloque a mão debaixo da minha coxa,"),
      V(3, "e jure pelo Senhor, o Deus dos céus e o Deus da terra, que você não escolherá para o meu filho uma mulher entre as filhas dos cananeus, no meio dos quais eu moro."),
      V(4, "Vá à minha terra, à minha parentela, e de lá traga uma mulher para Isaque, meu filho.”"),
      V(5, "O servo perguntou: “E se a mulher não quiser vir comigo para esta terra? Devo levar o seu filho de volta à terra de onde o senhor saiu?”"),
      V(6, "Abraão respondeu: “Cuidado! Não leve o meu filho para lá."),
      V(7, "O Senhor, o Deus dos céus, que me tirou da casa do meu pai e da terra da minha parentela, e que me falou e jurou: ‘À sua descendência darei esta terra’ — ele enviará o anjo dele adiante de você, e você trará de lá uma mulher para o meu filho."),
      V(8, "Se a mulher não quiser vir com você, você estará livre deste juramento. Mas não leve o meu filho para lá.”"),
      V(9, "O servo colocou a mão debaixo da coxa de Abraão, seu senhor, e jurou cumprir o que lhe foi pedido."),
    ]},
    {"verses": [
      V(10, "O servo pegou dez camelos do seu senhor, com todo tipo de presentes, e partiu para a Mesopotâmia, para a cidade de Naor."),
      V(11, "Ao entardecer, hora em que as mulheres saem para tirar água, ele fez os camelos se ajoelharem junto ao poço, fora da cidade."),
      V(12, "E orou: “Senhor, Deus do meu senhor Abraão, dá-me hoje sucesso e mostra bondade ao meu senhor Abraão."),
      V(13, "Aqui estou eu, em pé junto à fonte, e as moças da cidade vêm tirar água."),
      V(14, "Que a jovem a quem eu disser: ‘Incline o seu cântaro para que eu beba’, e que responder: ‘Beba, e também darei de beber aos seus camelos’ — seja essa a que escolheste para o teu servo Isaque. Assim saberei que mostraste bondade ao meu senhor.”"),
      V(15, "Antes de ele terminar de orar, Rebeca saiu com o cântaro no ombro. Ela era filha de Betuel, filho de Milca, mulher de Naor, irmão de Abraão."),
      V(16, "A jovem era muito bonita, virgem, que nenhum homem tinha tocado. Desceu à fonte, encheu o cântaro e voltou."),
      V(17, "O servo correu ao encontro dela e disse: “Por favor, deixe-me beber um pouco de água do seu cântaro.”"),
      V(18, "Ela respondeu: “Beba, meu senhor.” E logo baixou o cântaro sobre o braço e deu-lhe de beber."),
      V(19, "Depois que ele bebeu, ela disse: “Vou tirar água também para os seus camelos, até que acabem de beber.”"),
      V(20, "Depressa, esvaziou o cântaro no bebedouro, correu de novo ao poço para tirar mais água e tirou para todos os camelos."),
      V(21, "O homem a observava em silêncio, para saber se o Senhor tinha dado sucesso à sua missão ou não."),
      V(22, "Quando os camelos acabaram de beber, o homem pegou um anel de ouro para o nariz, de seis gramas, e duas pulseiras de ouro para os braços, de cento e vinte gramas,"),
      V(23, "e perguntou: “De quem você é filha? Diga-me, por favor: há lugar na casa do seu pai para passarmos a noite?”"),
      V(24, "Ela respondeu: “Sou filha de Betuel, filho de Milca e de Naor.”"),
      V(25, "E acrescentou: “Temos muita palha e forragem, e também lugar para passar a noite.”"),
      V(26, "O homem se ajoelhou, prostrou-se diante do Senhor"),
      V(27, "e disse: “Bendito seja o Senhor, Deus do meu senhor Abraão, que não deixou de mostrar a sua bondade e a sua fidelidade ao meu senhor! O Senhor me guiou até a casa dos parentes do meu senhor.”"),
      V(28, "A jovem correu para casa e contou à família da sua mãe tudo o que tinha acontecido."),
    ]},
    {"verses": [
      V(29, "Rebeca tinha um irmão chamado Labão. Ele correu para fora, até o homem, junto à fonte."),
      V(30, "Quando viu o anel e as pulseiras nos braços da irmã, e ouviu Rebeca contar o que o homem tinha dito, Labão foi até ele, que ainda estava em pé junto aos camelos, na fonte."),
      V(31, "E disse: “Venha, abençoado do Senhor! Por que você está aí fora? Preparei a casa e lugar para os camelos.”"),
      V(32, "O homem entrou na casa. Descarregaram os camelos, deram palha e forragem a eles, trouxeram água para lavar os pés dele e dos que o acompanhavam."),
      V(33, "Depois serviram comida, mas ele disse: “Não comerei enquanto não expuser o que tenho a dizer.” Labão respondeu: “Fale.”"),
      V(34, "Então ele disse: “Sou servo de Abraão."),
      V(35, "O Senhor abençoou muito o meu senhor, que se tornou rico: deu-lhe ovelhas, bois, prata, ouro, servos e servas, camelos e jumentos."),
      V(36, "Sara, a mulher do meu senhor, deu um filho ao meu senhor na velhice dele, e ele entregou tudo o que possui ao filho."),
      V(37, "O meu senhor me fez jurar, dizendo: ‘Não escolha para o meu filho uma mulher entre as filhas dos cananeus, em cuja terra eu moro."),
      V(38, "Vá à casa do meu pai, à minha parentela, e de lá traga uma mulher para o meu filho.’"),
      V(39, "Eu perguntei ao meu senhor: ‘E se a mulher não quiser vir comigo?’"),
      V(40, "Ele respondeu: ‘O Senhor, em cuja presença eu ando, enviará o anjo dele com você e dará sucesso à sua missão, para que você traga para o meu filho uma mulher da minha parentela, da casa do meu pai."),
      V(41, "Você estará livre do juramento se, indo à minha parentela, eles não a derem a você. Só então estará livre do juramento.’"),
      V(42, "Hoje cheguei à fonte e orei: ‘Senhor, Deus do meu senhor Abraão, dá sucesso à missão em que estou."),
      V(43, "Aqui estou eu, em pé junto à fonte. Que a jovem que sair para tirar água, a quem eu disser: “Deixe-me beber um pouco de água do seu cântaro”,"),
      V(44, "e que me responder: “Beba, e também darei de beber aos seus camelos” — seja essa a mulher que o Senhor escolheu para o filho do meu senhor.’"),
      V(45, "Antes de eu terminar de orar em meu coração, Rebeca saiu com o cântaro no ombro, desceu à fonte e tirou água. Eu lhe disse: ‘Deixe-me beber, por favor.’"),
      V(46, "Ela baixou depressa o cântaro do ombro e disse: ‘Beba, e também darei de beber aos seus camelos.’ Eu bebi, e ela deu de beber também aos camelos."),
      V(47, "Então perguntei: ‘De quem você é filha?’ Ela respondeu: ‘Sou filha de Betuel, filho de Naor e de Milca.’ Pus o anel no nariz dela e as pulseiras nos braços dela,"),
      V(48, "e me ajoelhei e prostrei diante do Senhor. Bendisse o Senhor, Deus do meu senhor Abraão, que me guiou pelo caminho certo para buscar para o filho do meu senhor a filha do irmão dele."),
      V(49, "Agora, se vocês vão tratar o meu senhor com bondade e fidelidade, digam-me; e, se não, digam também, para que eu saiba o que fazer.”"),
      V(50, "Labão e Betuel responderam: “Isso vem do Senhor; não podemos dizer nem sim nem não."),
      V(51, "Rebeca está aqui, diante de você: leve-a e vá, e que ela seja a mulher do filho do seu senhor, como o Senhor falou.”"),
      V(52, "Quando o servo de Abraão ouviu essas palavras, prostrou-se em terra diante do Senhor."),
      V(53, "Depois trouxe joias de prata e de ouro e roupas, e as deu a Rebeca; e deu presentes valiosos ao irmão e à mãe dela."),
      V(54, "Então ele e os homens que o acompanhavam comeram, beberam e passaram a noite ali. De manhã, quando se levantaram, ele disse: “Deixem-me voltar ao meu senhor.”"),
      V(55, "O irmão e a mãe de Rebeca disseram: “Deixe a jovem ficar conosco mais uns dias, pelo menos dez; depois ela irá.”"),
      V(56, "Mas ele respondeu: “Não me detenham, pois o Senhor deu sucesso à minha missão. Deixem-me partir e voltar ao meu senhor.”"),
      V(57, "Eles disseram: “Vamos chamar a jovem e perguntar a ela.”"),
      V(58, "Chamaram Rebeca e perguntaram: “Você quer ir com este homem?” Ela respondeu: “Quero.”"),
      V(59, "Então despediram Rebeca, sua irmã de criação, e o servo de Abraão com os seus homens."),
      V(60, "Abençoaram Rebeca, dizendo: “Nossa irmã, que você se torne mãe de milhares de milhares, e que a sua descendência possua as portas das suas cidades inimigas!”"),
    ]},
    {"verses": [
      V(61, "Rebeca e as suas servas se levantaram, montaram nos camelos e seguiram o homem. O servo tomou Rebeca e partiu."),
      V(62, "Isaque tinha voltado do caminho de Beer-Laai-Roi, pois morava no Neguebe."),
      V(63, "Ao entardecer, saiu ao campo para meditar. Levantou os olhos e viu camelos se aproximando."),
      V(64, "Rebeca também levantou os olhos e, quando viu Isaque, desceu do camelo"),
      V(65, "e perguntou ao servo: “Quem é aquele homem que vem pelo campo ao nosso encontro?” O servo respondeu: “É o meu senhor.” Então ela pegou o véu e se cobriu."),
      V(66, "O servo contou a Isaque tudo o que tinha feito."),
      V(67, "Isaque levou Rebeca para a tenda de Sara, sua mãe; casou-se com ela e a amou. Assim Isaque foi consolado depois da morte da sua mãe."),
    ]},
  ],
}

CH["25"] = {
  "verses": 34,
  "summary": "Abraão morre e é sepultado ao lado de Sara. Nascem os gêmeos Esaú e Jacó. Esaú, por um prato de comida, vende o direito de primogenitura a Jacó.",
  "sections": [
    {"title": "A morte de Abraão", "start": 1},
    {"title": "Os descendentes de Ismael", "start": 12},
    {"title": "Esaú e Jacó", "start": 19},
    {"title": "A primogenitura vendida", "start": 29},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Abraão tomou outra mulher, chamada Quetura."),
      V(2, "Ela lhe deu Zinrã, Jocsã, Medã, Midiã, Isbaque e Suá."),
      V(3, "Jocsã foi pai de Sabá e Dedã. Os descendentes de Dedã foram os assuritas, os letusitas e os leumitas."),
      V(4, "Os filhos de Midiã foram Efá, Éfer, Enoque, Abida e Elda. Todos esses foram descendentes de Quetura."),
      V(5, "Abraão deixou tudo o que possuía para Isaque."),
      V(6, "Mas aos filhos das suas concubinas Abraão deu presentes e, ainda em vida, os enviou para o oriente, para longe de Isaque, seu filho."),
      V(7, "Abraão viveu cento e setenta e cinco anos."),
      V(8, "Morreu numa boa velhice, em idade avançada, depois de uma vida completa, e foi reunido ao seu povo."),
      V(9, "Isaque e Ismael, seus filhos, o sepultaram na caverna de Macpela, no campo de Efrom, filho de Zoar, o heteu, a leste de Manre —"),
      V(10, "o campo que Abraão tinha comprado dos heteus. Ali foram sepultados Abraão e Sara, sua mulher."),
      V(11, "Depois da morte de Abraão, Deus abençoou Isaque, seu filho. E Isaque passou a morar junto a Beer-Laai-Roi."),
    ]},
    {"verses": [
      V(12, "Estes são os descendentes de Ismael, filho de Abraão, que Agar, a egípcia, serva de Sara, deu a Abraão."),
      V(13, "Os nomes dos filhos de Ismael, por ordem de nascimento: Nebaiote, o mais velho, depois Quedar, Adbeel, Mibsão,"),
      V(14, "Misma, Dumá, Massá,"),
      V(15, "Hadade, Temá, Jetur, Nafis e Quedemá."),
      V(16, "Esses foram os filhos de Ismael, e esses os seus nomes nas suas vilas e acampamentos: doze príncipes das suas tribos."),
      V(17, "Ismael viveu cento e trinta e sete anos. Morreu e foi reunido ao seu povo."),
      V(18, "Os descendentes dele habitaram desde Havilá até Sur, que fica a leste do Egito, na direção da Assíria. E viveram em hostilidade contra todos os seus irmãos."),
    ]},
    {"verses": [
      V(19, "Esta é a história de Isaque, filho de Abraão. Abraão foi pai de Isaque."),
      V(20, "Isaque tinha quarenta anos quando se casou com Rebeca, filha de Betuel, o arameu de Padã-Arã, e irmã de Labão, o arameu."),
      V(21, "Isaque orou ao Senhor pela sua mulher, porque ela era estéril. O Senhor o atendeu, e Rebeca, sua mulher, engravidou."),
      V(22, "Os filhos lutavam dentro dela, e ela disse: “Se é assim, por que isso está acontecendo comigo?” E foi consultar o Senhor."),
      V(23, "O Senhor lhe respondeu: “Duas nações estão no seu ventre; dois povos sairão de você e se separarão. Um povo será mais forte que o outro, e o mais velho servirá o mais novo.”"),
      V(24, "Quando chegou o tempo do parto, havia gêmeos no ventre dela."),
      V(25, "O primeiro saiu ruivo, todo coberto de pelos como um manto; por isso o chamaram de Esaú."),
      V(26, "Depois saiu o irmão, com a mão agarrada no calcanhar de Esaú; por isso o chamaram de Jacó. Isaque tinha sessenta anos quando eles nasceram."),
      V(27, "Os meninos cresceram. Esaú se tornou um caçador habilidoso, homem do campo; Jacó era um homem tranquilo, que gostava de ficar nas tendas."),
      V(28, "Isaque amava Esaú, porque gostava da caça; mas Rebeca amava Jacó."),
    ]},
    {"verses": [
      V(29, "Certo dia, Jacó preparava um ensopado quando Esaú chegou do campo, exausto."),
      V(30, "Esaú disse a Jacó: “Deixa-me comer um pouco desse ensopado vermelho, porque estou exausto.” Por isso ele foi chamado de Edom — “vermelho”."),
      V(31, "Jacó respondeu: “Primeiro venda a mim o seu direito de filho mais velho.”"),
      V(32, "Esaú disse: “Estou quase morrendo! De que me serve o direito de filho mais velho?”"),
      V(33, "Jacó insistiu: “Jure primeiro.” Esaú jurou e vendeu a Jacó o direito de filho mais velho."),
      V(34, "Então Jacó deu a Esaú pão e o ensopado de lentilhas. Ele comeu, bebeu, levantou-se e foi embora. Foi assim que Esaú desprezou o seu direito de filho mais velho."),
    ]},
  ],
}

CH["26"] = {
  "verses": 35,
  "summary": "Isaque passa por fome, repete o erro do pai em Gerar e prospera tanto que é invejado. Ele cava poços, Deus lhe aparece em Berseba e renova a promessa. Esaú, porém, casa com mulheres que amarguram a família.",
  "sections": [
    {"title": "Isaque em Gerar", "start": 1},
    {"title": "Os poços de Isaque", "start": 12},
    {"title": "A promessa em Berseba", "start": 23},
    {"title": "As esposas de Esaú", "start": 34},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Houve fome na terra — além da primeira fome que tinha havido nos dias de Abraão — e Isaque foi para Gerar, até Abimeleque, rei dos filisteus."),
      V(2, "O Senhor apareceu a Isaque e disse: “Não desça ao Egito. More na terra que eu vou indicar."),
      V(3, "More nesta terra como estrangeiro, e eu estarei com você e o abençoarei. A você e à sua descendência darei todas estas terras e confirmarei o juramento que fiz ao seu pai Abraão."),
      V(4, "Multiplicarei a sua descendência como as estrelas do céu, darei a ela todas estas terras, e por meio dela todas as nações da terra serão abençoadas,"),
      V(5, "porque Abraão obedeceu à minha voz e guardou as minhas ordens, os meus mandamentos, os meus decretos e as minhas leis.”"),
      V(6, "Isaque ficou morando em Gerar."),
      V(7, "Quando os homens do lugar perguntavam sobre a mulher dele, ele dizia: “Ela é minha irmã” — porque tinha medo de dizer “é minha mulher”, pensando: “Os homens deste lugar podem me matar por causa de Rebeca, porque ela é muito bonita.”"),
      V(8, "Depois de muito tempo morando ali, Abimeleque, rei dos filisteus, olhou pela janela e viu Isaque acariciando Rebeca, sua mulher."),
      V(9, "Abimeleque chamou Isaque e disse: “Ela é a sua mulher! Por que você disse: ‘É minha irmã’?” Isaque respondeu: “Porque pensei que eu poderia ser morto por causa dela.”"),
      V(10, "Abimeleque disse: “O que foi que você fez conosco? Qualquer um do povo poderia ter se deitado com a sua mulher, e você teria trazido culpa sobre nós.”"),
      V(11, "Então Abimeleque deu esta ordem a todo o povo: “Quem tocar neste homem ou na mulher dele certamente morrerá.”"),
    ]},
    {"verses": [
      V(12, "Isaque semeou naquela terra e, naquele mesmo ano, colheu cem vezes mais, porque o Senhor o abençoou."),
      V(13, "Ele prosperou e foi ficando cada vez mais rico, até se tornar muito poderoso."),
      V(14, "Possuía rebanhos de ovelhas, gado e muitos servos. Por isso os filisteus começaram a ter inveja dele."),
      V(15, "E os filisteus entupiram com terra todos os poços que os servos do seu pai Abraão tinham cavado."),
      V(16, "Abimeleque disse a Isaque: “Saia do meio de nós, porque você se tornou poderoso demais para nós.”"),
      V(17, "Isaque saiu dali, acampou no vale de Gerar e ficou morando lá."),
      V(18, "Isaque reabriu os poços que tinham sido cavados nos dias do seu pai Abraão e que os filisteus tinham entupido depois da morte dele, e deu-lhes os mesmos nomes que o pai tinha dado."),
      V(19, "Os servos de Isaque cavaram no vale e encontraram um poço de água corrente."),
      V(20, "Mas os pastores de Gerar discutiram com os pastores de Isaque, dizendo: “A água é nossa!” Por isso ele chamou o poço de Eseque — “disputa” —, porque discutiram com ele."),
      V(21, "Cavaram outro poço, e também por causa dele houve discussão; por isso o chamou de Sitna — “hostilidade”."),
      V(22, "Isaque mudou-se dali e cavou outro poço; por esse não houve discussão. Ele o chamou de Reobote — “espaços abertos” —, dizendo: “Agora o Senhor nos deu espaço, e prosperaremos na terra.”"),
    ]},
    {"verses": [
      V(23, "De lá Isaque subiu para Berseba."),
      V(24, "Naquela noite, o Senhor apareceu a ele e disse: “Eu sou o Deus de Abraão, seu pai. Não tenha medo, porque eu estou com você. Vou abençoá-lo e multiplicar a sua descendência, por causa do meu servo Abraão.”"),
      V(25, "Isaque construiu ali um altar e invocou o nome do Senhor. Armou a sua tenda ali, e os seus servos cavaram um poço."),
      V(26, "Abimeleque veio de Gerar ao encontro de Isaque, com Auzate, seu conselheiro, e Ficol, comandante do seu exército."),
      V(27, "Isaque perguntou: “Por que vocês vieram até mim, se me odeiam e me expulsaram do meio de vocês?”"),
      V(28, "Eles responderam: “Vimos claramente que o Senhor está com você. Por isso dissemos: façamos um juramento entre nós — um acordo entre nós e você."),
      V(29, "Jure que não nos fará mal, assim como nós não o tocamos, mas fizemos somente o bem a você e o deixamos partir em paz. Agora você é o abençoado do Senhor.”"),
      V(30, "Isaque preparou um banquete para eles, e comeram e beberam."),
      V(31, "De manhã cedo, fizeram um juramento um ao outro. Depois Isaque os despediu, e eles partiram em paz."),
      V(32, "Naquele mesmo dia, os servos de Isaque vieram contar-lhe sobre o poço que tinham cavado: “Encontramos água!”"),
      V(33, "Ele o chamou de Sibá. Por isso a cidade se chama Berseba até hoje."),
    ]},
    {"verses": [
      V(34, "Esaú tinha quarenta anos quando se casou com Judite, filha de Beeri, o heteu, e com Basemate, filha de Elom, o heteu."),
      V(35, "Elas foram motivo de amargura para Isaque e Rebeca."),
    ]},
  ],
}

CH["27"] = {
  "verses": 46,
  "summary": "Com a ajuda de Rebeca, Jacó engana o pai cego e recebe a bênção de primogênito. Esaú fica furioso e jura matar o irmão; Rebeca envia Jacó para longe.",
  "sections": [
    {"title": "O plano de Rebeca", "start": 1},
    {"title": "A bênção roubada", "start": 18},
    {"title": "A dor de Esaú", "start": 30},
    {"title": "A fuga de Jacó", "start": 41},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Quando Isaque ficou velho e os olhos dele se enfraqueceram, a ponto de não enxergar mais, chamou Esaú, o filho mais velho, e disse: “Meu filho!” Ele respondeu: “Aqui estou.”"),
      V(2, "Isaque disse: “Estou velho e não sei o dia da minha morte."),
      V(3, "Pegue as suas armas, o seu arco e as suas flechas, vá ao campo e cace uma caça para mim."),
      V(4, "Prepare-me um prato saboroso, do jeito que eu gosto, e traga para eu comer, para que eu o abençoe antes de morrer.”"),
      V(5, "Rebeca ouviu o que Isaque disse a Esaú, seu filho. Quando Esaú saiu ao campo para caçar,"),
      V(6, "Rebeca disse a Jacó, seu filho: “Ouvi o seu pai dizer ao seu irmão Esaú:"),
      V(7, "‘Traga-me uma caça e prepare-me um prato saboroso, para eu comer e abençoar você na presença do Senhor, antes de morrer.’"),
      V(8, "Agora, meu filho, ouça o que vou dizer: faça exatamente o que eu ordenar."),
      V(9, "Vá ao rebanho e traga-me dois cabritos bons, para que eu prepare para o seu pai um prato saboroso, do jeito que ele gosta."),
      V(10, "Você o levará ao seu pai para comer, para que ele o abençoe antes de morrer.”"),
      V(11, "Jacó respondeu a Rebeca, sua mãe: “O meu irmão Esaú é peludo, e eu tenho a pele lisa."),
      V(12, "E se o meu pai me tocar? Ele vai perceber que estou enganando e, em vez de bênção, trarei maldição sobre mim.”"),
      V(13, "A mãe respondeu: “Que essa maldição caia sobre mim, meu filho. Apenas faça o que eu digo: vá e traga os cabritos.”"),
      V(14, "Jacó foi, pegou os cabritos e os trouxe à mãe, que preparou um prato saboroso, do jeito que o pai dele gostava."),
      V(15, "Rebeca pegou as melhores roupas de Esaú, o filho mais velho, que estavam na casa, e vestiu Jacó, o filho mais novo."),
      V(16, "Com as peles dos cabritos cobriu as mãos dele e a parte lisa do pescoço."),
      V(17, "E entregou a Jacó o prato saboroso e o pão que tinha preparado."),
    ]},
    {"verses": [
      V(18, "Jacó foi até o pai e disse: “Meu pai!” Isaque respondeu: “Aqui estou. Quem é você, meu filho?”"),
      V(19, "Jacó disse ao pai: “Sou Esaú, o seu filho mais velho. Fiz o que o senhor mandou. Levante-se, sente-se e coma da minha caça, para que me abençoe.”"),
      V(20, "Isaque perguntou: “Como você achou a caça tão depressa, meu filho?” Ele respondeu: “O Senhor, o seu Deus, a colocou no meu caminho.”"),
      V(21, "Isaque disse a Jacó: “Chegue mais perto, meu filho, para eu tocar em você e saber se é mesmo Esaú, o meu filho, ou não.”"),
      V(22, "Jacó se aproximou de Isaque, seu pai, que o tocou e disse: “A voz é a voz de Jacó, mas as mãos são as mãos de Esaú.”"),
      V(23, "Ele não o reconheceu, porque as mãos estavam peludas como as de Esaú, seu irmão. E o abençoou."),
      V(24, "Ainda perguntou: “Você é mesmo o meu filho Esaú?” Ele respondeu: “Sou.”"),
      V(25, "Então Isaque disse: “Sirva-me, meu filho, para eu comer da caça e abençoar você.” Jacó o serviu, e ele comeu; trouxe-lhe também vinho, e ele bebeu."),
      V(26, "Isaque, seu pai, disse: “Aproxime-se e me beije, meu filho.”"),
      V(27, "Jacó se aproximou e o beijou. Isaque sentiu o cheiro das roupas dele e o abençoou, dizendo: “O cheiro do meu filho é como o cheiro de um campo que o Senhor abençoou."),
      V(28, "Que Deus lhe dê o orvalho do céu e a riqueza da terra, com muito trigo e muito vinho."),
      V(29, "Que povos o sirvam e nações se curvem diante de você. Seja senhor dos seus irmãos, e os filhos da sua mãe se curvem diante de você. Maldito quem o amaldiçoar, e bendito quem o abençoar!”"),
    ]},
    {"verses": [
      V(30, "Quando Isaque terminou de abençoar Jacó, e Jacó mal tinha saído da presença do pai, Esaú, seu irmão, chegou da caçada."),
      V(31, "Ele também preparou um prato saboroso, trouxe ao pai e disse: “Levante-se, meu pai, e coma da caça do seu filho, para que me abençoe.”"),
      V(32, "Isaque, seu pai, perguntou: “Quem é você?” Ele respondeu: “Sou Esaú, o seu filho mais velho.”"),
      V(33, "Isaque tremeu de espanto e disse: “Então quem foi aquele que caçou e me trouxe a caça? Eu comi de tudo antes de você chegar, e o abençoei — e abençoado ele ficará.”"),
      V(34, "Quando Esaú ouviu as palavras do pai, gritou com um clamor muito grande e amargo, e disse: “Abençoe-me também, meu pai!”"),
      V(35, "Isaque respondeu: “O seu irmão veio com engano e levou a sua bênção.”"),
      V(36, "Esaú disse: “Não é à toa que ele se chama Jacó — ‘aquele que engana’! Já é a segunda vez que me engana: tomou o meu direito de filho mais velho, e agora tomou a minha bênção!” E perguntou: “O senhor não reservou nenhuma bênção para mim?”"),
      V(37, "Isaque respondeu: “Eu o constituí senhor sobre você, e dei a ele todos os seus irmãos como servos; eu o sustentei com trigo e vinho. O que mais posso fazer por você, meu filho?”"),
      V(38, "Esaú disse ao pai: “O senhor tem só uma bênção, meu pai? Abençoe-me também, meu pai!” E Esaú chorou em alta voz."),
      V(39, "Isaque, seu pai, respondeu: “Longe da riqueza da terra será a sua morada, longe do orvalho que desce do céu."),
      V(40, "Você viverá pela espada e servirá o seu irmão. Mas, quando você se rebelar, sacudirá o jugo dele do seu pescoço.”"),
    ]},
    {"verses": [
      V(41, "Esaú passou a odiar Jacó por causa da bênção que o pai lhe tinha dado, e pensou: “Estão próximos os dias de luto pelo meu pai; então matarei Jacó, meu irmão.”"),
      V(42, "Contaram a Rebeca o que Esaú, o filho mais velho, tinha dito. Ela mandou chamar Jacó, o filho mais novo, e disse: “O seu irmão Esaú quer se vingar, matando você."),
      V(43, "Agora, meu filho, ouça: fuja para a casa do meu irmão Labão, em Harã."),
      V(44, "Fique com ele por algum tempo, até passar a fúria do seu irmão,"),
      V(45, "até o rancor dele esfriar e ele esquecer o que você fez. Então mandarei buscá-lo. Por que eu perderia os meus dois filhos num só dia?”"),
      V(46, "Rebeca disse a Isaque: “Estou enjoada da minha vida por causa dessas mulheres heteias. Se Jacó também se casar com uma mulher desta terra, com uma heteia como essas, de que me servirá a vida?”"),
    ]},
  ],
}

CH["28"] = {
  "verses": 22,
  "summary": "Jacó foge para Harã. No caminho, sonha com uma escada que liga a terra ao céu e ouve Deus renovar a promessa. Ao acordar, consagra o lugar e faz um voto.",
  "sections": [
    {"title": "A partida para Harã", "start": 1},
    {"title": "O sonho da escada", "start": 10},
    {"title": "O voto de Jacó", "start": 16},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Isaque chamou Jacó, o abençoou e lhe ordenou: “Não se case com uma mulher de Canaã."),
      V(2, "Levante-se e vá a Padã-Arã, à casa de Betuel, pai da sua mãe, e case-se lá com uma das filhas de Labão, irmão da sua mãe."),
      V(3, "Que o Deus Todo-Poderoso o abençoe, o torne fértil e o multiplique, para que você se torne uma comunidade de povos."),
      V(4, "Que ele dê a você e à sua descendência a bênção de Abraão, para que você herde a terra onde mora como estrangeiro, a terra que Deus deu a Abraão.”"),
      V(5, "Assim Isaque despediu Jacó, que foi a Padã-Arã, à casa de Labão, filho de Betuel, o arameu, irmão de Rebeca, mãe de Jacó e de Esaú."),
      V(6, "Esaú viu que Isaque tinha abençoado Jacó e o tinha enviado a Padã-Arã para casar-se lá, e que, ao abençoá-lo, tinha ordenado: “Não se case com uma mulher de Canaã”."),
      V(7, "E viu também que Jacó tinha obedecido ao pai e à mãe e ido a Padã-Arã."),
      V(8, "Percebendo que as mulheres de Canaã desagradavam a Isaque, seu pai,"),
      V(9, "Esaú foi até a casa de Ismael e se casou também com Maalate, filha de Ismael, filho de Abraão, irmã de Nebaiote."),
    ]},
    {"verses": [
      V(10, "Jacó partiu de Berseba e seguiu para Harã."),
      V(11, "Chegando a certo lugar, passou a noite ali, porque o sol já tinha se posto. Pegou uma das pedras do lugar, usou como travesseiro e deitou-se para dormir."),
      V(12, "E sonhou: havia uma escada apoiada na terra, cujo topo alcançava o céu, e os anjos de Deus subiam e desciam por ela."),
      V(13, "Acima dela estava o Senhor, que disse: “Eu sou o Senhor, o Deus de Abraão, seu pai, e o Deus de Isaque. A terra onde você está deitado eu darei a você e à sua descendência."),
      V(14, "A sua descendência será como o pó da terra: você se espalhará para o oeste e para o leste, para o norte e para o sul. E por meio de você e da sua descendência todas as famílias da terra serão abençoadas."),
      V(15, "Eu estou com você e o guardarei por onde quer que você vá, e o trarei de volta a esta terra. Não o abandonarei até cumprir tudo o que lhe prometi.”"),
      V(16, "Jacó acordou do sono e disse: “Sem dúvida o Senhor está neste lugar, e eu não sabia!”"),
      V(17, "Teve medo e disse: “Que lugar temível é este! Isto não é outro lugar senão a casa de Deus; esta é a porta dos céus.”"),
      V(18, "De manhã cedo, Jacó se levantou, pegou a pedra que tinha usado como travesseiro, ergueu-a como coluna e derramou azeite sobre ela."),
      V(19, "E chamou aquele lugar de Betel — “casa de Deus” —, embora antes a cidade se chamasse Luz."),
    ]},
    {"verses": [
      V(20, "Jacó fez um voto, dizendo: “Se Deus estiver comigo, me guardar nesta viagem, me der pão para comer e roupa para vestir,"),
      V(21, "e eu voltar em paz à casa do meu pai, então o Senhor será o meu Deus."),
      V(22, "E esta pedra que ergui como coluna será a casa de Deus; e de tudo o que me deres, certamente te devolverei o dízimo.”"),
    ]},
  ],
}

CH["29"] = {
  "verses": 35,
  "summary": "Jacó chega à casa de Labão, apaixona-se por Raquel e trabalha sete anos por ela. Labão o engana, dando-lhe Lia primeiro, e Jacó trabalha mais sete anos por Raquel. Nascem os primeiros filhos de Jacó.",
  "sections": [
    {"title": "O encontro com Raquel", "start": 1},
    {"title": "O engano de Labão", "start": 15},
    {"title": "Os filhos de Jacó", "start": 31},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Jacó seguiu viagem e chegou à terra do oriente."),
      V(2, "Olhou e viu um poço no campo, e junto dele três rebanhos de ovelhas deitados, porque os rebanhos bebiam daquele poço. Uma grande pedra cobria a boca do poço."),
      V(3, "Quando todos os rebanhos se reuniam ali, os pastores rolavam a pedra da boca do poço, davam de beber às ovelhas e recolocavam a pedra no lugar."),
      V(4, "Jacó perguntou aos pastores: “Meus irmãos, de onde são vocês?” Eles responderam: “Somos de Harã.”"),
      V(5, "Ele perguntou: “Vocês conhecem Labão, filho de Naor?” Eles responderam: “Conhecemos.”"),
      V(6, "Jacó perguntou ainda: “Ele vai bem?” Responderam: “Vai bem. Aliás, Raquel, a filha dele, vem chegando com as ovelhas.”"),
      V(7, "Jacó disse: “Ainda é pleno dia, não é hora de recolher os rebanhos. Deem de beber às ovelhas e levem-nas de volta para pastar.”"),
      V(8, "Mas eles responderam: “Não podemos, enquanto todos os rebanhos não estiverem reunidos e a pedra não for rolada da boca do poço; só então damos de beber às ovelhas.”"),
      V(9, "Enquanto Jacó ainda falava com eles, Raquel chegou com as ovelhas do pai, pois era pastora."),
      V(10, "Quando Jacó viu Raquel, filha de Labão, irmão da sua mãe, aproximou-se, rolou a pedra da boca do poço e deu de beber às ovelhas de Labão, irmão da sua mãe."),
      V(11, "Jacó beijou Raquel e chorou em alta voz."),
      V(12, "Contou a ela que era parente do pai dela e filho de Rebeca. Ela correu e foi contar ao pai."),
      V(13, "Quando Labão ouviu as notícias sobre Jacó, filho da sua irmã, correu ao encontro dele, abraçou-o, beijou-o e o levou para casa. E Jacó contou a Labão tudo o que tinha acontecido."),
      V(14, "Labão disse: “Você é, de fato, osso meu e carne minha.” E Jacó ficou morando com ele um mês inteiro."),
    ]},
    {"verses": [
      V(15, "Labão disse a Jacó: “Só porque você é meu parente, vai trabalhar de graça para mim? Diga-me qual deve ser o seu salário.”"),
      V(16, "Labão tinha duas filhas: a mais velha se chamava Lia, e a mais nova, Raquel."),
      V(17, "Lia tinha olhos fracos, mas Raquel era bonita de corpo e de rosto."),
      V(18, "Jacó amava Raquel. Por isso respondeu: “Trabalharei sete anos para você em troca de Raquel, a sua filha mais nova.”"),
      V(19, "Labão disse: “É melhor dá-la a você do que a outro homem. Fique comigo.”"),
      V(20, "Assim Jacó trabalhou sete anos por Raquel — e lhe pareceram poucos dias, de tanto que a amava."),
      V(21, "Depois Jacó disse a Labão: “Entregue-me a minha mulher, porque o prazo já se completou, e quero me casar com ela.”"),
      V(22, "Labão reuniu todos os homens do lugar e deu uma festa."),
      V(23, "À noite, porém, tomou Lia, a sua filha, e a levou a Jacó, que se deitou com ela."),
      V(24, "Labão deu a sua serva Zilpa à sua filha Lia, como serva."),
      V(25, "Quando amanheceu, Jacó viu que era Lia! Então disse a Labão: “O que foi que você fez comigo? Eu não trabalhei para você em troca de Raquel? Por que você me enganou?”"),
      V(26, "Labão respondeu: “Aqui não se costuma dar a filha mais nova antes da mais velha."),
      V(27, "Complete a semana de festa desta, e lhe daremos também a outra, em troca de mais sete anos de trabalho.”"),
      V(28, "Jacó concordou. Completou a semana de Lia, e Labão lhe deu a filha Raquel como mulher."),
      V(29, "Labão deu a sua serva Bila à sua filha Raquel, como serva."),
      V(30, "Jacó também se deitou com Raquel e a amou mais do que a Lia. E trabalhou para Labão mais sete anos."),
    ]},
    {"verses": [
      V(31, "O Senhor viu que Lia era desprezada e a tornou fértil; Raquel, porém, era estéril."),
      V(32, "Lia engravidou e deu à luz um filho, a quem chamou Rúben — “vejam, um filho” —, dizendo: “O Senhor viu a minha aflição. Agora o meu marido me amará.”"),
      V(33, "Engravidou de novo e deu à luz outro filho. E disse: “O Senhor ouviu que eu era desprezada e me deu também este.” Por isso o chamou Simeão — “ouvido”."),
      V(34, "Engravidou mais uma vez e deu à luz outro filho. E disse: “Agora, desta vez, o meu marido vai se apegar a mim, porque lhe dei três filhos.” Por isso o chamou Levi — “apegado”."),
      V(35, "Engravidou ainda outra vez e deu à luz outro filho. E disse: “Desta vez louvarei o Senhor.” Por isso o chamou Judá — “louvor”. Então parou de ter filhos."),
    ]},
  ],
}

CH["30"] = {
  "verses": 43,
  "summary": "Nascem os demais filhos de Jacó. Depois, ele faz um acordo com Labão e, com a bênção de Deus, prospera muito — voltando para casa rico.",
  "sections": [
    {"title": "Os filhos de Bila e Zilpa", "start": 1},
    {"title": "Os filhos de Lia", "start": 14},
    {"title": "O nascimento de José", "start": 22},
    {"title": "O acordo com Labão", "start": 25},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Raquel viu que não dava filhos a Jacó e teve inveja da irmã. Disse a Jacó: “Dê-me filhos, senão eu morro!”"),
      V(2, "Jacó ficou irritado com Raquel e disse: “Por acaso eu estou no lugar de Deus, que impediu você de ter filhos?”"),
      V(3, "Ela respondeu: “Aqui está a minha serva Bila. Deite-se com ela, para que ela dê à luz sobre os meus joelhos; assim também eu terei filhos por meio dela.”"),
      V(4, "Então Raquel deu a Jacó a sua serva Bila como mulher, e Jacó se deitou com ela."),
      V(5, "Bila engravidou e deu um filho a Jacó."),
      V(6, "Raquel disse: “Deus me fez justiça, ouviu a minha voz e me deu um filho.” Por isso o chamou Dã — “justiça”."),
      V(7, "Bila, a serva de Raquel, engravidou de novo e deu um segundo filho a Jacó."),
      V(8, "Raquel disse: “Travei uma luta tremenda com a minha irmã e venci.” Por isso o chamou Naftali — “luta”."),
      V(9, "Lia viu que tinha parado de ter filhos. Então tomou Zilpa, a sua serva, e a deu a Jacó como mulher."),
      V(10, "Zilpa, a serva de Lia, deu um filho a Jacó."),
      V(11, "Lia disse: “Que sorte!” Por isso o chamou Gade — “sorte”."),
      V(12, "Zilpa, a serva de Lia, deu um segundo filho a Jacó."),
      V(13, "Lia disse: “Que felicidade! As mulheres me chamarão feliz.” Por isso o chamou Aser — “feliz”."),
    ]},
    {"verses": [
      V(14, "Na época da colheita do trigo, Rúben saiu ao campo, achou mandrágoras e as trouxe a Lia, sua mãe. Raquel disse a Lia: “Dê-me algumas das mandrágoras do seu filho.”"),
      V(15, "Lia respondeu: “Não basta você ter tomado o meu marido? Quer tomar também as mandrágoras do meu filho?” Raquel disse: “Pois bem: esta noite ele se deitará com você, em troca das mandrágoras do seu filho.”"),
      V(16, "Ao entardecer, quando Jacó voltava do campo, Lia saiu ao encontro dele e disse: “Você vai se deitar comigo, porque eu paguei por você com as mandrágoras do meu filho.” E Jacó se deitou com ela naquela noite."),
      V(17, "Deus ouviu Lia, e ela engravidou e deu a Jacó o quinto filho."),
      V(18, "Lia disse: “Deus me recompensou, porque dei a minha serva ao meu marido.” Por isso o chamou Issacar — “recompensa”."),
      V(19, "Lia engravidou de novo e deu a Jacó o sexto filho."),
      V(20, "E disse: “Deus me deu um presente precioso. Agora o meu marido me honrará, porque lhe dei seis filhos.” Por isso o chamou Zebulom — “honra”."),
      V(21, "Depois ela deu à luz uma filha, e a chamou Diná."),
    ]},
    {"verses": [
      V(22, "Deus se lembrou de Raquel, ouviu o clamor dela e a tornou fértil."),
      V(23, "Ela engravidou e deu à luz um filho, e disse: “Deus tirou a minha vergonha.”"),
      V(24, "E o chamou José — “que ele acrescente” —, dizendo: “Que o Senhor me dê ainda outro filho.”"),
    ]},
    {"verses": [
      V(25, "Depois que Raquel deu à luz José, Jacó disse a Labão: “Deixe-me voltar para a minha terra e para o meu lugar."),
      V(26, "Entregue-me as minhas mulheres, pelas quais trabalhei para você, e os meus filhos, e deixe-me partir. Você bem sabe o trabalho que fiz para você.”"),
      V(27, "Labão respondeu: “Se encontrei favor aos seus olhos, fique. Eu descobri que o Senhor me abençoou por sua causa.”"),
      V(28, "E acrescentou: “Diga qual deve ser o seu salário, e eu pagarei.”"),
      V(29, "Jacó respondeu: “Você sabe como trabalhei para você e como os seus rebanhos prosperaram sob os meus cuidados."),
      V(30, "O pouco que você tinha antes de eu chegar aumentou muito, e o Senhor o abençoou por minha causa. Agora, quando vou começar a trabalhar pela minha própria casa?”"),
      V(31, "Labão perguntou: “O que devo dar a você?” Jacó respondeu: “Não me dê nada. Se você fizer o que vou propor, continuarei cuidando dos seus rebanhos:"),
      V(32, "hoje vou passar por todo o rebanho e separar todos os animais salpicados e malhados, todas as ovelhas escuras e todos os cabritos salpicados e malhados. Esses serão o meu salário."),
      V(33, "Assim a minha honestidade falará por mim no futuro: quando você vier verificar o meu salário, tudo o que não for salpicado ou malhado entre os cabritos, ou escuro entre as ovelhas, será considerado roubo da minha parte.”"),
      V(34, "Labão concordou: “Está bem. Que seja como você disse.”"),
      V(35, "Naquele mesmo dia, porém, Labão separou os bodes listrados e malhados, todas as cabras salpicadas e malhadas — tudo o que tinha alguma mancha branca — e todas as ovelhas escuras, e os entregou aos seus filhos."),
      V(36, "E colocou três dias de viagem entre ele e Jacó. Jacó continuou cuidando do restante do rebanho de Labão."),
      V(37, "Jacó pegou varas verdes de estoraque, de amendoeira e de plátano, descascou nelas listras brancas, expondo a parte branca das varas,"),
      V(38, "e as colocou nos bebedouros, diante dos rebanhos, onde os animais vinham beber; porque os animais acasalavam quando vinham beber."),
      V(39, "Os rebanhos acasalavam diante das varas e davam crias listradas, salpicadas e malhadas."),
      V(40, "Jacó separava os cordeiros e fazia os rebanhos de Labão olharem para os animais listrados e para todos os escuros. Assim formou rebanhos para si, que não misturava com os de Labão."),
      V(41, "Sempre que as fêmeas fortes estavam no cio, Jacó punha as varas nos bebedouros, diante delas, para que acasalassem diante das varas."),
      V(42, "Mas quando as fêmeas eram fracas, não as punha. Assim as fracas ficavam para Labão, e as fortes, para Jacó."),
      V(43, "O homem se tornou muito rico: tinha grandes rebanhos, servos e servas, camelos e jumentos."),
    ]},
  ],
}

CH["31"] = {
  "verses": 55,
  "summary": "Deus manda Jacó voltar a Canaã. Ele parte em segredo com a família e os bens; Raquel leva os ídolos do pai. Labão o persegue, mas Deus intervém, e os dois fazem um pacto de paz.",
  "sections": [
    {"title": "A partida de Jacó", "start": 1},
    {"title": "Labão persegue Jacó", "start": 22},
    {"title": "O pacto entre Labão e Jacó", "start": 43},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Jacó ouviu os filhos de Labão comentarem: “Jacó tomou tudo o que era do nosso pai e foi com os bens do nosso pai que ele juntou toda essa riqueza.”"),
      V(2, "E percebeu que Labão já não o olhava como antes."),
      V(3, "O Senhor disse a Jacó: “Volte para a terra dos seus pais, para a sua parentela, e eu estarei com você.”"),
      V(4, "Jacó mandou chamar Raquel e Lia ao campo, onde estava o seu rebanho,"),
      V(5, "e disse a elas: “Vejo que o seu pai já não me olha como antes. Mas o Deus do meu pai tem estado comigo."),
      V(6, "Vocês sabem que trabalhei para o seu pai com todas as minhas forças,"),
      V(7, "e ele me enganou: mudou o meu salário dez vezes. Mas Deus não permitiu que ele me prejudicasse."),
      V(8, "Quando ele dizia: ‘Os salpicados serão o seu salário’, todo o rebanho dava crias salpicadas. Quando dizia: ‘Os listrados serão o seu salário’, todo o rebanho dava crias listradas."),
      V(9, "Foi assim que Deus tirou o rebanho do seu pai e o deu a mim."),
      V(10, "Na época do acasalamento, tive um sonho: olhei e vi que os machos que cobriam as fêmeas eram listrados, salpicados e malhados."),
      V(11, "O Anjo de Deus me chamou no sonho: ‘Jacó!’ Eu respondi: ‘Aqui estou.’"),
      V(12, "Ele disse: ‘Levante os olhos e veja: todos os machos que cobrem as fêmeas são listrados, salpicados e malhados, porque vi tudo o que Labão está fazendo com você."),
      V(13, "Eu sou o Deus de Betel, onde você ungiu uma coluna e me fez um voto. Agora levante-se, saia desta terra e volte para a terra da sua parentela.’”"),
      V(14, "Raquel e Lia responderam: “Será que ainda temos parte ou herança na casa do nosso pai?"),
      V(15, "Ele não nos tratou como filhas? Não fomos consideradas estrangeiras? Ele nos vendeu e ainda gastou o nosso dinheiro!"),
      V(16, "Toda a riqueza que Deus tirou do nosso pai é nossa e dos nossos filhos. Faça agora tudo o que Deus lhe mandou.”"),
      V(17, "Então Jacó se levantou, colocou os filhos e as mulheres sobre os camelos,"),
      V(18, "reuniu todo o seu rebanho e todos os bens que tinha acumulado em Padã-Arã e partiu para a terra de Canaã, à casa de Isaque, seu pai."),
      V(19, "Enquanto Labão tinha ido tosquiar as ovelhas, Raquel roubou os ídolos da casa do pai."),
      V(20, "Jacó enganou Labão, o arameu, fugindo sem avisar."),
      V(21, "E fugiu com tudo o que tinha. Levantou-se, atravessou o rio Eufrates e seguiu rumo aos montes de Gileade."),
    ]},
    {"verses": [
      V(22, "No terceiro dia, contaram a Labão que Jacó tinha fugido."),
      V(23, "Labão reuniu os seus parentes e o perseguiu por sete dias, até alcançá-lo nos montes de Gileade."),
      V(24, "Mas, à noite, Deus veio em sonho a Labão, o arameu, e disse: “Cuidado! Não diga nada a Jacó, nem bem nem mal.”"),
      V(25, "Labão alcançou Jacó, que tinha armado a sua tenda nos montes. Labão e os parentes dele também acamparam nos montes de Gileade."),
      V(26, "Labão disse a Jacó: “O que foi que você fez? Você me enganou e levou as minhas filhas como prisioneiras de guerra!"),
      V(27, "Por que fugiu em segredo, me enganando, sem me avisar? Eu teria despedido você com alegria, com cânticos, tamborins e harpas!"),
      V(28, "Você nem me deixou beijar os meus netos e as minhas filhas. Você agiu como um tolo."),
      V(29, "Eu poderia fazer mal a vocês, mas, na noite passada, o Deus do pai de vocês me disse: ‘Cuidado! Não diga nada a Jacó, nem bem nem mal.’"),
      V(30, "Sei que você partiu porque tinha saudade da casa do seu pai. Mas por que roubou os meus deuses?”"),
      V(31, "Jacó respondeu a Labão: “Tive medo, pensando que você me tomaria as suas filhas à força."),
      V(32, "Mas quem for achado com os seus deuses não ficará vivo! Na presença dos nossos parentes, verifique você mesmo o que está comigo e leve o que for seu.” Jacó não sabia que Raquel os tinha roubado."),
      V(33, "Labão entrou na tenda de Jacó, na tenda de Lia e na tenda das duas servas, mas não achou nada. Saiu da tenda de Lia e entrou na tenda de Raquel."),
      V(34, "Raquel tinha escondido os ídolos na sela do camelo e estava sentada em cima deles. Labão vasculhou toda a tenda, mas não os encontrou."),
      V(35, "Ela disse ao pai: “Não fique zangado, meu senhor, por eu não conseguir me levantar diante de você, pois estou no período das mulheres.” Labão procurou por toda parte, mas não achou os ídolos."),
      V(36, "Jacó ficou indignado e reclamou com Labão: “Qual foi o meu crime? Qual foi o meu pecado, para você me perseguir com tanta fúria?"),
      V(37, "Você vasculhou todos os meus bens. O que achou da sua casa? Ponha aqui, diante dos nossos parentes, para que julguem entre nós dois!"),
      V(38, "Fiquei vinte anos com você: as suas ovelhas e cabras não abortaram, e eu não comi os carneiros do seu rebanho."),
      V(39, "Os animais despedaçados eu nunca trouxe a você; eu mesmo pagava o prejuízo. Você cobrava de mim o que era roubado de dia e de noite."),
      V(40, "De dia o calor me devorava, e de noite o frio; e o sono fugia dos meus olhos."),
      V(41, "Foram vinte anos na sua casa: catorze trabalhando pelas suas duas filhas e seis pelo seu rebanho. E você mudou o meu salário dez vezes!"),
      V(42, "Se o Deus do meu pai, o Deus de Abraão e o Temor de Isaque, não estivesse comigo, você teria me mandado embora de mãos vazias. Mas Deus viu a minha aflição e o trabalho das minhas mãos, e ontem à noite ele julgou a causa.”"),
    ]},
    {"verses": [
      V(43, "Labão respondeu: “As filhas são minhas filhas, os netos são meus netos, os rebanhos são meus rebanhos — tudo o que você vê é meu. O que eu poderia fazer hoje contra as minhas filhas ou contra os filhos que elas deram à luz?"),
      V(44, "Venha, façamos um pacto, eu e você, e que ele sirva de testemunho entre nós.”"),
      V(45, "Jacó pegou uma pedra e a ergueu como coluna."),
      V(46, "E disse aos parentes: “Juntem pedras.” Eles juntaram pedras e fizeram um monte, e comeram ali, junto ao monte."),
      V(47, "Labão o chamou de Jegar-Saaduta, e Jacó o chamou de Galeede — “monte do testemunho”."),
      V(48, "Labão disse: “Este monte é hoje testemunha entre mim e você.” Por isso foi chamado Galeede,"),
      V(49, "e também Mispá — “torre de vigia” —, porque ele disse: “Que o Senhor vigie entre mim e você, quando estivermos longe um do outro."),
      V(50, "Se você maltratar as minhas filhas ou tomar outras mulheres além delas, mesmo que ninguém esteja conosco, lembre-se: Deus é testemunha entre mim e você.”"),
      V(51, "Labão disse ainda: “Aqui estão este monte e esta coluna que levantei entre nós."),
      V(52, "Este monte é testemunha, e esta coluna é testemunha, de que eu não passarei deste monte para o seu lado para lhe fazer mal, e você não passará deste monte e desta coluna para o meu lado para me fazer mal."),
      V(53, "Que o Deus de Abraão e o Deus de Naor, o Deus do pai deles, julguem entre nós.” E Jacó jurou pelo Temor de Isaque, seu pai."),
      V(54, "Jacó ofereceu um sacrifício no monte e convidou os parentes para comer. Eles comeram e passaram a noite no monte."),
      V(55, "De manhã cedo, Labão beijou os netos e as filhas, abençoou-os e partiu de volta para casa."),
    ]},
  ],
}

CH["32"] = {
  "verses": 32,
  "summary": "Jacó se prepara para reencontrar Esaú e, na noite anterior, luta com um homem misterioso até o amanhecer. Ele sai manco, mas com um novo nome: Israel.",
  "sections": [
    {"title": "Os preparativos para encontrar Esaú", "start": 1},
    {"title": "A luta em Peniel", "start": 22},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Jacó seguiu o seu caminho, e os anjos de Deus vieram ao seu encontro."),
      V(2, "Quando os viu, disse: “Este é o acampamento de Deus!” E chamou aquele lugar de Maanaim — “dois acampamentos”."),
      V(3, "Jacó enviou mensageiros adiante de si ao seu irmão Esaú, na terra de Seir, no território de Edom."),
      V(4, "E ordenou: “Digam assim ao meu senhor Esaú: ‘Assim diz o seu servo Jacó: morei com Labão e lá fiquei até agora."),
      V(5, "Tenho bois, jumentos, ovelhas, servos e servas. Mando esta mensagem ao meu senhor para que eu encontre favor aos seus olhos.’”"),
      V(6, "Os mensageiros voltaram e disseram a Jacó: “Fomos até o seu irmão Esaú, e ele vem ao seu encontro com quatrocentos homens.”"),
      V(7, "Jacó ficou com muito medo e angustiado. Dividiu em dois grupos o povo, os rebanhos, o gado e os camelos que estavam com ele,"),
      V(8, "pensando: “Se Esaú atacar um grupo, o outro poderá escapar.”"),
      V(9, "Então Jacó orou: “Deus do meu pai Abraão, Deus do meu pai Isaque, Senhor que me disseste: ‘Volte para a sua terra, para a sua parentela, e eu o tratarei bem’,"),
      V(10, "sou indigno de toda a bondade e de toda a fidelidade que mostraste ao teu servo. Com apenas o meu cajado atravessei este Jordão, e agora sou dono de dois acampamentos."),
      V(11, "Livra-me, por favor, das mãos do meu irmão Esaú, porque tenho medo de que ele venha e ataque a mim, as mães e as crianças."),
      V(12, "Tu mesmo disseste: ‘Certamente eu o tratarei bem e tornarei a sua descendência como a areia do mar, que ninguém pode contar.’”"),
      V(13, "Jacó passou a noite ali. Do que possuía, separou um presente para Esaú, seu irmão:"),
      V(14, "duzentas cabras e vinte bodes, duzentas ovelhas e vinte carneiros,"),
      V(15, "trinta camelas com suas crias, quarenta vacas e dez touros, vinte jumentas e dez jumentos."),
      V(16, "Dividiu-os em grupos e os entregou aos servos, dizendo: “Vão na minha frente e deixem espaço entre os grupos.”"),
      V(17, "Ao primeiro ordenou: “Quando Esaú, meu irmão, encontrar você e perguntar: ‘De quem você é? Aonde vai? De quem é este rebanho à sua frente?’,"),
      V(18, "responda: ‘É do seu servo Jacó. É um presente enviado ao meu senhor Esaú, e ele mesmo vem atrás de nós.’”"),
      V(19, "Deu a mesma ordem ao segundo e ao terceiro, e a todos os que iam na frente dos rebanhos: “Digam isso mesmo a Esaú quando o encontrarem."),
      V(20, "E digam também: ‘O seu servo Jacó vem atrás de nós.’” Pois pensava: “Vou acalmá-lo com os presentes que vão à minha frente; só depois verei o seu rosto. Talvez ele me aceite.”"),
      V(21, "Assim os presentes seguiram na frente. Jacó, porém, passou a noite no acampamento."),
    ]},
    {"verses": [
      V(22, "Naquela mesma noite, Jacó se levantou, tomou as duas mulheres, as duas servas e os onze filhos e atravessou o vau do Jaboque."),
      V(23, "Ele os ajudou a atravessar o ribeiro e fez passar tudo o que possuía."),
      V(24, "E Jacó ficou sozinho. Então um homem lutou com ele até o amanhecer."),
      V(25, "Quando o homem viu que não podia vencê-lo, tocou na articulação da coxa de Jacó, e a coxa dele se deslocou enquanto lutavam."),
      V(26, "O homem disse: “Solte-me, pois o dia está amanhecendo.” Jacó respondeu: “Não o solto enquanto você não me abençoar.”"),
      V(27, "O homem perguntou: “Qual é o seu nome?” Ele respondeu: “Jacó.”"),
      V(28, "Então disse: “Seu nome não será mais Jacó, e sim Israel — ‘aquele que luta com Deus’ —, porque você lutou com Deus e com os homens, e venceu.”"),
      V(29, "Jacó perguntou: “Diga-me o seu nome, por favor.” Ele respondeu: “Por que pergunta o meu nome?” E ali mesmo o abençoou."),
      V(30, "Jacó chamou aquele lugar de Peniel — “face de Deus” —, dizendo: “Vi Deus face a face, e a minha vida foi poupada.”"),
      V(31, "O sol já tinha nascido quando ele atravessou Peniel, mancando por causa da coxa."),
      V(32, "Por isso, até hoje os israelitas não comem o músculo da coxa, junto à articulação, porque o homem tocou ali na articulação da coxa de Jacó."),
    ]},
  ],
}

CH["33"] = {
  "verses": 20,
  "summary": "O reencontro de Jacó com Esaú é surpreendentemente pacífico: Esaú o abraça e chora. Depois cada um segue seu caminho, e Jacó se estabelece em Siquém.",
  "sections": [
    {"title": "O reencontro com Esaú", "start": 1},
    {"title": "Jacó se estabelece em Siquém", "start": 17},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Jacó levantou os olhos e viu Esaú chegando, com quatrocentos homens. Então dividiu as crianças entre Lia, Raquel e as duas servas."),
      V(2, "Colocou na frente as servas com os filhos delas, depois Lia com os filhos dela, e por último Raquel com José."),
      V(3, "Ele mesmo passou à frente de todos e se prostrou até o chão sete vezes, até se aproximar do irmão."),
      V(4, "Mas Esaú correu ao encontro dele, abraçou-o, lançou-se sobre o seu pescoço e o beijou. E os dois choraram."),
      V(5, "Esaú levantou os olhos, viu as mulheres e as crianças e perguntou: “Quem são estes que estão com você?” Jacó respondeu: “São os filhos que Deus, na sua bondade, deu ao seu servo.”"),
      V(6, "As servas se aproximaram com os filhos e se prostraram."),
      V(7, "Lia também se aproximou com os filhos e se prostrou. Por fim, José e Raquel se aproximaram e se prostraram."),
      V(8, "Esaú perguntou: “O que você quer dizer com todos esses grupos que encontrei?” Jacó respondeu: “É para encontrar favor aos olhos do meu senhor.”"),
      V(9, "Esaú disse: “Eu tenho muito, meu irmão. Fique com o que é seu.”"),
      V(10, "Jacó insistiu: “Não! Se encontrei favor aos seus olhos, aceite o meu presente, porque ver o seu rosto é como ver o rosto de Deus — e você me recebeu tão bem!"),
      V(11, "Aceite, por favor, a bênção que trouxe para você, porque Deus foi generoso comigo, e tenho tudo o que preciso.” Jacó insistiu tanto, que Esaú aceitou."),
      V(12, "Esaú disse: “Vamos partir. Eu seguirei com você.”"),
      V(13, "Mas Jacó respondeu: “O meu senhor sabe que as crianças são frágeis, e que tenho ovelhas e vacas com crias. Se forçarmos o passo um só dia, todo o rebanho morrerá."),
      V(14, "Vá o meu senhor na frente do seu servo. Eu seguirei devagar, no ritmo do gado e das crianças, até chegar ao meu senhor em Seir.”"),
      V(15, "Esaú disse: “Então deixarei com você alguns dos meus homens.” Jacó respondeu: “Não é necessário. Basta que eu encontre favor aos olhos do meu senhor.”"),
      V(16, "Naquele mesmo dia, Esaú voltou pelo seu caminho para Seir."),
    ]},
    {"verses": [
      V(17, "Jacó, porém, foi para Sucote, onde construiu uma casa para si e abrigos para o gado. Por isso o lugar foi chamado de Sucote — “abrigos”."),
      V(18, "Depois de voltar de Padã-Arã, Jacó chegou em paz à cidade de Siquém, na terra de Canaã, e acampou diante da cidade."),
      V(19, "Comprou dos filhos de Hamor, pai de Siquém, o terreno onde tinha armado a sua tenda, por cem moedas de prata."),
      V(20, "Ali ergueu um altar e o chamou de El-Eloé-Israel — “Deus, o Deus de Israel”."),
    ]},
  ],
}

CH["34"] = {
  "verses": 31,
  "summary": "Diná, filha de Jacó, é violentada por Siquém. Seus irmãos Simeão e Levi se vingam com uma traição brutal, matando todos os homens da cidade — e Jacó fica indignado.",
  "sections": [
    {"title": "A desonra de Diná", "start": 1},
    {"title": "A vingança de Simeão e Levi", "start": 13},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Certo dia, Diná, filha que Lia tinha dado a Jacó, saiu para visitar as mulheres da terra."),
      V(2, "Siquém, filho de Hamor, o heveu, príncipe daquela terra, viu-a, agarrou-a, deitou-se com ela e a violentou."),
      V(3, "Mas o coração dele se apegou a Diná, filha de Jacó; ele amou a jovem e falou com carinho ao coração dela."),
      V(4, "Siquém disse a Hamor, seu pai: “Consiga essa jovem para mim, para ser a minha mulher.”"),
      V(5, "Jacó soube que a sua filha Diná tinha sido desonrada. Mas, como os filhos dele estavam no campo com o gado, ficou calado até que voltassem."),
      V(6, "Hamor, pai de Siquém, foi falar com Jacó."),
      V(7, "Os filhos de Jacó voltaram do campo e, quando souberam do que tinha acontecido, ficaram indignados e furiosos, porque Siquém tinha cometido uma infâmia em Israel, deitando-se com a filha de Jacó — coisa que não se faz."),
      V(8, "Hamor falou com eles: “O coração do meu filho Siquém está apaixonado pela filha de vocês. Por favor, deem-na a ele como mulher."),
      V(9, "Aparentem-se conosco: deem-nos as suas filhas e tomem as nossas para vocês."),
      V(10, "Morem conosco. A terra está aberta diante de vocês: habitem nela, negociem e adquiram propriedades.”"),
      V(11, "Siquém disse ao pai e aos irmãos de Diná: “Que eu encontre favor aos olhos de vocês, e darei o que me pedirem."),
      V(12, "Peçam um preço alto e presentes valiosos: pagarei tudo o que pedirem. Somente deem-me a jovem como mulher.”"),
    ]},
    {"verses": [
      V(13, "Os filhos de Jacó responderam a Siquém e a Hamor, o pai dele, com falsidade, porque ele tinha desonrado Diná, a irmã deles."),
      V(14, "Disseram: “Não podemos fazer isso: dar a nossa irmã a um homem incircunciso, porque isso seria uma vergonha para nós."),
      V(15, "Só aceitaremos com uma condição: que vocês se tornem como nós, circuncidando todos os homens."),
      V(16, "Então daremos as nossas filhas a vocês e tomaremos as filhas de vocês para nós; moraremos com vocês e seremos um só povo."),
      V(17, "Mas, se não nos ouvirem e não se circuncidarem, tomaremos a nossa irmã e iremos embora.”"),
      V(18, "A proposta agradou a Hamor e a Siquém, filho de Hamor."),
      V(19, "O jovem não demorou a fazer o que foi pedido, porque amava a filha de Jacó — e ele era o mais respeitado de toda a casa do seu pai."),
      V(20, "Hamor e Siquém, seu filho, foram à porta da cidade e falaram aos homens da cidade:"),
      V(21, "“Esses homens são pacíficos. Deixem que morem na nossa terra e negociem nela; a terra tem espaço de sobra para eles. Casaremos com as filhas deles e daremos as nossas filhas a eles."),
      V(22, "Mas só com uma condição eles aceitam morar conosco e formar um só povo: que todos os nossos homens se circuncidem, como eles são circuncidados."),
      V(23, "Os rebanhos, os bens e todos os animais deles não serão nossos? Vamos aceitar a condição, e eles morarão conosco.”"),
      V(24, "Todos os que passavam pela porta da cidade concordaram com Hamor e Siquém, seu filho; e todos os homens da cidade foram circuncidados."),
      V(25, "No terceiro dia, quando os homens ainda sofriam com as dores, dois filhos de Jacó — Simeão e Levi, irmãos de Diná — pegaram as espadas, entraram na cidade desprevenida e mataram todos os homens."),
      V(26, "Mataram também Hamor e Siquém, o filho dele, ao fio da espada, tomaram Diná da casa de Siquém e foram embora."),
      V(27, "Os outros filhos de Jacó vieram sobre os mortos e saquearam a cidade, porque a irmã deles tinha sido desonrada."),
      V(28, "Levaram as ovelhas, o gado, os jumentos, tudo o que havia na cidade e no campo,"),
      V(29, "todos os bens, todas as crianças e as mulheres; e saquearam tudo o que havia nas casas."),
      V(30, "Jacó disse a Simeão e a Levi: “Vocês me arruinaram, fazendo com que eu seja odiado pelos cananeus e ferezeus, moradores desta terra! Eu tenho poucos homens. Se eles se juntarem contra mim e me atacarem, serei destruído, eu e a minha casa!”"),
      V(31, "Mas eles responderam: “Ele trataria a nossa irmã como uma prostituta?”"),
    ]},
  ],
}

CH["35"] = {
  "verses": 29,
  "summary": "Deus manda Jacó voltar a Betel e renova a promessa e o novo nome. No caminho, morrem Débora e Raquel, ao dar à luz Benjamim. Isaque também morre, e os gêmeos o sepultam.",
  "sections": [
    {"title": "O retorno a Betel", "start": 1},
    {"title": "A morte de Raquel", "start": 16},
    {"title": "A morte de Isaque", "start": 27},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Deus disse a Jacó: “Levante-se, suba a Betel e more ali. Construa um altar ao Deus que apareceu a você quando fugia do seu irmão Esaú.”"),
      V(2, "Jacó disse à sua família e a todos os que estavam com ele: “Joguem fora os deuses estrangeiros que há entre vocês, purifiquem-se e troquem de roupas."),
      V(3, "Vamos subir a Betel. Ali construirei um altar ao Deus que me respondeu no dia da minha angústia e esteve comigo por onde andei.”"),
      V(4, "Eles entregaram a Jacó todos os deuses estrangeiros que tinham e os brincos que usavam nas orelhas. Jacó os enterrou debaixo do carvalho que ficava perto de Siquém."),
      V(5, "Quando partiram, um terror vindo de Deus caiu sobre as cidades ao redor, de modo que ninguém perseguiu os filhos de Jacó."),
      V(6, "Jacó chegou a Luz, que é Betel, na terra de Canaã, com todo o povo que estava com ele."),
      V(7, "Ali construiu um altar e chamou o lugar de El-Betel — “o Deus de Betel” —, porque foi ali que Deus tinha se revelado a ele, quando fugia do irmão."),
      V(8, "Débora, a ama de Rebeca, morreu e foi sepultada perto de Betel, debaixo do carvalho que foi chamado de Alom-Bacute — “carvalho do choro”."),
      V(9, "Depois que Jacó voltou de Padã-Arã, Deus apareceu a ele outra vez e o abençoou."),
      V(10, "Deus lhe disse: “O seu nome é Jacó. Mas você não será mais chamado Jacó: o seu nome será Israel.” E o chamou de Israel."),
      V(11, "Deus continuou: “Eu sou o Deus Todo-Poderoso. Seja fértil e se multiplique. De você sairão uma nação e uma comunidade de nações, e reis sairão dos seus lombos."),
      V(12, "A terra que dei a Abraão e a Isaque, dou a você; e à sua descendência depois de você, dou esta terra.”"),
      V(13, "Então Deus subiu do lugar onde tinha falado com ele."),
      V(14, "Jacó ergueu uma coluna de pedra no lugar onde Deus tinha falado com ele, derramou sobre ela uma oferta de bebida e a ungiu com azeite."),
      V(15, "E chamou de Betel o lugar onde Deus tinha falado com ele."),
    ]},
    {"verses": [
      V(16, "Eles partiram de Betel. Quando faltava ainda um pouco para chegar a Efrata, Raquel entrou em trabalho de parto, e o parto foi muito difícil."),
      V(17, "Enquanto sofria, a parteira lhe disse: “Não tenha medo, porque você terá outro filho.”"),
      V(18, "Quando ela estava morrendo — pois estava perdendo a vida —, chamou o menino de Benoni — “filho da minha dor” —, mas o pai o chamou de Benjamim — “filho da mão direita”."),
      V(19, "Raquel morreu e foi sepultada no caminho de Efrata, que é Belém."),
      V(20, "Jacó ergueu uma coluna sobre a sepultura dela; é a coluna da sepultura de Raquel, que existe até hoje."),
      V(21, "Israel partiu dali e armou a sua tenda além de Migdal-Éder."),
      V(22, "Enquanto Israel morava naquela terra, Rúben se deitou com Bila, concubina do seu pai. E Israel ficou sabendo. Os filhos de Jacó eram doze:"),
      V(23, "os filhos de Lia: Rúben, o primogênito de Jacó, Simeão, Levi, Judá, Issacar e Zebulom."),
      V(24, "Os filhos de Raquel: José e Benjamim."),
      V(25, "Os filhos de Bila, serva de Raquel: Dã e Naftali."),
      V(26, "Os filhos de Zilpa, serva de Lia: Gade e Aser. Esses foram os filhos de Jacó, que nasceram em Padã-Arã."),
    ]},
    {"verses": [
      V(27, "Jacó chegou à casa de Isaque, seu pai, em Manre, perto de Quiriate-Arba, que é Hebrom, onde Abraão e Isaque tinham morado como estrangeiros."),
      V(28, "Isaque viveu cento e oitenta anos."),
      V(29, "Morreu e foi reunido ao seu povo, velho e farto de dias. Esaú e Jacó, seus filhos, o sepultaram."),
    ]},
  ],
}

CH["36"] = {
  "verses": 43,
  "summary": "A genealogia de Esaú, pai dos edomitas, lista seus descendentes, os chefes de Edom e os reis que reinaram antes de haver rei em Israel.",
  "sections": [
    {"title": "Os descendentes de Esaú", "start": 1},
    {"title": "Os chefes de Edom", "start": 20},
    {"title": "Os reis de Edom", "start": 31},
  ],
  "paragraphs": [
    {"verses": [
      V(1, "Estes são os descendentes de Esaú, que é Edom."),
      V(2, "Esaú se casou com mulheres de Canaã: Ada, filha de Elom, o heteu; Oolibama, filha de Aná e neta de Zibeão, o heveu;"),
      V(3, "e Basemate, filha de Ismael e irmã de Nebaiote."),
      V(4, "Ada deu a Esaú Elifaz; Basemate deu Reuel;"),
      V(5, "e Oolibama deu Jeús, Jalão e Corá. Esses foram os filhos de Esaú, que nasceram na terra de Canaã."),
      V(6, "Esaú tomou as suas mulheres, os seus filhos e filhas e todas as pessoas da sua casa, os rebanhos, todos os animais e todos os bens que tinha acumulado na terra de Canaã, e partiu para outra terra, afastando-se de Jacó, seu irmão."),
      V(7, "Os bens deles eram grandes demais para morarem juntos; a terra onde moravam como estrangeiros não dava conta dos rebanhos deles."),
      V(8, "Por isso Esaú, que é Edom, passou a morar nos montes de Seir."),
      V(9, "Estes são os descendentes de Esaú, pai dos edomitas, nos montes de Seir."),
      V(10, "Os nomes dos filhos de Esaú: Elifaz, filho de Ada, mulher de Esaú; e Reuel, filho de Basemate, mulher de Esaú."),
      V(11, "Os filhos de Elifaz: Temã, Omar, Zefô, Gaetã e Quenaz."),
      V(12, "Elifaz, filho de Esaú, tinha uma concubina chamada Timna, que lhe deu Amaleque. Esses foram os descendentes de Ada, mulher de Esaú."),
      V(13, "Os filhos de Reuel: Naate, Zerá, Samá e Mizá. Esses foram os descendentes de Basemate, mulher de Esaú."),
      V(14, "Os filhos de Oolibama, filha de Aná e neta de Zibeão, mulher de Esaú: Jeús, Jalão e Corá."),
      V(15, "Estes são os chefes das tribos dos filhos de Esaú. Os filhos de Elifaz, o primogênito de Esaú: os chefes Temã, Omar, Zefô, Quenaz,"),
      V(16, "Corá, Gaetã e Amaleque. Esses foram os chefes de Elifaz, na terra de Edom; são os descendentes de Ada."),
      V(17, "Os filhos de Reuel, filho de Esaú: os chefes Naate, Zerá, Samá e Mizá. Esses foram os chefes de Reuel, na terra de Edom; são os descendentes de Basemate, mulher de Esaú."),
      V(18, "Os filhos de Oolibama, mulher de Esaú: os chefes Jeús, Jalão e Corá. Esses foram os chefes de Oolibama, filha de Aná, mulher de Esaú."),
      V(19, "Esses foram os filhos de Esaú, que é Edom, e esses os chefes deles."),
    ]},
    {"verses": [
      V(20, "Estes são os filhos de Seir, o horeu, que morava naquela terra: Lotã, Sobal, Zibeão, Aná,"),
      V(21, "Disom, Éser e Disã. Esses foram os chefes dos horeus, filhos de Seir, na terra de Edom."),
      V(22, "Os filhos de Lotã: Hori e Homã. A irmã de Lotã era Timna."),
      V(23, "Os filhos de Sobal: Alvã, Manaate, Ebal, Sefô e Onã."),
      V(24, "Os filhos de Zibeão: Aiá e Aná. Foi Aná que achou as fontes termais no deserto, quando pastoreava os jumentos de Zibeão, seu pai."),
      V(25, "Os filhos de Aná: Disom e Oolibama, filha de Aná."),
      V(26, "Os filhos de Disom: Hendã, Esbã, Itrã e Querã."),
      V(27, "Os filhos de Éser: Bilã, Zaavã e Acã."),
      V(28, "Os filhos de Disã: Uz e Arã."),
      V(29, "Estes foram os chefes dos horeus: Lotã, Sobal, Zibeão, Aná,"),
      V(30, "Disom, Éser e Disã. Esses foram os chefes dos horeus, segundo as suas tribos, na terra de Seir."),
    ]},
    {"verses": [
      V(31, "Estes foram os reis que reinaram na terra de Edom, antes de haver rei sobre os israelitas:"),
      V(32, "Belá, filho de Beor, reinou em Edom; a cidade dele se chamava Dinabá."),
      V(33, "Belá morreu, e reinou em seu lugar Jobabe, filho de Zerá, de Bozra."),
      V(34, "Jobabe morreu, e reinou em seu lugar Husão, da terra dos temanitas."),
      V(35, "Husão morreu, e reinou em seu lugar Hadade, filho de Bedade, que derrotou os midianitas no campo de Moabe; a cidade dele se chamava Avite."),
      V(36, "Hadade morreu, e reinou em seu lugar Samlá, de Masreca."),
      V(37, "Samlá morreu, e reinou em seu lugar Saul, de Reobote, que fica junto ao rio."),
      V(38, "Saul morreu, e reinou em seu lugar Baal-Hanã, filho de Acbor."),
      V(39, "Baal-Hanã, filho de Acbor, morreu, e reinou em seu lugar Hadar; a cidade dele se chamava Paú, e a mulher dele se chamava Meetabel, filha de Matrede e neta de Me-Zaabe."),
      V(40, "Estes são os nomes dos chefes de Esaú, segundo as suas famílias, lugares e nomes: Timna, Alvá, Jetete,"),
      V(41, "Oolibama, Elá, Pinom,"),
      V(42, "Quenaz, Temã, Mibzar,"),
      V(43, "Magdiel e Irã. Esses foram os chefes de Edom, segundo as suas moradas, na terra que possuíram. Esaú é o pai dos edomitas."),
    ]},
  ],
}

out = os.path.join(os.path.dirname(__file__), "..", "data", "books", "gn", "18-36.json")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    json.dump({"book": "gn", "chapters": CH}, f, ensure_ascii=False, indent=2)

total = sum(ch["verses"] for ch in CH.values())
print(f"Parte 2 OK: capítulos 18-36, {total} versículos -> {out}")
