// Introduções de cada livro da Bíblia: autor, data, contexto histórico e cultural,
// tema central, versículo-chave e curiosidades. Chave = abbrev normalizada.
// Conteúdo em perspectiva histórico-tradicional, para fins educativos e devocionais.

export const INTROS = {
  gn: {
    autor: 'Tradicionalmente atribuído a Moisés',
    data: 'c. 1445–1405 a.C. (narrando desde a criação)',
    periodo: 'Origens — da criação aos patriarcas',
    tema: 'As origens de tudo: o mundo, o pecado e a aliança de Deus com um povo.',
    contexto: 'Gênesis abre a Torá narrando a criação, a queda, o dilúvio e a história dos patriarcas Abraão, Isaque, Jacó e José. Foi escrito para Israel recém-saído do Egito, para lhe dar identidade e mostrar que o Deus que os libertou é o mesmo Criador de todas as coisas.',
    cultura: 'O cenário é o antigo Oriente Próximo, entre a Mesopotâmia (Ur dos caldeus) e o Egito. A vida girava em torno de clãs seminômades, pastoreio, hospitalidade sagrada e alianças seladas com sacrifícios — costumes que iluminam a promessa feita a Abraão.',
    versiculo: 'No princípio, Deus criou os céus e a terra. (Gênesis 1:1)',
    curiosidade: 'A palavra "Gênesis" vem do grego e significa "origem". Em hebraico, o livro é chamado "Bereshith" — "No princípio", suas primeiras palavras.',
  },
  ex: {
    autor: 'Tradicionalmente atribuído a Moisés',
    data: 'c. 1445–1405 a.C.',
    periodo: 'Escravidão e êxodo do Egito',
    tema: 'A redenção de Israel: Deus liberta seu povo e faz aliança com ele no Sinai.',
    contexto: 'Êxodo narra a escravidão no Egito, o chamado de Moisés, as dez pragas, a Páscoa, a travessia do Mar Vermelho e a entrega da Lei no monte Sinai. É o evento fundador da nação de Israel.',
    cultura: 'O Egito do Império Novo era a superpotência da época, com o faraó tido como divino. A libertação de escravos por um Deus estrangeiro era um escândalo teológico — as pragas atingem diretamente os deuses egípcios (o Nilo, o sol, o gado).',
    versiculo: 'Eu sou o Senhor, o vosso Deus, que vos tirei da terra do Egito. (Êxodo 20:2)',
    curiosidade: 'A Páscoa (Pessach) celebrada até hoje pelos judeus tem origem direta na noite da libertação descrita em Êxodo 12.',
  },
  lv: {
    autor: 'Tradicionalmente atribuído a Moisés',
    data: 'c. 1445–1405 a.C.',
    periodo: 'No Sinai, após o êxodo',
    tema: 'Santidade: como um povo pecador pode se aproximar de um Deus santo.',
    contexto: 'Levítico reúne as leis dos sacrifícios, do sacerdócio, da pureza e das festas. Seu nome vem da tribo de Levi, responsável pelo culto. É o manual de adoração de Israel.',
    cultura: 'No mundo antigo, aproximar-se do sagrado exigia rituais precisos. Levítico regula alimentação, higiene, moral e culto — distinguindo Israel das nações vizinhas e ensinando que a fé abrange toda a vida.',
    versiculo: 'Sereis santos, porque eu, o Senhor, vosso Deus, sou santo. (Levítico 19:2)',
    curiosidade: 'O Dia da Expiação (Yom Kippur), a data mais solene do calendário judaico, é instituído em Levítico 16.',
  },
  nm: {
    autor: 'Tradicionalmente atribuído a Moisés',
    data: 'c. 1445–1405 a.C.',
    periodo: 'Os 40 anos no deserto',
    tema: 'A peregrinação: a fidelidade de Deus apesar da incredulidade do povo.',
    contexto: 'Números acompanha Israel do Sinai às fronteiras da Terra Prometida. Após recusarem entrar por medo, uma geração inteira vaga 40 anos no deserto até que uma nova geração se levante.',
    cultura: 'O nome vem dos dois censos militares do povo. A vida no deserto — água, maná, tendas, marchas — molda uma nação. Os episódios da serpente de bronze e de Balaão marcam o livro.',
    versiculo: 'O Senhor te abençoe e te guarde. (Números 6:24)',
    curiosidade: 'A "bênção sacerdotal" de Números 6:24-26 é uma das passagens bíblicas mais antigas já encontradas em arqueologia, gravada em amuletos de prata do séc. VII a.C.',
  },
  dt: {
    autor: 'Tradicionalmente atribuído a Moisés',
    data: 'c. 1405 a.C.',
    periodo: 'Vésperas da entrada em Canaã',
    tema: 'Aliança renovada: "ama o Senhor teu Deus de todo o coração".',
    contexto: 'Deuteronômio são os discursos finais de Moisés, relembrando a Lei a uma nova geração antes de entrar na Terra Prometida. É um chamado à obediência de amor e à escolha entre a vida e a morte.',
    cultura: 'Sua estrutura imita os tratados de aliança dos reis do Oriente Próximo (suserano e vassalo), reforçando o compromisso exclusivo de Israel com o seu Deus.',
    versiculo: 'Amarás o Senhor, teu Deus, de todo o teu coração. (Deuteronômio 6:5)',
    curiosidade: '"Deuteronômio" significa "segunda lei". Foi o livro mais citado por Jesus, inclusive nas tentações no deserto.',
  },
  js: {
    autor: 'Atribuído a Josué (com registros posteriores)',
    data: 'c. 1405–1380 a.C.',
    periodo: 'Conquista de Canaã',
    tema: 'A fidelidade de Deus em cumprir suas promessas de dar a terra.',
    contexto: 'Josué narra a entrada de Israel em Canaã: a travessia do Jordão, a queda de Jericó, as campanhas de conquista e a divisão da terra entre as doze tribos.',
    cultura: 'Canaã era formada por cidades-estado fortificadas. As muralhas de Jericó e a tecnologia militar da Idade do Bronze compõem o pano de fundo. A conquista é apresentada como ato de Deus, não mérito humano.',
    versiculo: 'Sê forte e corajoso; não temas, nem te espantes. (Josué 1:9)',
    curiosidade: 'Josué é a forma hebraica do nome que, em grego, se torna "Jesus" — ambos significam "o Senhor salva".',
  },
  jz: {
    autor: 'Tradicionalmente atribuído a Samuel',
    data: 'c. 1043 a.C. (narrando c. 1380–1050 a.C.)',
    periodo: 'Entre a conquista e a monarquia',
    tema: 'O ciclo de pecado, opressão, clamor e libertação por juízes.',
    contexto: 'Juízes mostra Israel repetindo um ciclo trágico: abandona a Deus, é oprimido, clama e é resgatado por líderes como Débora, Gideão e Sansão. "Cada um fazia o que parecia reto aos seus olhos."',
    cultura: 'Sem rei nem governo central, as tribos viviam ameaçadas por filisteus, midianitas e cananeus. Os "juízes" eram libertadores militares carismáticos, não magistrados.',
    versiculo: 'Naqueles dias não havia rei em Israel; cada um fazia o que achava mais reto. (Juízes 21:25)',
    curiosidade: 'Débora é a única mulher juíza e profetisa a liderar Israel, comandando o exército ao lado de Baraque.',
  },
  rt: {
    autor: 'Tradicionalmente atribuído a Samuel',
    data: 'c. 1030 a.C. (ambientado no tempo dos juízes)',
    periodo: 'Época dos juízes',
    tema: 'Lealdade, redenção e a providência de Deus na vida comum.',
    contexto: 'Rute é uma moabita viúva que, por amor à sogra Noemi, adota o Deus de Israel. Sua história de fidelidade a leva a se casar com Boaz e a se tornar bisavó do rei Davi.',
    cultura: 'O livro ilustra a lei do "resgatador" (goel) e da respiga, que garantia sustento a pobres e viúvas. Mostra também a acolhida de uma estrangeira no povo de Deus.',
    versiculo: 'Onde quer que fores, irei eu; o teu povo é o meu povo, e o teu Deus é o meu Deus. (Rute 1:16)',
    curiosidade: 'Rute, uma estrangeira, aparece na genealogia de Jesus (Mateus 1), mostrando que o plano de Deus inclui todos os povos.',
  },
  '1sm': {
    autor: 'Samuel, com Natã e Gade',
    data: 'c. 930 a.C. (narrando c. 1100–1010 a.C.)',
    periodo: 'Transição dos juízes à monarquia',
    tema: 'Deus levanta líderes segundo o seu coração, não segundo a aparência.',
    contexto: '1 Samuel narra o nascimento da monarquia: o profeta Samuel, o fracasso do rei Saul e a ascensão do jovem Davi, ungido em segredo e vitorioso sobre o gigante Golias.',
    cultura: 'Israel exige um rei "como as outras nações", diante da ameaça filisteia — povo do mar com armas de ferro. O livro reflete a tensão entre o desejo humano de poder e a soberania de Deus.',
    versiculo: 'O Senhor não vê como vê o homem: o homem olha para o exterior, mas o Senhor olha para o coração. (1 Samuel 16:7)',
    curiosidade: 'O confronto entre Davi e Golias no vale de Elá é uma das cenas mais conhecidas de toda a Bíblia.',
  },
  '2sm': {
    autor: 'Registros de Natã e Gade',
    data: 'c. 930 a.C. (narrando c. 1010–970 a.C.)',
    periodo: 'Reinado de Davi',
    tema: 'A aliança de Deus com Davi e as consequências do pecado.',
    contexto: '2 Samuel relata o reinado de Davi: a conquista de Jerusalém, a promessa de um trono eterno, mas também seu pecado com Bate-Seba e as tragédias familiares que se seguem.',
    cultura: 'Davi transforma Jerusalém na capital política e religiosa, levando para lá a Arca. A "aliança davídica" torna-se base da esperança messiânica de Israel.',
    versiculo: 'A tua casa e o teu reino serão firmados para sempre diante de ti. (2 Samuel 7:16)',
    curiosidade: 'Apesar de suas falhas graves, Davi é chamado "homem segundo o coração de Deus" por seu arrependimento sincero.',
  },
  '1rs': {
    autor: 'Tradicionalmente atribuído a Jeremias',
    data: 'c. 560–540 a.C. (narrando c. 970–850 a.C.)',
    periodo: 'Auge e divisão do reino',
    tema: 'A sabedoria e a infidelidade: a glória de Salomão e a fratura do reino.',
    contexto: '1 Reis conta o reinado glorioso de Salomão, a construção do Templo, e como, após sua morte, o reino se divide em Israel (norte) e Judá (sul). Surge o profeta Elias contra a idolatria.',
    cultura: 'O Templo de Salomão torna-se o centro da fé de Israel. O comércio, as alianças e o luxo da corte marcam a era de ouro, seguida pelo declínio provocado pela idolatria.',
    versiculo: 'Dá, pois, ao teu servo um coração compreensivo para julgar o teu povo. (1 Reis 3:9)',
    curiosidade: 'O confronto de Elias com os profetas de Baal no monte Carmelo (1 Reis 18) é um dos duelos espirituais mais dramáticos da Bíblia.',
  },
  '2rs': {
    autor: 'Tradicionalmente atribuído a Jeremias',
    data: 'c. 560–540 a.C. (narrando c. 850–586 a.C.)',
    periodo: 'Declínio e queda dos dois reinos',
    tema: 'As consequências da infidelidade: o exílio como juízo anunciado.',
    contexto: '2 Reis segue os profetas Elias e Eliseu e narra a decadência dos dois reinos até a queda de Israel diante da Assíria (722 a.C.) e de Judá diante da Babilônia (586 a.C.), com a destruição de Jerusalém.',
    cultura: 'Os grandes impérios — Assíria e Babilônia — dominam a geopolítica. A deportação de povos era prática comum para enfraquecer nações conquistadas.',
    versiculo: 'Não houve outro rei semelhante a ele... que se convertesse ao Senhor de todo o coração. (2 Reis 23:25)',
    curiosidade: 'O rei Josias promoveu uma grande reforma ao redescobrir o "livro da Lei" durante reformas no Templo.',
  },
  '1cr': {
    autor: 'Tradicionalmente atribuído a Esdras',
    data: 'c. 450–430 a.C.',
    periodo: 'Após o exílio (revisitando a era de Davi)',
    tema: 'A identidade e a esperança de Israel restaurado, centradas em Davi e no culto.',
    contexto: '1 Crônicas recapitula a história desde Adão em genealogias e foca no reinado de Davi, com ênfase no culto e na preparação para o Templo. Foi escrito para os que voltaram do exílio.',
    cultura: 'Para o povo pós-exílico, sem rei e sob domínio estrangeiro, as genealogias reafirmavam quem eles eram e sua ligação com as promessas de Deus.',
    versiculo: 'Tua, Senhor, é a grandeza, o poder, a honra, a vitória e a majestade. (1 Crônicas 29:11)',
    curiosidade: 'As longas genealogias iniciais funcionavam como uma "certidão de identidade" nacional após a devastação do exílio.',
  },
  '2cr': {
    autor: 'Tradicionalmente atribuído a Esdras',
    data: 'c. 450–430 a.C.',
    periodo: 'De Salomão ao exílio',
    tema: 'O Templo, a adoração e os avivamentos como caminho de restauração.',
    contexto: '2 Crônicas relata a construção do Templo por Salomão e a história dos reis de Judá, destacando os avivamentos espirituais. Termina com o decreto de Ciro permitindo o retorno do exílio.',
    cultura: 'A obra realça o papel de Jerusalém e do Templo. Reis reformadores como Ezequias e Josias são modelos de fé para a comunidade restaurada.',
    versiculo: 'Se o meu povo... se humilhar, orar... eu ouvirei dos céus e sararei a sua terra. (2 Crônicas 7:14)',
    curiosidade: 'Na Bíblia hebraica, Crônicas é o último livro — encerrando o Antigo Testamento com a esperança do retorno.',
  },
  ed: {
    autor: 'Tradicionalmente atribuído a Esdras',
    data: 'c. 440 a.C.',
    periodo: 'Retorno do exílio babilônico',
    tema: 'A restauração do povo e a reconstrução do Templo e da fé.',
    contexto: 'Esdras narra o retorno dos judeus da Babilônia, a reconstrução do Templo e a reforma espiritual liderada pelo sacerdote-escriba Esdras, que reensina a Lei ao povo.',
    cultura: 'Sob o Império Persa, relativamente tolerante, os judeus puderam voltar e reconstruir. Esdras enfrenta oposição, casamentos mistos e o desafio de reconstruir a identidade religiosa.',
    versiculo: 'A boa mão do seu Deus estava sobre ele. (Esdras 7:9)',
    curiosidade: 'Ciro, o rei persa, é citado como instrumento de Deus para libertar os judeus — cumprindo profecias de Isaías e Jeremias.',
  },
  ne: {
    autor: 'Neemias (com edição de Esdras)',
    data: 'c. 430 a.C.',
    periodo: 'Retorno do exílio babilônico',
    tema: 'Liderança, oração e ação: reconstruindo os muros e a comunidade.',
    contexto: 'Neemias, copeiro do rei persa, obtém permissão para reconstruir os muros de Jerusalém. Apesar da oposição, a obra é concluída em 52 dias, seguida de renovação espiritual.',
    cultura: 'Muros eram símbolo de segurança e dignidade. Neemias combina fé e planejamento prático, enfrentando inimigos como Sambalate e Tobias e reformando abusos sociais.',
    versiculo: 'A alegria do Senhor é a vossa força. (Neemias 8:10)',
    curiosidade: 'Neemias é considerado um modelo clássico de liderança: ora, planeja, delega, persevera e presta contas.',
  },
  et: {
    autor: 'Desconhecido (talvez Mardoqueu)',
    data: 'c. 460–350 a.C.',
    periodo: 'Judeus na diáspora persa',
    tema: 'A providência oculta de Deus: preservando seu povo através de uma rainha corajosa.',
    contexto: 'Ester conta como uma jovem judia se torna rainha da Pérsia e arrisca a vida para impedir o extermínio de seu povo, arquitetado pelo perverso Hamã.',
    cultura: 'A história se passa na corte de Susã, no auge do Império Persa. Retrata banquetes, intrigas palacianas e o perigo de ser minoria em terra estrangeira.',
    versiculo: 'Quem sabe se para tempo como este chegaste ao reino? (Ester 4:14)',
    curiosidade: 'Ester é um dos dois livros bíblicos que não mencionam o nome de Deus — mas sua mão é vista em cada detalhe. Deu origem à festa judaica de Purim.',
  },
  'jó': {
    autor: 'Desconhecido (um dos livros mais antigos)',
    data: 'Incerta — possivelmente era patriarcal',
    periodo: 'Cenário muito antigo',
    tema: 'O sofrimento do justo e a soberania de Deus além da compreensão humana.',
    contexto: 'Jó é um homem justo que perde tudo — bens, filhos e saúde. O livro é um profundo debate poético sobre por que os justos sofrem, encerrado pela resposta de Deus a partir de um redemoinho.',
    cultura: 'Ambientado na terra de Uz, reflete a sabedoria do antigo Oriente. Os discursos dos amigos representam a teologia comum de que sofrimento é sempre castigo — visão que o livro contesta.',
    versiculo: 'Eu sei que o meu Redentor vive. (Jó 19:25)',
    curiosidade: 'Grande parte de Jó é escrita em poesia hebraica sofisticada, sendo considerada uma obra-prima literária mundial.',
  },
  sl: {
    autor: 'Davi e outros (Asafe, filhos de Corá, Salomão, Moisés)',
    data: 'c. 1440–450 a.C. (compilado ao longo de séculos)',
    periodo: 'Diversas épocas de Israel',
    tema: 'Louvor, lamento e oração: o coração humano diante de Deus em toda emoção.',
    contexto: 'Os Salmos são o cancioneiro de Israel: 150 poemas de louvor, gratidão, arrependimento, angústia e esperança. Foram usados no culto do Templo e na devoção pessoal.',
    cultura: 'Cantados com instrumentos como harpa e lira, os salmos acompanhavam festas, peregrinações e o culto diário. Muitos têm indicações musicais em seus títulos.',
    versiculo: 'O Senhor é o meu pastor; nada me faltará. (Salmos 23:1)',
    curiosidade: 'O Salmo 119, com 176 versículos, é o capítulo mais longo da Bíblia — um poema alfabético em louvor à Palavra de Deus.',
  },
  pv: {
    autor: 'Salomão (principalmente) e outros sábios',
    data: 'c. 970–700 a.C.',
    periodo: 'Monarquia de Israel',
    tema: 'Sabedoria prática: o temor do Senhor é o princípio do conhecimento.',
    contexto: 'Provérbios reúne ditados sábios sobre a vida cotidiana — trabalho, palavras, dinheiro, amizade, família — ensinando a viver com prudência e integridade diante de Deus.',
    cultura: 'A literatura de sabedoria era comum no Oriente Próximo (Egito, Mesopotâmia). Provérbios se distingue por ancorar toda sabedoria no "temor do Senhor".',
    versiculo: 'O temor do Senhor é o princípio da sabedoria. (Provérbios 9:10)',
    curiosidade: 'O capítulo 31 descreve a "mulher virtuosa", um poema alfabético que celebra a força e a sabedoria feminina.',
  },
  ec: {
    autor: 'Tradicionalmente atribuído a Salomão ("o Pregador")',
    data: 'c. 940 a.C.',
    periodo: 'Monarquia de Israel',
    tema: 'O sentido da vida: tudo é vaidade sem Deus.',
    contexto: 'Eclesiastes é a reflexão de um sábio que experimentou riqueza, prazer e conhecimento, e conclui que tudo é passageiro ("vaidade") — só faz sentido viver no temor de Deus.',
    cultura: 'A palavra hebraica "hevel" (vaidade) significa "sopro, vapor" — algo fugaz. O livro dialoga com o ceticismo e a busca humana por significado, tão atual hoje.',
    versiculo: 'Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu. (Eclesiastes 3:1)',
    curiosidade: 'O poema "para tudo há um tempo" (cap. 3) é um dos textos bíblicos mais citados na cultura e na música.',
  },
  ct: {
    autor: 'Tradicionalmente atribuído a Salomão',
    data: 'c. 960 a.C.',
    periodo: 'Monarquia de Israel',
    tema: 'A beleza do amor conjugal, celebrado como dádiva de Deus.',
    contexto: 'Cânticos (Cantares de Salomão) é um poema de amor entre um noivo e uma noiva, celebrando o desejo, a fidelidade e a beleza do relacionamento. Tradicionalmente lido também como alegoria do amor entre Deus e seu povo.',
    cultura: 'A poesia amorosa era um gênero conhecido no antigo Oriente. O livro usa imagens da natureza — jardins, vinhas, especiarias — para exaltar a intimidade.',
    versiculo: 'Eu sou do meu amado, e o meu amado é meu. (Cânticos 6:3)',
    curiosidade: 'É um dos poucos livros da Bíblia inteiramente dedicado ao amor romântico entre um homem e uma mulher.',
  },

  is: {
    autor: 'Profeta Isaías',
    data: 'c. 740–680 a.C.',
    periodo: 'Reino de Judá, ameaça assíria',
    tema: 'Juízo e salvação: o Santo de Israel julga, mas envia um Redentor.',
    contexto: 'Isaías profetiza em Jerusalém durante crises políticas e a ameaça da Assíria. Denuncia a hipocrisia religiosa, anuncia juízo, mas também promete consolo, restauração e a vinda do Messias e do Servo Sofredor.',
    cultura: 'A Judá de Isaías vivia entre alianças perigosas e idolatria. Suas imagens de tribunal, vinha e servo refletem a vida agrária e jurídica da época.',
    versiculo: 'Um menino nos nasceu, um filho se nos deu... Príncipe da Paz. (Isaías 9:6)',
    curiosidade: 'Isaías 53, sobre o Servo Sofredor, é uma das profecias messiânicas mais citadas no Novo Testamento. Um rolo quase completo de Isaías foi achado entre os Manuscritos do Mar Morto.',
  },
  jr: {
    autor: 'Profeta Jeremias (com o escriba Baruque)',
    data: 'c. 626–580 a.C.',
    periodo: 'Últimos dias de Judá e o exílio',
    tema: 'Fidelidade em tempos de colapso e a promessa de uma nova aliança.',
    contexto: 'Jeremias, o "profeta chorão", anuncia por 40 anos a queda de Jerusalém diante da Babilônia. Rejeitado e perseguido, mantém a fidelidade e proclama uma nova aliança escrita no coração.',
    cultura: 'Judá vivia seus estertores, dividida entre facções pró-Egito e pró-Babilônia. Jeremias usa gestos simbólicos (jugo, cinto, vasos de barro) típicos do ministério profético.',
    versiculo: 'Eu sei os planos que tenho para vós: planos de paz e não de mal. (Jeremias 29:11)',
    curiosidade: 'Jeremias comprou um campo enquanto a cidade caía — um ato profético de esperança de que o povo um dia voltaria à terra.',
  },
  lm: {
    autor: 'Tradicionalmente atribuído a Jeremias',
    data: 'c. 586 a.C.',
    periodo: 'Logo após a queda de Jerusalém',
    tema: 'Lamento pela destruição, mas com esperança nas misericórdias de Deus.',
    contexto: 'Lamentações são cinco poemas de luto pela destruição de Jerusalém e do Templo pela Babilônia. Em meio à dor, brilha a certeza de que a compaixão de Deus se renova a cada manhã.',
    cultura: 'É uma "elegia" (canto fúnebre) no estilo poético hebraico. Quatro dos cinco poemas são acrósticos alfabéticos, dando forma e contenção à dor.',
    versiculo: 'As misericórdias do Senhor são a causa de não sermos consumidos; renovam-se cada manhã. (Lamentações 3:22-23)',
    curiosidade: 'É lido pelos judeus no Tishá b\'Av, dia de jejum que lembra a destruição dos dois Templos de Jerusalém.',
  },
  ez: {
    autor: 'Profeta Ezequiel',
    data: 'c. 593–571 a.C.',
    periodo: 'Exílio na Babilônia',
    tema: 'A glória de Deus e a promessa de um coração novo para um povo renovado.',
    contexto: 'Ezequiel, sacerdote exilado, profetiza aos judeus na Babilônia através de visões extraordinárias — as criaturas viventes, o vale de ossos secos, o novo Templo — anunciando juízo e depois restauração.',
    cultura: 'Escrito longe da terra natal, o livro reafirma que Deus está presente também no exílio. Suas visões grandiosas e atos simbólicos são marcas do seu ministério.',
    versiculo: 'Dar-vos-ei um coração novo e porei dentro de vós um espírito novo. (Ezequiel 36:26)',
    curiosidade: 'A visão do vale de ossos secos ganhando vida (cap. 37) é uma poderosa imagem de ressurreição nacional e esperança.',
  },
  dn: {
    autor: 'Profeta Daniel',
    data: 'c. 605–530 a.C.',
    periodo: 'Exílio na Babilônia e Pérsia',
    tema: 'A soberania de Deus sobre os impérios e a fidelidade sob pressão.',
    contexto: 'Daniel, jovem exilado, ascende nas cortes da Babilônia e da Pérsia mantendo firme sua fé. O livro combina histórias de fidelidade (a fornalha, a cova dos leões) com visões proféticas sobre o futuro.',
    cultura: 'Retrata a vida na corte dos maiores impérios da época. Sua segunda metade é literatura apocalíptica, cheia de símbolos sobre reinos que se sucedem até o reino eterno de Deus.',
    versiculo: 'O Deus a quem servimos é que nos pode livrar. (Daniel 3:17)',
    curiosidade: 'A cena dos três amigos na fornalha ardente e Daniel na cova dos leões estão entre as histórias mais conhecidas da Bíblia.',
  },
  os: {
    autor: 'Profeta Oséias',
    data: 'c. 755–715 a.C.',
    periodo: 'Reino do Norte (Israel), antes de sua queda',
    tema: 'O amor fiel de Deus por um povo infiel.',
    contexto: 'Oséias recebe a ordem de se casar com uma mulher infiel, Gômer, como retrato vivo do relacionamento entre Deus e Israel — que o traía com a idolatria, mas continuava amado e buscado.',
    cultura: 'No próspero mas corrupto Reino do Norte, o culto a Baal misturava religião e fertilidade. A metáfora do casamento tinha enorme força cultural e emocional.',
    versiculo: 'Eu quero misericórdia, e não sacrifício. (Oséias 6:6)',
    curiosidade: 'A vida familiar do próprio profeta se torna uma parábola encenada da fidelidade divina.',
  },
  jl: {
    autor: 'Profeta Joel',
    data: 'Incerta (c. 835–500 a.C.)',
    periodo: 'Reino de Judá',
    tema: 'O Dia do Senhor e a promessa do derramamento do Espírito.',
    contexto: 'Joel usa uma devastadora praga de gafanhotos como imagem do juízo divino e chama o povo ao arrependimento, prometendo restauração e o derramamento do Espírito de Deus sobre toda a humanidade.',
    cultura: 'Numa sociedade agrária, uma praga de gafanhotos era catástrofe total. O profeta transforma o desastre em chamado espiritual urgente.',
    versiculo: 'Derramarei o meu Espírito sobre toda a carne. (Joel 2:28)',
    curiosidade: 'Pedro cita Joel no dia de Pentecostes (Atos 2), aplicando a profecia ao nascimento da Igreja.',
  },
  am: {
    autor: 'Profeta Amós',
    data: 'c. 760–750 a.C.',
    periodo: 'Reino do Norte (Israel), auge econômico',
    tema: 'Justiça social: a verdadeira religião se prova no cuidado com o oprimido.',
    contexto: 'Amós, um pastor de Tecoa, é enviado ao próspero Reino do Norte para denunciar a exploração dos pobres e a hipocrisia religiosa, anunciando juízo sobre a injustiça.',
    cultura: 'Israel vivia prosperidade material, mas com desigualdade escandalosa. Amós confronta os ricos que uniam culto religioso e opressão dos necessitados.',
    versiculo: 'Corra o juízo como as águas, e a justiça como ribeiro perene. (Amós 5:24)',
    curiosidade: 'Amós era um agricultor comum, não um profeta profissional — prova de que Deus chama pessoas simples para grandes missões.',
  },
  ob: {
    autor: 'Profeta Obadias',
    data: 'c. 586 a.C.',
    periodo: 'Após a queda de Jerusalém',
    tema: 'O orgulho precede a queda; Deus julga a arrogância das nações.',
    contexto: 'O menor livro do Antigo Testamento (um só capítulo) condena Edom por se alegrar com a destruição de Jerusalém e por trair Judá, anunciando sua ruína.',
    cultura: 'Edom, descendente de Esaú, era vizinho e rival histórico de Israel. Suas cidades escavadas na rocha (como Petra) davam falsa sensação de invencibilidade.',
    versiculo: 'A soberba do teu coração te enganou. (Obadias 1:3)',
    curiosidade: 'Com apenas 21 versículos, é o livro mais curto do Antigo Testamento.',
  },
  jn: {
    autor: 'Profeta Jonas',
    data: 'c. 780–760 a.C.',
    periodo: 'Reino do Norte (Israel)',
    tema: 'A misericórdia de Deus alcança até os inimigos.',
    contexto: 'Jonas foge do chamado de Deus para pregar a Nínive, capital da temida Assíria. Engolido por um grande peixe, arrepende-se e prega — e a cidade inteira se converte, para desgosto do próprio profeta.',
    cultura: 'Nínive era símbolo de crueldade e opressão. A história desafia o preconceito de que a graça de Deus seria só para Israel.',
    versiculo: 'E não pouparei eu a Nínive, aquela grande cidade? (Jonas 4:11)',
    curiosidade: 'Jesus comparou seus três dias no túmulo aos três dias de Jonas no ventre do peixe ("o sinal de Jonas").',
  },
  mq: {
    autor: 'Profeta Miquéias',
    data: 'c. 735–700 a.C.',
    periodo: 'Reinos de Judá e Israel',
    tema: 'Justiça, misericórdia e humildade diante de Deus.',
    contexto: 'Miquéias, do interior de Judá, denuncia a corrupção dos líderes e a exploração dos pobres, mas anuncia esperança: um governante nasceria em Belém para pastorear o povo.',
    cultura: 'Contemporâneo de Isaías, fala em nome do povo do campo contra os abusos das elites urbanas de Jerusalém e Samaria.',
    versiculo: 'Que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus. (Miquéias 6:8)',
    curiosidade: 'Miquéias 5:2 profetizou Belém como local do nascimento do Messias, séculos antes de Jesus.',
  },
  na: {
    autor: 'Profeta Naum',
    data: 'c. 663–612 a.C.',
    periodo: 'Reino de Judá',
    tema: 'Deus é justo: nenhum império opressor fica impune para sempre.',
    contexto: 'Naum anuncia a queda de Nínive, cerca de um século após seu arrependimento no tempo de Jonas. A Assíria voltara à crueldade, e Deus decreta seu fim.',
    cultura: 'A Assíria era a superpotência mais temida por sua brutalidade. Para os pequenos reinos oprimidos, a mensagem de Naum era de alívio e justiça.',
    versiculo: 'O Senhor é bom, uma fortaleza no dia da angústia. (Naum 1:7)',
    curiosidade: 'Nínive caiu em 612 a.C., exatamente como Naum previu — e foi tão destruída que virou lenda por séculos.',
  },
  hc: {
    autor: 'Profeta Habacuque',
    data: 'c. 610–605 a.C.',
    periodo: 'Reino de Judá, ascensão babilônica',
    tema: 'Viver pela fé mesmo sem entender os caminhos de Deus.',
    contexto: 'Habacuque dialoga diretamente com Deus, questionando por que a maldade prospera e por que Deus usaria a cruel Babilônia para julgar Judá. Termina confiando, mesmo sem respostas completas.',
    cultura: 'O livro tem forma de diálogo e encerra com um salmo. Reflete a angústia de um crente diante do mal e da soberania divina.',
    versiculo: 'O justo viverá pela sua fé. (Habacuque 2:4)',
    curiosidade: '"O justo viverá pela fé" tornou-se o versículo-chave da Reforma Protestante, citado por Paulo em Romanos e Gálatas.',
  },
  sf: {
    autor: 'Profeta Sofonias',
    data: 'c. 640–620 a.C.',
    periodo: 'Reino de Judá, antes da reforma de Josias',
    tema: 'O Dia do Senhor: juízo sobre o pecado e alegria para o remanescente fiel.',
    contexto: 'Sofonias anuncia o Dia do Senhor como juízo abrangente sobre Judá e as nações, mas conclui com uma das mais belas promessas de restauração e alegria de toda a Bíblia.',
    cultura: 'Provável descendente do rei Ezequias, escreveu às vésperas do avivamento do rei Josias. Combate a idolatria e a complacência.',
    versiculo: 'O Senhor... se regozijará em ti com alegria; renovar-te-á no seu amor. (Sofonias 3:17)',
    curiosidade: 'Termina com Deus "cantando" de alegria sobre o seu povo — uma imagem terna e única nas Escrituras.',
  },
  ag: {
    autor: 'Profeta Ageu',
    data: '520 a.C.',
    periodo: 'Após o retorno do exílio',
    tema: 'Prioridades certas: reconstruir a casa de Deus antes do conforto próprio.',
    contexto: 'Ageu exorta os judeus que voltaram do exílio a retomar a reconstrução do Templo, abandonada por 16 anos enquanto cuidavam de suas próprias casas. O povo obedece e a obra recomeça.',
    cultura: 'A comunidade pós-exílica era pequena e desanimada. Ageu conecta a negligência espiritual às dificuldades econômicas que enfrentavam.',
    versiculo: 'Considerai o vosso passado. (Ageu 1:7)',
    curiosidade: 'Suas mensagens são datadas com precisão de dia, mês e ano — algo raro entre os livros proféticos.',
  },
  zc: {
    autor: 'Profeta Zacarias',
    data: 'c. 520–480 a.C.',
    periodo: 'Após o retorno do exílio',
    tema: 'Encorajamento e esperança messiânica na reconstrução.',
    contexto: 'Contemporâneo de Ageu, Zacarias encoraja a reconstrução do Templo através de visões simbólicas e profecias claras sobre o Messias vindouro, o Rei humilde e o Bom Pastor.',
    cultura: 'A literatura de visões e anjos aponta para o estilo apocalíptico. O livro sustenta a esperança de um povo em reconstrução.',
    versiculo: 'Não por força, nem por poder, mas pelo meu Espírito, diz o Senhor. (Zacarias 4:6)',
    curiosidade: 'Zacarias contém muitas profecias cumpridas em Jesus, como a entrada em Jerusalém montado num jumento (9:9).',
  },
  ml: {
    autor: 'Profeta Malaquias',
    data: 'c. 430 a.C.',
    periodo: 'Fim do período do Antigo Testamento',
    tema: 'Fidelidade renovada e a promessa do mensageiro que prepararia o caminho.',
    contexto: 'Malaquias, o último profeta do Antigo Testamento, confronta a frieza espiritual, os sacrifícios de má qualidade e a infidelidade conjugal, prometendo o retorno de "Elias" antes do grande Dia do Senhor.',
    cultura: 'Um século após o retorno, o entusiasmo esfriara. O livro tem forma de disputa: Deus acusa, o povo se defende, Deus responde.',
    versiculo: 'Eis que eu vos envio o profeta Elias. (Malaquias 4:5)',
    curiosidade: 'Após Malaquias, seguem-se cerca de 400 anos de "silêncio profético" até a chegada de João Batista.',
  },

  mt: {
    autor: 'Mateus (Levi), apóstolo e ex-cobrador de impostos',
    data: 'c. 50–70 d.C.',
    periodo: 'Século I, sob domínio romano',
    tema: 'Jesus é o Messias prometido, o Rei dos judeus.',
    contexto: 'Mateus escreve principalmente para leitores judeus, mostrando como Jesus cumpre as profecias do Antigo Testamento. Organiza o ensino de Jesus em cinco grandes discursos, como o Sermão do Monte.',
    cultura: 'A Judeia vivia sob Roma, com expectativa messiânica intensa. Mateus dialoga com a tradição judaica, citando repetidamente as Escrituras hebraicas.',
    versiculo: 'Eis que estou convosco todos os dias, até à consumação dos séculos. (Mateus 28:20)',
    curiosidade: 'Só Mateus registra a visita dos magos do Oriente e a fuga da família de Jesus para o Egito.',
  },
  mc: {
    autor: 'João Marcos (baseado em Pedro)',
    data: 'c. 50–65 d.C.',
    periodo: 'Século I, sob domínio romano',
    tema: 'Jesus é o Servo Sofredor e Filho de Deus em ação.',
    contexto: 'O evangelho mais curto e ágil, provavelmente baseado nas lembranças de Pedro. Mostra Jesus em ação constante — milagres, confrontos e serviço — rumo à cruz e à ressurreição.',
    cultura: 'Escrito provavelmente em Roma para cristãos gentios sob perseguição, explica costumes judaicos e enfatiza coragem e discipulado no sofrimento.',
    versiculo: 'O Filho do Homem não veio para ser servido, mas para servir. (Marcos 10:45)',
    curiosidade: 'É considerado o primeiro evangelho escrito e a principal fonte usada por Mateus e Lucas.',
  },
  lc: {
    autor: 'Lucas, médico e companheiro de Paulo',
    data: 'c. 60–62 d.C.',
    periodo: 'Século I, sob domínio romano',
    tema: 'Jesus é o Salvador de todos: pobres, mulheres, pecadores e excluídos.',
    contexto: 'Lucas, o único autor gentio da Bíblia, faz uma pesquisa cuidadosa para escrever um relato ordenado da vida de Jesus, destacando sua compaixão pelos marginalizados e a alegria da salvação.',
    cultura: 'Dirigido ao mundo greco-romano, o evangelho tem estilo refinado e ênfase histórica. Realça o papel das mulheres e dos samaritanos, incomum para a época.',
    versiculo: 'O Filho do Homem veio buscar e salvar o que se havia perdido. (Lucas 19:10)',
    curiosidade: 'Só Lucas traz as parábolas do Filho Pródigo e do Bom Samaritano, e os cânticos de Maria e Zacarias.',
  },
  jo: {
    autor: 'João, apóstolo, "o discípulo amado"',
    data: 'c. 85–95 d.C.',
    periodo: 'Fim do século I',
    tema: 'Jesus é o Filho de Deus; crer nele é ter vida eterna.',
    contexto: 'O evangelho mais teológico e reflexivo. João seleciona sete sinais (milagres) e sete declarações "Eu Sou" para revelar a divindade de Jesus e conduzir o leitor à fé.',
    cultura: 'Escrito quando a Igreja já se distinguia do judaísmo, dialoga com o pensamento grego (o "Logos", a Palavra) e com a espiritualidade universal.',
    versiculo: 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito. (João 3:16)',
    curiosidade: 'João 3:16 é possivelmente o versículo mais conhecido de toda a Bíblia, resumindo o evangelho em uma frase.',
  },
  atos: {
    autor: 'Lucas, médico e companheiro de Paulo',
    data: 'c. 62–64 d.C.',
    periodo: 'Século I, nascimento da Igreja',
    tema: 'O Espírito Santo impulsiona a expansão do evangelho até os confins da terra.',
    contexto: 'Continuação do evangelho de Lucas, Atos narra o nascimento da Igreja em Pentecostes e sua expansão de Jerusalém a Roma, com destaque para Pedro e, sobretudo, Paulo e suas viagens missionárias.',
    cultura: 'O cenário é todo o Império Romano — suas estradas, cidades, sinagogas e tribunais. A cidadania romana de Paulo e a língua grega comum favorecem a missão.',
    versiculo: 'Recebereis poder... e ser-me-eis testemunhas até aos confins da terra. (Atos 1:8)',
    curiosidade: 'Foi em Antioquia, narrada em Atos, que os seguidores de Jesus foram chamados "cristãos" pela primeira vez.',
  },
  rm: {
    autor: 'Apóstolo Paulo',
    data: 'c. 57 d.C.',
    periodo: 'Século I, missão de Paulo',
    tema: 'A justificação pela fé: o evangelho é o poder de Deus para a salvação.',
    contexto: 'Carta escrita à igreja de Roma, é a exposição mais sistemática do evangelho por Paulo: todos pecaram, mas são justificados gratuitamente pela fé em Cristo, judeus e gentios igualmente.',
    cultura: 'Roma era a capital do império, com uma igreja mista de judeus e gentios. Paulo prepara terreno para uma futura visita e missão até a Espanha.',
    versiculo: 'Não me envergonho do evangelho, pois é o poder de Deus para a salvação. (Romanos 1:16)',
    curiosidade: 'A leitura de Romanos foi decisiva na conversão de Agostinho, Lutero e John Wesley — moldando a história da Igreja.',
  },
  '1co': {
    autor: 'Apóstolo Paulo',
    data: 'c. 55 d.C.',
    periodo: 'Século I, missão de Paulo',
    tema: 'Unidade, santidade e amor numa igreja cheia de problemas.',
    contexto: 'Paulo responde a divisões, imoralidade e confusões sobre dons espirituais na igreja de Corinto. Ensina sobre a cruz, a ceia, a ressurreição e o amor como o caminho supremo.',
    cultura: 'Corinto era uma cidade portuária rica, cosmopolita e notoriamente imoral. Os desafios da igreja refletem a tensão de viver a fé numa cultura permissiva.',
    versiculo: 'O amor é paciente, o amor é bondoso. (1 Coríntios 13:4)',
    curiosidade: 'O "capítulo do amor" (1 Coríntios 13) é lido em incontáveis casamentos pelo mundo todo.',
  },
  '2co': {
    autor: 'Apóstolo Paulo',
    data: 'c. 56 d.C.',
    periodo: 'Século I, missão de Paulo',
    tema: 'Força na fraqueza: o ministério autêntico em meio ao sofrimento.',
    contexto: 'A mais pessoal das cartas de Paulo, defende seu apostolado diante de críticos e revela seu coração pastoral, suas lutas e a suficiência da graça de Deus na fraqueza humana.',
    cultura: 'Paulo confronta "superapóstolos" que valorizavam eloquência e status. Ele contrasta a ostentação com a humildade da cruz.',
    versiculo: 'A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. (2 Coríntios 12:9)',
    curiosidade: 'Paulo menciona seu misterioso "espinho na carne" e uma visão do "terceiro céu" nesta carta.',
  },
  gl: {
    autor: 'Apóstolo Paulo',
    data: 'c. 48–55 d.C.',
    periodo: 'Século I, missão de Paulo',
    tema: 'Liberdade em Cristo: salvos pela fé, não pela lei.',
    contexto: 'Paulo escreve com urgência às igrejas da Galácia, que estavam sendo convencidas de que precisavam cumprir a lei judaica para se salvar. Ele defende ardorosamente a salvação somente pela graça.',
    cultura: 'A pressão de judaizantes para circuncidar os gentios ameaçava a essência do evangelho. Gálatas é a "carta magna" da liberdade cristã.',
    versiculo: 'Para a liberdade foi que Cristo nos libertou. (Gálatas 5:1)',
    curiosidade: 'Aqui aparece a famosa lista do "fruto do Espírito": amor, alegria, paz, paciência e muito mais.',
  },
  ef: {
    autor: 'Apóstolo Paulo (na prisão)',
    data: 'c. 60–62 d.C.',
    periodo: 'Século I, prisão de Paulo',
    tema: 'A Igreja como corpo de Cristo, unida em Deus por sua graça.',
    contexto: 'Escrita da prisão, Efésios celebra as riquezas espirituais em Cristo e a unidade entre judeus e gentios na Igreja, exortando a viver de modo digno dessa chamada.',
    cultura: 'Éfeso era centro do culto à deusa Ártemis e de práticas ocultas. A metáfora da "armadura de Deus" fala de batalha espiritual num contexto pagão.',
    versiculo: 'Pela graça sois salvos, por meio da fé... é dom de Deus. (Efésios 2:8)',
    curiosidade: 'A "armadura de Deus" (cap. 6) inspira-se no equipamento do soldado romano que Paulo via como prisioneiro.',
  },
  fp: {
    autor: 'Apóstolo Paulo (na prisão)',
    data: 'c. 61–62 d.C.',
    periodo: 'Século I, prisão de Paulo',
    tema: 'A alegria em Cristo, independente das circunstâncias.',
    contexto: 'Carta calorosa de agradecimento à igreja de Filipos, escrita da prisão. Apesar das cadeias, Paulo transborda alegria e ensina o contentamento e a humildade de Cristo.',
    cultura: 'Filipos era uma colônia romana orgulhosa de sua cidadania. Paulo lembra que a verdadeira cidadania dos cristãos está nos céus.',
    versiculo: 'Posso todas as coisas naquele que me fortalece. (Filipenses 4:13)',
    curiosidade: 'A palavra "alegria" (ou "regozijar") aparece cerca de 16 vezes numa carta escrita da cadeia.',
  },
  cl: {
    autor: 'Apóstolo Paulo (na prisão)',
    data: 'c. 60–62 d.C.',
    periodo: 'Século I, prisão de Paulo',
    tema: 'A supremacia e a suficiência de Cristo sobre todas as coisas.',
    contexto: 'Paulo combate falsos ensinos que rebaixavam Cristo, exaltando-o como Senhor de toda a criação e cabeça da Igreja — nele habita toda a plenitude de Deus.',
    cultura: 'Colossos enfrentava uma mistura de filosofia grega, misticismo e legalismo judaico. Paulo mostra que Cristo basta, sem necessidade de "acréscimos".',
    versiculo: 'Nele foram criadas todas as coisas... tudo subsiste por meio dele. (Colossenses 1:16-17)',
    curiosidade: 'Contém um dos mais sublimes hinos cristológicos do Novo Testamento (Colossenses 1:15-20).',
  },
  '1ts': {
    autor: 'Apóstolo Paulo',
    data: 'c. 51 d.C.',
    periodo: 'Século I, missão de Paulo',
    tema: 'Viver em santidade e esperança aguardando a volta de Cristo.',
    contexto: 'Uma das primeiras cartas de Paulo, encoraja os jovens cristãos de Tessalônica a permanecerem firmes na perseguição e esclarece dúvidas sobre a segunda vinda de Jesus.',
    cultura: 'Tessalônica era um importante centro comercial. Os novos convertidos sofriam pressão social e precisavam de firmeza e esperança.',
    versiculo: 'O próprio Senhor descerá do céu... e assim estaremos sempre com o Senhor. (1 Tessalonicenses 4:16-17)',
    curiosidade: 'Provavelmente está entre os documentos mais antigos do Novo Testamento, escrito cerca de 20 anos após a ressurreição.',
  },
  '2ts': {
    autor: 'Apóstolo Paulo',
    data: 'c. 51–52 d.C.',
    periodo: 'Século I, missão de Paulo',
    tema: 'Firmeza na esperança e correção de erros sobre o Dia do Senhor.',
    contexto: 'Paulo corrige um mal-entendido: alguns achavam que o Dia do Senhor já tinha chegado e paravam de trabalhar. Ele reafirma a esperança e exorta a perseverar e trabalhar com responsabilidade.',
    cultura: 'A expectativa acalorada do fim gerava confusão e ociosidade. Paulo equilibra esperança futura com responsabilidade presente.',
    versiculo: 'Não vos canseis de fazer o bem. (2 Tessalonicenses 3:13)',
    curiosidade: 'Dela vem o princípio "se alguém não quer trabalhar, também não coma" (3:10).',
  },
  '1tm': {
    autor: 'Apóstolo Paulo',
    data: 'c. 62–64 d.C.',
    periodo: 'Século I, últimos anos de Paulo',
    tema: 'Como conduzir e organizar a igreja com sã doutrina.',
    contexto: 'Carta pastoral ao jovem líder Timóteo, orientando-o sobre liderança, ensino saudável, culto e o caráter dos que servem na igreja de Éfeso.',
    cultura: 'Timóteo era jovem e enfrentava falsos mestres. Paulo lhe dá autoridade e instruções práticas de gestão eclesiástica.',
    versiculo: 'Ninguém despreze a tua mocidade; mas sê exemplo dos fiéis. (1 Timóteo 4:12)',
    curiosidade: 'É uma das três "epístolas pastorais", junto com 2 Timóteo e Tito, focadas na liderança da igreja.',
  },
  '2tm': {
    autor: 'Apóstolo Paulo (na prisão, perto do fim)',
    data: 'c. 64–67 d.C.',
    periodo: 'Século I, martírio iminente de Paulo',
    tema: 'Perseverança fiel até o fim, guardando a Palavra.',
    contexto: 'A última carta de Paulo, escrita da prisão às vésperas de sua morte. É seu testamento espiritual a Timóteo: sofra pelo evangelho, guarde a fé e pregue a Palavra em toda ocasião.',
    cultura: 'Sob a perseguição de Nero, ser cristão podia custar a vida. Paulo escreve sabendo que sua execução se aproxima.',
    versiculo: 'Combati o bom combate, acabei a carreira, guardei a fé. (2 Timóteo 4:7)',
    curiosidade: 'Contém a célebre afirmação de que "toda a Escritura é inspirada por Deus" (3:16).',
  },
  tt: {
    autor: 'Apóstolo Paulo',
    data: 'c. 62–64 d.C.',
    periodo: 'Século I, últimos anos de Paulo',
    tema: 'A boa doutrina produz boas obras.',
    contexto: 'Paulo instrui Tito, deixado na ilha de Creta, a organizar as igrejas, nomear líderes íntegros e ensinar como a graça de Deus transforma o modo de viver.',
    cultura: 'Os cretenses tinham fama de indisciplinados. Paulo enfatiza integridade e bom testemunho num ambiente moralmente difícil.',
    versiculo: 'A graça de Deus... nos ensina a viver de modo sensato, justo e piedoso. (Tito 2:11-12)',
    curiosidade: 'É uma carta curta e prática, verdadeiro manual de liderança e vida cristã.',
  },
  fm: {
    autor: 'Apóstolo Paulo (na prisão)',
    data: 'c. 60–62 d.C.',
    periodo: 'Século I, prisão de Paulo',
    tema: 'Perdão e reconciliação: o evangelho transforma relações.',
    contexto: 'Bilhete pessoal a Filemom, pedindo que receba de volta seu escravo fugitivo Onésimo — agora convertido — não mais como escravo, mas como irmão amado em Cristo.',
    cultura: 'A escravidão era estrutural no mundo romano. Sem abolir de imediato o sistema, Paulo planta a semente que o mina: a igualdade fraterna em Cristo.',
    versiculo: 'Já não como escravo... mas como irmão amado. (Filemom 1:16)',
    curiosidade: 'É a carta mais curta e pessoal de Paulo, um raro vislumbre de sua ternura pastoral.',
  },
  hb: {
    autor: 'Desconhecido (anônimo)',
    data: 'c. 60–70 d.C.',
    periodo: 'Século I, antes da queda de Jerusalém',
    tema: 'A superioridade de Cristo: ele é melhor que tudo o que veio antes.',
    contexto: 'Dirigida a cristãos de origem judaica tentados a voltar ao judaísmo, mostra que Jesus é superior aos anjos, a Moisés e ao sacerdócio antigo — o sacrifício perfeito e definitivo.',
    cultura: 'Rica em referências ao culto, ao Templo e aos sacrifícios do Antigo Testamento, dialoga com quem conhecia profundamente a tradição judaica.',
    versiculo: 'A fé é a certeza daquilo que esperamos e a prova das coisas que não vemos. (Hebreus 11:1)',
    curiosidade: 'O capítulo 11 é a famosa "galeria dos heróis da fé", de Abel a Moisés.',
  },
  tg: {
    autor: 'Tiago, irmão de Jesus',
    data: 'c. 45–49 d.C.',
    periodo: 'Século I, igreja primitiva',
    tema: 'Fé prática: a fé verdadeira se mostra em obras.',
    contexto: 'Provavelmente a carta mais antiga do Novo Testamento, é um guia prático de sabedoria cristã: controle da língua, cuidado com os pobres, paciência nas provações e coerência entre crer e viver.',
    cultura: 'Com estilo próximo dos Provérbios e do Sermão do Monte, dirige-se a cristãos judeus dispersos, enfrentando pobreza e injustiça.',
    versiculo: 'A fé, se não tiver obras, é morta em si mesma. (Tiago 2:17)',
    curiosidade: 'Tiago não seguia Jesus antes da ressurreição — tornou-se depois líder da igreja de Jerusalém.',
  },
  '1pe': {
    autor: 'Apóstolo Pedro',
    data: 'c. 62–64 d.C.',
    periodo: 'Século I, início das perseguições',
    tema: 'Esperança viva e firmeza no sofrimento.',
    contexto: 'Pedro escreve a cristãos perseguidos e dispersos pela Ásia Menor, encorajando-os a permanecer firmes, a viver de forma exemplar e a manter a esperança na herança eterna, seguindo o exemplo de Cristo.',
    cultura: 'Sob crescente hostilidade romana, os cristãos eram "estrangeiros e peregrinos". Pedro os ajuda a sofrer com dignidade e testemunho.',
    versiculo: 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós. (1 Pedro 5:7)',
    curiosidade: 'Pedro chama a igreja de "sacerdócio real" e "nação santa", aplicando aos cristãos títulos antes dados a Israel.',
  },
  '2pe': {
    autor: 'Apóstolo Pedro',
    data: 'c. 64–67 d.C.',
    periodo: 'Século I, últimos dias de Pedro',
    tema: 'Crescer na graça e resistir aos falsos mestres.',
    contexto: 'Escrita perto da morte de Pedro, alerta contra falsos mestres e zombadores que negavam a volta de Cristo, exortando os fiéis a crescer no conhecimento e a viver santamente.',
    cultura: 'O adiamento aparente da volta de Jesus gerava ceticismo. Pedro reafirma a certeza do Dia do Senhor e a paciência de Deus.',
    versiculo: 'O Senhor... é longânimo para convosco, não querendo que alguém se perca. (2 Pedro 3:9)',
    curiosidade: 'Pedro chama as cartas de Paulo de "Escrituras", reconhecendo-as como inspiradas ainda no séc. I.',
  },
  '1jo': {
    autor: 'Apóstolo João',
    data: 'c. 85–95 d.C.',
    periodo: 'Fim do século I',
    tema: 'Deus é amor e Deus é luz: como ter certeza da vida eterna.',
    contexto: 'João escreve para dar segurança aos crentes e combater falsos ensinos que negavam a humanidade de Cristo. Insiste em três marcas do cristão: fé verdadeira, obediência e amor fraternal.',
    cultura: 'Contra o gnosticismo incipiente, que separava espírito e matéria, João afirma que Jesus veio de fato "em carne".',
    versiculo: 'Deus é amor, e quem permanece no amor permanece em Deus. (1 João 4:16)',
    curiosidade: 'Não tem saudação nem despedida típicas de carta — parece mais um sermão de amor do apóstolo idoso.',
  },
  '2jo': {
    autor: 'Apóstolo João',
    data: 'c. 85–95 d.C.',
    periodo: 'Fim do século I',
    tema: 'Andar na verdade e no amor, com discernimento.',
    contexto: 'Breve carta à "senhora eleita" (uma igreja ou pessoa), unindo dois temas caros a João: permanecer na verdade e amar uns aos outros, evitando os enganadores.',
    cultura: 'A hospitalidade itinerante era vital na igreja primitiva; João alerta para não acolher quem propagava falsos ensinos.',
    versiculo: 'E o amor é este: que andemos segundo os seus mandamentos. (2 João 1:6)',
    curiosidade: 'Com apenas 13 versículos, é um dos livros mais curtos do Novo Testamento.',
  },
  '3jo': {
    autor: 'Apóstolo João',
    data: 'c. 85–95 d.C.',
    periodo: 'Fim do século I',
    tema: 'Hospitalidade, fidelidade e a diferença entre servir e dominar.',
    contexto: 'Carta pessoal a Gaio, elogiando sua hospitalidade aos missionários, repreendendo o arrogante Diótrefes e recomendando o fiel Demétrio.',
    cultura: 'Retrata os bastidores da igreja primitiva: apoio a obreiros itinerantes e disputas de liderança local.',
    versiculo: 'Não imites o mal, mas o bem. (3 João 1:11)',
    curiosidade: 'É o livro mais curto da Bíblia em número de palavras no original grego.',
  },
  jd: {
    autor: 'Judas, irmão de Tiago (e de Jesus)',
    data: 'c. 65–80 d.C.',
    periodo: 'Século I, igreja primitiva',
    tema: 'Contender pela fé diante de falsos mestres.',
    contexto: 'Judas exorta os cristãos a "batalhar pela fé" contra mestres imorais que se infiltraram na igreja, lembrando exemplos de juízo e chamando à perseverança e à compaixão.',
    cultura: 'Cita tradições judaicas (como o livro de Enoque), mostrando o rico repertório cultural da igreja primitiva.',
    versiculo: 'Àquele que é poderoso para vos guardar de tropeçar. (Judas 1:24)',
    curiosidade: 'Encerra com uma das mais belas doxologias (louvores finais) de toda a Bíblia.',
  },
  ap: {
    autor: 'Apóstolo João (na ilha de Patmos)',
    data: 'c. 95 d.C.',
    periodo: 'Fim do século I, perseguição de Domiciano',
    tema: 'A vitória final de Cristo e a esperança de um novo céu e nova terra.',
    contexto: 'Escrito no exílio, Apocalipse é uma revelação em visões simbólicas sobre a luta entre o bem e o mal, o julgamento e o triunfo definitivo de Cristo, culminando na nova Jerusalém.',
    cultura: 'Gênero apocalíptico, cheio de símbolos e números, encorajava cristãos perseguidos a permanecerem fiéis, garantindo que Deus vence no fim.',
    versiculo: 'Eu sou o Alfa e o Ômega, o princípio e o fim. (Apocalipse 21:6)',
    curiosidade: '"Apocalipse" significa "revelação". É o único livro que promete bênção a quem o lê (1:3) e encerra toda a Bíblia com a promessa "Vem, Senhor Jesus".',
  },
};

